### ISSUE TITLE
路由里使用报错

### ISSUE THREAD

**Issue by lovelyJason** [CJY0208/react-activation#10]
Alive组件
`
...
render() {
        return (
            <div>
                <button onClick={() => this.setState({count:this.state.count++})}>add</button>
                {this.state.count}
            </div>
        )
 }`
路由:
`
router
...
<Router>
            <Switch>
                <Route path="/" exact component={Home}></Route>
                {/* <Route path="/alive" exact component={Alive}></Route> */}
                <Route path="/alive" exact render={props => (
                    <KeepAlive>
                        <Alive {...props}/>
                    </KeepAlive>
                )}></Route>
            </Switch>
        </Router>
`
然后控制台报一堆红
Cannot read property 'keep' of undefined

The above error occurred in the <KeepAlive> component:

**Comment by CJY0208** [comment]
有没有放置 AliveScope 外层呢？

**Comment by lovelyJason** [comment]
> 有没有放置 AliveScope 外层呢？

这个没有.我看的你文档里也是这么写的,没有包裹AliveScope.
Multiple Cache这一块

**Comment by CJY0208** [comment]
需要将 AliveScope 放置在不会被卸载的地方，我文档没写清楚

可以参考基础用例加上 AliveScope
