### ISSUE TITLE
antd calendar组件缓存问题

### ISSUE THREAD

**Issue by Rookierk** [CJY0208/react-activation#100]
`<Provider store={store}>
    <AliveScope>
      <KeepAlive>
        <Calendar />
      </KeepAlive>
    </AliveScope>
  </Provider>`
缓存calendar组件就会出现hooks前后不一致的问题，报错信息如下
![CB31F8C4-30FE-4D78-8F57-AF8340B76464](https://user-images.githubusercontent.com/79496007/108800899-50403f80-75cf-11eb-89e4-cca96444b39d.png)
经debug发现fiexdContext出现了渲染前后数量不一致的情况，
本人初学React小白，实在找不到问题出在哪，希望大大们看一下-。-

**Comment by CJY0208** [comment]
与 #99 类似，关闭此 issue，后续尝试重构此处逻辑

**Comment by CJY0208** [comment]
0.8.1 中暂时修复了 Rendered more hooks 的问题~ 可以试试
