### ISSUE TITLE
在TS项目中报错

### ISSUE THREAD

**Issue by WhiteYin** [CJY0208/react-activation#105]
```
TypeScript error in E:/node_modules/react-activation/index.d.ts(54,99):
'{' or ';' expected.  TS1144

    52 |
    53 | export declare function withActivation<C extends ComponentType<GetProps<C>>>(component: C): C
  > 54 | export declare function withAliveScope<C extends ComponentType<GetProps<C>>>(component: C): class name {
       |                                                                                                   ^
    55 |   constructor(parameters) {
    56 |
    57 |   }
```

**Comment by CJY0208** [comment]
尴尬，不记得为啥这么写了，我改回去

**Comment by tianliuj** [comment]
0.10.1这个版本又有这个问题

**Comment by tianliuj** [comment]
PR是啥意思呀，项目的具体版本号嘛
我刚以为是0.10.1这个版本的问题，就降到了0.9.12，还是有问题
    "react": "^16.13.1",
    "react-activation": "^0.9.12",
    "react-app-rewired": "^2.1.6",
    "react-data-grid": "^5.0.5",
    "react-dom": "^16.13.1",
    "react-hot-loader": "^4.12.21",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "react-sortable-hoc": "^2.0.0",
    "reactour": "^1.18.6",
    "styled-components": "^4.4.1",
    "typescript": "^3.8.3",

**Comment by tianliuj** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/34020954/165059181-b4d7968f-1187-4f25-bc96-ee64328f7bd3.png">
