### ISSUE TITLE
AliveScope 在 Provider 外部使用有问题

### ISSUE THREAD

**Issue by Haixiang6123** [CJY0208/react-activation#106]
如图所示

![image](https://user-images.githubusercontent.com/17061654/111618806-c5461400-881f-11eb-855a-56f3adf17e99.png)

把 <AliveScrop> 放到 Provider 外面会有上面的错误，请问有哪些可能会导致这个问题呢？我把 <AliveScrop> 删掉就不会有错误了。

**Comment by CJY0208** [comment]
放 Provider 内部好一些，是什么功能的 Provider？

**Comment by Haixiang6123** [comment]
我关了，这个是因为别的地方做了两次渲染才导致的问题，不是由于 Provider 引起的

**Comment by CJY0208** [comment]
ok
