### ISSUE TITLE
第一次进入页面会执行多次挂载

### ISSUE THREAD

**Issue by mathcw** [CJY0208/react-activation#107]
当页面中含有antd的table组件时 使用keepalive包裹当前页面会导致页面的额多次挂载
[最小复现](https://codesandbox.io/s/umi-keep-alive-tabs-demo-forked-dgixz)
在这页面可以看到mount逻辑被走了两次 而且奇怪的是点击“显示”按钮来控制table的显示后
又走了一遍

**Comment by mathcw** [comment]
antd:4.14.0 umi-plugin-keep-alive:0.0.1-beta.24

**Comment by mathcw** [comment]
@CJY0208 大佬求助

**Comment by mathcw** [comment]
测试了一下 0.7.4 没有这个问题

**Comment by lishaoxin123** [comment]
> 当页面中含有antd的table组件时 使用keepalive包裹当前页面会导致页面的额多次挂载
> [最小复现](https://codesandbox.io/s/umi-keep-alive-tabs-demo-forked-dgixz)
> 在这页面可以看到mount逻辑被走了两次 而且奇怪的是点击“显示”按钮来控制table的显示后
> 又走了一遍

同遇到这个问题，老哥有解决方案？

**Comment by mathcw** [comment]
现在看起来是autoFixContext对React 17+的兼容问题

**Comment by CJY0208** [comment]
@mathcw 没有对 React 17+ 静默支持 autoFixContext，不过 autoFixContext 的逻辑先前确实存在问题，导致了多次 did mount

0.9.0 中尝试进行了修复，可以试试，并且 0.9.0 中不再需要放置 AliveScope 外层~
