### ISSUE TITLE
为什么最新的tab永远drop不了

### ISSUE THREAD

**Issue by wzz5304** [CJY0208/react-activation#108]
目前的想法：

首先，兼容同步 drop 的场景：在 drop 期间如果组件重新激活了，则取消 drop 行为

后续：drop 返回 Promise 类型，以便允许依赖 await 语法进行异步卸载行为完成后的事件

```js
await drop('demo-list')
console.log('demo-list dropped ')
```

考虑参考 React class component 的 `setState` 方法，兼容 callback 参数（不一定做）

```js
drop('demo-list', () => {
  console.log('demo-list dropped ')
})
```

_Originally posted by @CJY0208 in https://github.com/CJY0208/react-activation/issues/72#issuecomment-713243026_

**Comment by CJY0208** [comment]
你的问题应该和引用的 issue 不是同一个问题

drop 的条件为组件处于未激活状态，如果当前路由决定了组件必须处于激活状况，则无法 drop

需要先进行路由跳转，并在跳转完成后再进行 drop

后续针对此问题会做一个修复尝试，在执行了 drop 之后一定时间内监听组件的激活状态变化，如果在限定时间内变为了未激活态，则执行 drop
