### ISSUE TITLE
vite下如何设置这个库的babel？

### ISSUE THREAD

**Issue by pincman** [CJY0208/react-activation#109]
刚刚从cra转vite,发现不支持babel配置，请问如何使用这个库呢？

**Comment by CJY0208** [comment]
没用过 vite，不太清楚，试试这个？
https://www.npmjs.com/package/vite-babel-plugin

**Comment by nangongmo** [comment]
@CJY0208 这个只能vite1,vite2用不了,目前其他组件均已适配,就这个keep-alive无法适配，很尴尬😓

**Comment by CJY0208** [comment]
其他组件的 babel 也能在 vite2 中用了吗，是如何使用的？能否提供 demo 示例，我看看是不是 activation/babel 的版本问题

**Comment by nangongmo** [comment]
@CJY0208 vite不支持babel的，一般的用babel的插件都是hack后的搞法，比如动态导入
```typescript
import styleImport from 'vite-plugin-style-import';

export function configStylePlugin(isBuild: boolean) {
    if (!isBuild) return [];
    const stylePlugin = styleImport({
        libs: [
            {
                libraryName: 'antd',
                esModule: true,
                resolveStyle: (name) => {
                    return `antd/es/${name}/style/index`;
                },
            },
        ],
    });
    return stylePlugin;
}
```

**Comment by CJY0208** [comment]
感觉可以参考 vite 官方的这个插件搞一手

https://github.com/vitejs/vite/blob/v2.1.5/packages/plugin-vue-jsx/README.md

**Comment by nangongmo** [comment]
@CJY0208 大神靠你了，我一个业余前端搞不出来这种名堂😄

**Comment by CJY0208** [comment]
@pincman vite 支持正在 PR 阶段：[添加vite 2.0兼容](https://github.com/CJY0208/react-node-key/pull/4)

感谢 @zebing

**Comment by waterJLuck** [comment]
你好 请问vite2已经适配了吗

**Comment by CJY0208** [comment]
此问题合并到 #168 
@waterJLuck
