### ISSUE TITLE
react项目多页应用，依赖react-activation react-router-dom 实现多路由缓存，报错，事实只能实现单个挂载路由缓存

### ISSUE THREAD

**Issue by rdlei** [CJY0208/react-activation#110]

**Comment by CJY0208** [comment]
这块数组结构，加上 key 字段试试，目前可能是被 keep-alive babel 插件认为是同一个 KeepAlive 标记了，共用了缓存

![image](https://user-images.githubusercontent.com/18415774/113822774-6fc2ae80-97b0-11eb-896f-81330e664c5d.png)

**Comment by rdlei** [comment]
goodLuck

**Comment by CJY0208** [comment]
加上 key 是解决了吗？
