### ISSUE TITLE
当前缓存页面useActivate会执行多次

### ISSUE THREAD

**Issue by ChuangShiOS** [CJY0208/react-activation#111]
你好，我发现我的当前缓存页面useActivate会执行多次，能帮我看看我的写法不对的地方么？线上地址：https://codesandbox.io/s/react-activation-shili-forked-5w0kf?file=/src/index.js

**Comment by CJY0208** [comment]
似乎和 React.StrictMode 有关

**Comment by ChuangShiOS** [comment]
嗯嗯 太好了 果然是这个问题 非常感谢哈
