### ISSUE TITLE
antd的表单、分页搭配使用问题

### ISSUE THREAD

**Issue by xiaobinwu** [CJY0208/react-activation#112]
你好，我在使用您这个插件的时候，我使用antd的表单、分页，填了之后切换路由，然后切回来，之前填写的值没有回显，您这个的底层实现是不是不支持呀？我看React.createPortal 实现的就没问题

**Comment by CJY0208** [comment]
由于借助了 babel 插件对不同节点进行标记区分，react-activation 达成缓存的条件相较于 react-keep-alive 要苛刻些，得以实现精确度更好的缓存控制，你的业务场景是支持的，但书写方式可能导致 activation 认为是不同的缓存标记，所以没实现你的需求

可以提供你的场景 demo 来做排查

**Comment by ChuangShiOS** [comment]
我也是用antd，发现没有问题哦

**Comment by CJY0208** [comment]
无反馈，暂时关闭
