### ISSUE TITLE
react---rouer---push   时候 想要页面刷新怎么炒作

### ISSUE THREAD

**Issue by flyzhaowu** [CJY0208/react-activation#113]

**Comment by CJY0208** [comment]
不明白你的意思

**Comment by flyzhaowu** [comment]
页面路由pop的时候想要保存状态 push的时候想要页面重新创建，等于重新刷新一下页面

**Comment by flyzhaowu** [comment]
![image](https://user-images.githubusercontent.com/33539683/114646797-82883680-9d0e-11eb-84be-616451a3d499.png)
这里进去  我就不想要展示缓存的页面  想要页面重新执行一次（刷新）

**Comment by CJY0208** [comment]
和 drop 并列的有一个叫做 refresh 的方法，可以用这个来进行刷新，文档里漏写了

**Comment by flyzhaowu** [comment]
好~~~谢谢~~

**Comment by TimRChen** [comment]
> 和 drop 并列的有一个叫做 refresh 的方法，可以用这个来进行刷新，文档里漏写了

大佬可否将此方法更新到文档中

**Comment by CJY0208** [comment]
> > 和 drop 并列的有一个叫做 refresh 的方法，可以用这个来进行刷新，文档里漏写了
> 
> 大佬可否将此方法更新到文档中

OK，加了
