### ISSUE TITLE
页面有标签，当新建/编辑角色后，回到列表页如何根据之前缓存的筛选条件，拿到最新的数据

### ISSUE THREAD

**Issue by JTenacity** [CJY0208/react-activation#115]
![image](https://user-images.githubusercontent.com/19601885/118241647-fa44af00-b4ce-11eb-9f95-b27cb4dab9f6.png)
列表的筛选是有缓存的。回到列表页后缓存不清空的情况下，想重新调取接口。目前useeffect是不执行的。
@CJY0208

**Comment by CJY0208** [comment]
可以使用 useActivate 生命周期，在组件重新激活后进行请求

**Comment by JTenacity** [comment]
现在是对已有项目进行标签页开发的，如果要是用useActivate进行处理的话，就要在很多页面都要进行一遍处理。不想让页面组件的逻辑因为标签而产生新的开发。 在实现上还有其它更好的吗？ @CJY0208

**Comment by CJY0208** [comment]
没有更好的办法，激活后触发特定请求这是个业务性质的行为，activation 无法甄别业务开发者想做什么
