### ISSUE TITLE
请问首页，列表页，详情页三个页面，列表页缓存后，如何使用让列表页从首页点进去是没有缓存的呢

### ISSUE THREAD

**Issue by sunjun-coder** [CJY0208/react-activation#116]
请问，请问首页，列表页，详情页三个页面，列表页缓存后，如何使用让列表页从首页点进去是没有缓存的呢？

**Comment by CJY0208** [comment]
首页进入列表页之前，先进行 drop('列表页') 操作

**Comment by sunjun-coder** [comment]
> 首页进入列表页之前，先进行drop（'列表页'）操作

有什么办法把这个逻辑处理放在列表页吗。因为如果我有别的页面A、B 页面也要缓存，那么我每加一个缓存页面都要在进入该页面前先做一层drop（'A、B '）操作。

**Comment by CJY0208** [comment]
业务上记录上一个路由的信息，然后列表页 useActivate 后看上一个路由是否是首页，是的话执行 refresh('列表页')

这个如何？

**Comment by sunjun-coder** [comment]
> 业务上记录上一个路由的信息，然后列表页 useActivate 后看上一个路由是否是首页，是的话执行 refresh('列表页')
> 
> 这个如何？
请问refresh是个什么操作呢，reload?
我试着在useActivate判断后drop掉，页面变成了空白

**Comment by CJY0208** [comment]
和 drop 从同样的地方取出 refresh 方法，和 reload 的概念类似，最好延时一些做这件事情

**Comment by sunjun-coder** [comment]
> refresh

非常感谢，refresh是要加个setTimeout，不然页面直接卡死掉了
