### ISSUE TITLE
useReducer、全局store在keep-alive中 异步请求没有渲染页面

### ISSUE THREAD

**Issue by snailsph** [CJY0208/react-activation#120]

**Comment by CJY0208** [comment]
需要提供相关场景描述或复现的示例

**Comment by zyzxrj** [comment]
你好这个库是不支持网络请求列表当前滚动位置的缓存吗，我尝试了本地数据列表位置是可以缓存的，但是通过网络请求绘制的列表到详情再返回列表，列表位置没有缓存

**Comment by CJY0208** [comment]
@zyzxrj 支持的，滚动位置的缓存只和页面高度，以及当前滚动位置相关，和数据没有直接关系的，需要检查一下你的使用方式

另外讨论和本 issue 不相关，可以另开 issue 讨论
