### ISSUE TITLE
在<keepAlive>中直接放置DOM显示state，无法感知useState更新 【生产问题 急！！！】

### ISSUE THREAD

**Issue by xiaoxiaofan123** [CJY0208/react-activation#121]
![截屏2021-06-21 下午4 02 15](https://user-images.githubusercontent.com/18550815/122728095-58249d80-d2aa-11eb-8ce5-913b3ed0db03.png)
如图片 在keepAlive中放了一个div，显示num state的值，点击addNum按钮后num值不会更新。点击toggle隐藏后再次点击显示 会显示最新的值
项目中使用（用的umi-plugin-keep-alive）时遇到了类似的问题，但在另一个项目中又是正常的，不知道是否跟react版本有关

demo地址：https://codesandbox.io/s/zuijian-react-keepalive-shixian-forked-euemd?file=/src/index.js
react、reactDom版本：16.8.6
umi-plugin-keep-alive:0.0.1-beta.28

**Comment by CJY0208** [comment]
先不要跨 KeepAlive 传递数据，尽量完整包裹需要缓存的组件

如果现在实在比较着急，可以先使用上下文来尝试修复，KeepAlive 目前对上下文的修复是良好的

```jsx

import { createContext } from 'react

const { Provider, Consumer } = createContext()

function App() {
  const [num, setNum] = useState(0)

  return (
    <Provider value={num}>
      <KeepAlive>
        <Consumer>
          {num => (
            <div>{num}</div>
          )}
        </Consumer>
      </KeepAlive>
    </Provider>
  )
}
```

**Comment by xiaoxiaofan123** [comment]
@CJY0208 好的 我试试看 谢谢回复

**Comment by xiaoxiaofan123** [comment]
> @CJY0208 好的 我试试看 谢谢回复

作者你好 
第一种方式 因为被包裹的组件需要和外界的平级组件交互，所以不可避免跨KeepAlive传递数据
第二种方式 我在demo里试了 好像value并不能渲染出来 不知道是不是我写的不对（把keepAlive去掉是正常的）
![截屏2021-06-21 下午7 17 33](https://user-images.githubusercontent.com/18550815/122753820-5fa57000-d2c5-11eb-87d3-c9a373263e87.png)

**Comment by CJY0208** [comment]
创建上下文的动作要提出去

![image](https://user-images.githubusercontent.com/18415774/122847603-99fd2480-d33a-11eb-8d4d-ae0ff256af7f.png)

**Comment by CJY0208** [comment]
看了一下，发现你用的并不是 react-activation... 只是最简示例中的 KeepAlive

最简示例中的 KeepAlive 缺失许多功能，包括上边说的问题，使用 actication 的话应该不会有问题

如果是 umi-plugin-keep-alive 的问题，可以再开一个新 issues 单独讨论，这个先关了
