### ISSUE TITLE
能否考虑不要将_nk 属性映射到dom节点上? 看起来比较臃肿，还需要配置babel

### ISSUE THREAD

**Issue by yinran100** [CJY0208/react-activation#124]

**Comment by CJY0208** [comment]
React 16 后会默认将 jsx 上的所有属性映射到真实 dom 上，这个行为目前似乎没找到可避免的方式，所以目前暂时还无法调整...
https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html
