### ISSUE TITLE
在electron-app中，增加react-activation后，运行可执行文件时报错

### ISSUE THREAD

**Issue by zspishere** [CJY0208/react-activation#125]
Hi，我在[electron-vite-react-starter](https://github.com/Harhao/electron-vite-react-starter)项目基础上，增加了一个当前package：[react-activation](https://github.com/CJY0208/react-activation)，实现组件状态的自动保存。

## 错误描述

开发过程中，功能正常。Build之后，执行unpack目录的electron-vite-react-starter.exe，功能无法运行，报两个同样的错误
```
vendor.83d6ef6d.js:4784 Error: Minified React error #130;
visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

## 错误重现步骤

- yarn add react-activation
- yarn dev  -- 功能正常
- yarn build 
- 运行`electron-vite-react-starter\release\0.0.1\win-unpacked\electron-vite-react-starter.exe`，发现上述两个报错

![](https://user-images.githubusercontent.com/19356426/124407279-1568c800-dd76-11eb-9a15-bcce61b84848.png)

## 复现错误的MR
https://github.com/zspishere/electron-vite-react-starter/commit/55351ece2269d3b048fd0d7c8f5dafb549917266

## 复现错误的Repo
https://github.com/zspishere/electron-vite-react-starter

## 补充

通过[create-react-app](https://github.com/facebook/create-react-app)创建`react17`的项目，增加[react-activation](https://github.com/CJY0208/react-activation)，以及相应的代码[src/renderer/Test.jsx](https://github.com/zspishere/electron-vite-react-starter/blob/55351ece22/src/renderer/Test.jsx)

- 开发过程，功能正常
- build之后，通过浏览器直接访问`http://localhost:5000/`，`功能也正常`

麻烦有时间帮忙确认是vite2的问题，还是[react-activation](https://github.com/CJY0208/react-activation)的问题。

**Comment by zspishere** [comment]
我又做了两个测试，都是基于`webpack`打包，打包后功能正常。
结论：感觉像是vite2的锅，或者我的vite2配置不对。。。

- 基于[electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)创建的electron应用，增加[react-activation](https://github.com/CJY0208/react-activation)，以及相应的代码[src/renderer/Test.jsx](https://github.com/zspishere/electron-vite-react-starter/blob/55351ece22/src/renderer/Test.jsx)。Build之后，运行时功能正常，不会报错

- 基于[create-react-app](https://github.com/facebook/create-react-app)创建一个react应用，然后，`yarn add electron electron-builder react-activation`，再添加相关代码[src/renderer/Test.jsx](https://github.com/zspishere/electron-vite-react-starter/blob/55351ece22/src/renderer/Test.jsx)。Build之后，运行时功能正常，不会报错

**Comment by CJY0208** [comment]
是的，目前这个工具没有在 vite 上做过测试...不清楚需要做哪些调整

**Comment by rocketsbigfan** [comment]
请问答主后面是如何解决的，因为vite build命令时是rollup来打包的

**Comment by CJY0208** [comment]
前段时间一个小伙伴有帮忙对 vite 做支持，可以看看 example 是否有帮助
https://github.com/zebing/react-node-key/blob/a263a75a23ce9bef414ba3e5b7cb792d11b28a14/examples/vite/vite.config.js

**Comment by zspishere** [comment]
感谢 @CJY0208  支持！
我按照example做了修改，问题依旧，麻烦帮忙看下`我的改动是否存在问题`。

- 改动之后的仓库地址（branch是node-key）：
https://github.com/zspishere/vite2-react-app/tree/node-key

- 改动的PR：
https://github.com/zspishere/vite2-react-app/commit/c6f0f1b92e66d354aef9150a84018cdf2b48c95f

再次感谢~

**Comment by zspishere** [comment]
问题已解决，原因以及解决方法，可以参考：https://github.com/vitejs/vite/issues/4123

**Comment by rocketsbigfan** [comment]
非常感谢，其实就一句话，不要使用es6的默认导出
