### ISSUE TITLE
组件没有缓存效果

### ISSUE THREAD

**Issue by liyanhui100** [CJY0208/react-activation#126]
按照说明做好配置后，通过devTool能看到有keeper，但是跳转回组件没有激活组件的componentDidActivate生命周期。组件的didMount, unMount生命周期也照样会触发。请问有可能是哪里出问题了

**Comment by CJY0208** [comment]
可以提供你的使用方式截图或者代码吗？我看一下

**Comment by CJY0208** [comment]
无响应，暂时关闭
