### ISSUE TITLE
@ant-design/pro-table组件外使用KeepAlive，从缓存读取的pro-table，里面的数据样式发生改变

### ISSUE THREAD

**Issue by 767746649zyy** [CJY0208/react-activation#129]
![image](https://user-images.githubusercontent.com/23164065/125432389-a6663f0a-577e-4eb6-af64-feb5bdb442e5.png)
![image](https://user-images.githubusercontent.com/23164065/125432527-f486f5b0-985e-4cbf-b095-8ac030c0478d.png)
ant-design/pro-table组件外使用KeepAlive，从缓存读取的pro-table时，里面的数据样式发生改变，里面的“...”应该显示完整数据，pro-table的column中没有设置ellipsis属性的字段，则没有这个问题，求解决方案

**Comment by 767746649zyy** [comment]
![image](https://user-images.githubusercontent.com/23164065/125433422-cf714713-daf0-4a59-b9ef-65aee75a656b.png)

**Comment by 767746649zyy** [comment]
![image](https://user-images.githubusercontent.com/23164065/125433552-a47a197d-08ac-4770-ab1b-ef1caa28bf3c.png)

**Comment by CJY0208** [comment]
可以提供简单的用例复现吗？

**Comment by biggbb777** [comment]
@767746649zyy @CJY0208  antd更新到最新版问题解决

**Comment by CJY0208** [comment]
@biggbb777 感谢，那这个问题就先关闭了
