### ISSUE TITLE
<KeepAlive/> 包裹的组件中，setState 过多会有错误，windows 系统下输入框输入过快明显的卡顿。

### ISSUE THREAD

**Issue by x-codon** [CJY0208/react-activation#13]
<KeepAlive /> Too many transient updates, may have encountered an infinite loop of updates, forced to pause the update
There are serious performance issues with the update results you are currently seeing
May encounter an implied bug, please don't use KeepAlive and contact the author to solve

**Comment by CJY0208** [comment]
能否提供所使用的 activation 版本呢？最好能提供可复现的场景，感谢

**Comment by CJY0208** [comment]
mark: 使用方式有误导致，不过亦发现了一些对性能本身的影响，已修正
