### ISSUE TITLE
无法在组件mount时拿到dom节点的大小

### ISSUE THREAD

**Issue by VeronicaF** [CJY0208/react-activation#131]
https://codesandbox.io/s/umi-keep-alive-tabs-demo-forked-orcmh?file=/src/pages/chart.js

![image](https://user-images.githubusercontent.com/20827900/126097029-89e2162b-71da-4de5-89bd-d3e7f31eaae8.png)

![image](https://user-images.githubusercontent.com/20827900/126097047-6474d5ca-da23-448f-a388-ad6c4509d897.png)

如示例，会导致一些依赖于dom大小的库出现不可控行为，如echarts、threejs，有没有优雅的解决办法呢？

**Comment by CJY0208** [comment]
函数式组件暂无好的方案，建议是封装一个自定义 useMount，在其内部加 setTimeout 延时操作

或者换成 class 组件配合 withActivation 使用

参考文档[Breaking Change 由实现原理引发的额外问题](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#breaking-change-%E7%94%B1%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86%E5%BC%95%E5%8F%91%E7%9A%84%E9%A2%9D%E5%A4%96%E9%97%AE%E9%A2%98)

![image](https://user-images.githubusercontent.com/18415774/126097467-3e2fc3fb-bb12-49c3-b764-b4db166f64d5.png)
