### ISSUE TITLE
使用vtie做为构建工具，开发模式下没有问题，构建完部署之后，报错

### ISSUE THREAD

**Issue by rocketsbigfan** [CJY0208/react-activation#132]
版本：
vite2.0
react17
react-router17
react-activation0.9.4

报错截图
![image](https://user-images.githubusercontent.com/20547894/126116968-93d5eaff-e4fc-4d31-a41d-cb75f633dfda.png)
![image](https://user-images.githubusercontent.com/20547894/126117012-24fcbca1-604e-43a4-b9f3-40413b75c4dc.png)

代码
```javascript
<Route
  key={route.path || index}
  path={route.path}
  exact={route.exact}
  strict={route.strict}
  render={props => {
    const renderChildRoutes = renderRoutes(route.routes);
    // route存在component时进循环
    if (route.component) {
      // 有子route时
      if (renderChildRoutes) {
        return (
          <Suspense fallback={<PageLoading />}>
            <route.component route={route} {...props}>
              {renderChildRoutes}
            </route.component>
          </Suspense>
        );
      }
      if (noNeedCachePath.includes(route.path)) {
        // 不需要缓存路由下的内容时
        return (
          <Suspense fallback={<PageLoading />}>
            <route.component route={route} {...props} />
          </Suspense>
        );
      }
      // 输出需要缓存的路由
      return (
        <Suspense fallback={<PageLoading />}>
          <KeepAlive name={route.path} title={route.title}>
            <route.component route={route} {...props} />
          </KeepAlive>
        </Suspense>
      );
    }
    // default
    return renderChildRoutes;
  }}
/>
```
当去掉keepalive功能时，可以正常使用的。

**Comment by rocketsbigfan** [comment]
还请作者有时间帮我看一下

**Comment by CJY0208** [comment]
能否提供项目 demo？近期有做 vite 的插件适配，是否有用上呢

**Comment by CJY0208** [comment]
前段时间一个小伙伴有帮忙对 vite 做支持，可以看看 example 是否有帮助
https://github.com/zebing/react-node-key/blob/a263a75a23ce9bef414ba3e5b7cb792d11b28a14/examples/vite/vite.config.js

**Comment by rocketsbigfan** [comment]
> 能否提供项目 demo？近期有做 vite 的插件适配，是否有用上呢

https://github.com/rocketsbigfan/management-system  这是我的github，
我先测试下你提供的方法
谢谢

**Comment by rocketsbigfan** [comment]
> 前段时间一个小伙伴有帮忙对 vite 做支持，可以看看 example 是否有帮助
> https://github.com/zebing/react-node-key/blob/a263a75a23ce9bef414ba3e5b7cb792d11b28a14/examples/vite/vite.config.js

npm install之后，发现用不了，是不是还没有发布支持vite的版本

**Comment by minghu0902** [comment]
我也遇到了同样的问题，开发环境没有问题，打包之后运行就报错，去掉keepalive后再次打包运行，就正常了。
vite2.3.7
react17
react-router-dom5.2
react-activation0.9.4

**Comment by shuangbofu** [comment]
找了半天发现是这个组件的问题，请问您有解决吗

**Comment by rocketsbigfan** [comment]
> @shuangbofu 尝试将
> 
> ```js
> import KeepAlive  from 'react-activation'
> ```
> 
> 替换为
> 
> ```js
> import { KeepAlive } from 'react-activation'
> ```
就是如作者所说的来

jiushi
