### ISSUE TITLE
页签切换后url地址问号后的参数丢失？

### ISSUE THREAD

**Issue by GALA009** [CJY0208/react-activation#133]
当前存在的问题是，如果我的地址包含参数，如：/userInfo?id=1234，首次进入该页面地址时，地址为：/userInfo?id=1234，但当我切换页签后，再点击该页签，地址栏中地址为：/userInfo，如何才能保持页签地址包含有参数呢？

**Comment by CJY0208** [comment]
听起来可能是你设计的页签本身忘了包含 query 参数

**Comment by GALA009** [comment]
那需要怎么才能包含 query 呢？

当前我的写法如下
```javascript
<KeepAlive
    id={route.path}
    name={route.name}
    path={ route.path}
    saveScrollPosition="screen"
    when={true}
  >
    {children}
</KeepAlive>
````

**Comment by CJY0208** [comment]
参考以下，不仅仅使用 route.path 字段
https://github.com/CJY0208/react-activation#multiple-cache

![image](https://user-images.githubusercontent.com/18415774/126419660-cd700999-0348-46bd-8e5d-6450ba01e9af.png)

**Comment by GALA009** [comment]
我使用你说的这个方法，确实是能够将 query 存在nodes 中，但我在 /userInfo 页面，中如何获取到这个数据呢？
我想到的办法是通过 getCachingNodes 的值遍历匹配path，从而拿到 query 参数，这样做得弊端就是使用 query 的页面都需要修改并不是我想要的效果。

我想要是点击已缓存页签时，缓存的地址如果包含有 query 参数就自动带入地址中

**Comment by GALA009** [comment]
我知道了，是我自己糊涂了，再点击页签时，我应该把 query 拼接在 path 后面

**Comment by GALA009** [comment]
现在出现另外一个问题了，首次进入时存在 getCachingNodes 结果中 的query： { id: '1234' }， 当我换了一个 id: 5678 进入时， getCachingNodes 返回的结果中 query 还是旧的 { id: '1234' },  如何更新缓存的数据呢？
