### ISSUE TITLE
如何更新已缓存页签的数据？

### ISSUE THREAD

**Issue by GALA009** [CJY0208/react-activation#134]
您好，我想请教一个问题，当前我对页面进行多页签缓存，为了记录 query数据，所以缓存 query 数据，代码如下:

```javaScript
<KeepAlive
    id={route.path}
    name={route.name}
    path={ route.path}
    saveScrollPosition="screen"
    when={true}
    query={history.location.query}
  >
    {children}
</KeepAlive>
```

当我点击 A用户信息的查看按钮进入 /userInfo?id=1234 页面是时，query 中缓存的是 id: '1234', 当我选择B用户查看后，query 中缓存的数据并没有变更。请问一下如何才能进行变更为最新数据呢？

**Comment by CJY0208** [comment]
最新版本修复了一个历史问题，应该也修复了当前 issue，可以试试，当前问题暂时关了
