### ISSUE TITLE
页面有缓存，但页面状态没有恢复

### ISSUE THREAD

**Issue by MYSUMMERLORD** [CJY0208/react-activation#135]
hello，请教个问题，我按文档操作了一下，数据状态没有恢复，麻烦帮忙看下啦

我的操作如下：

在第一个页面输入筛选条件：
![image](https://user-images.githubusercontent.com/9947530/126929123-5e5c8951-41e2-4ffa-9a96-75a75f60142a.png)
切换到第二个页面，打印cache
![image](https://user-images.githubusercontent.com/9947530/126929188-c0a3ff31-4cd7-4eb6-b5ac-2c7d35733461.png)
回到第一个页面
![image](https://user-images.githubusercontent.com/9947530/126929213-8928bbb2-5815-4eed-ab6a-10c609c3e4bb.png)
![image](https://user-images.githubusercontent.com/9947530/126929225-8e2f460a-58e6-498e-9050-df4ffe8b2866.png)
数据状态没有恢复！

代码如下：
![image](https://user-images.githubusercontent.com/9947530/126929412-8124f9e0-8572-4707-a966-eae21cb52e8e.png)

**Comment by MYSUMMERLORD** [comment]
在第二页面查看第一个页面Keeper的状态，能看到缓存下来的，第一个页面select的value值，
![image](https://user-images.githubusercontent.com/9947530/126930724-19c15ebd-9297-4e83-a87e-103f4f2afa85.png)
返回第一个页面，查看该页面Keeper的状态，select的value值变为undefined　
![image](https://user-images.githubusercontent.com/9947530/126930847-4c6a8c8b-7f29-489b-a400-42c6fbed0340.png)

**Comment by CJY0208** [comment]
截图中我没看到 keep-alive，目前代码是怎么写的？

**Comment by MYSUMMERLORD** [comment]
![image](https://user-images.githubusercontent.com/9947530/127795596-9cda5922-0f9b-4546-892e-ffe8961cb3fa.png)
![image](https://user-images.githubusercontent.com/9947530/127795622-89c05273-95fb-4a6f-85e1-e916bc907175.png)

**Comment by LittleFairyY** [comment]
最后怎么解决的啊

**Comment by CJY0208** [comment]
需要检查待缓存的值是否存在了 redux 之类的公共数据区域

**Comment by LittleFairyY** [comment]
我也是和他一样页面a的状态在切换到页面b的时候状态这些都有 但是切回页面a就没有了 我的状态是react hooks 的usestate

**Comment by hellowuxin** [comment]
> 需要检查待缓存的值是否存在了 redux 之类的公共数据区域

存在redux的值就不能恢复了，是这个意思吗？有办法解决吗

**Comment by CJY0208** [comment]
最新版本修复了一个历史性问题，大概率也修复了此问题，暂时关闭
