### ISSUE TITLE
您好，请问refresh之后，为何会再次执行useActivate？

### ISSUE THREAD

**Issue by Gianna-w** [CJY0208/react-activation#137]
在useActivate之中执行refresh('name')，会循环执行useActivate，这是为什么呢？

**Comment by captain-c** [comment]
我也碰到了，请问是啥原因呢？虽然能用clear()解决，但还是希望知道原因

**Comment by CJY0208** [comment]
拿 demo 看了一下没有遇到这个情况，是不是开启了 react 严格模式？这个需要关闭
