### ISSUE TITLE
页面绑定window的scroll事件，进入页面几次就会触发多少次scroll事件

### ISSUE THREAD

**Issue by liyanging** [CJY0208/react-activation#139]

**Comment by liyanging** [comment]
因为页面一直缓存在内存里面的，也没有触发组件的卸载，如果 页面绑定了全局事件，就会一直累加起来。请问这种情况如何处理比较好？是否可以提供actived和unActived的生命周期

**Comment by CJY0208** [comment]
提供了生命周期，文档此处：https://github.com/CJY0208/react-activation#lifecycle
