### ISSUE TITLE
图表类echarts不更新

### ISSUE THREAD

**Issue by tianyazjq** [CJY0208/react-activation#142]
图表类echarts不更新，启用keep-alive以后，echarts图表类不渲染。

**Comment by CJY0208** [comment]
能提供可复现的 demo 吗？

**Comment by Cheerwhy** [comment]
可以尝试在activated生命周期中resize()图表

**Comment by tianyazjq** [comment]
可以了，谢谢大大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月23日(周四) 晚上8:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CJY0208/react-activation] 图表类echarts不更新 (#142)




 
可以尝试在activated生命周期中resize()图表
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
