### ISSUE TITLE
Problem with Portal

### ISSUE THREAD

**Issue by prochorz** [CJY0208/react-activation#144]
It has a problem when we use the portal inside the component. After the toggle boolean state, the component doesn't disappear. 

https://codesandbox.io/s/zui-jian-react-keepalive-shi-xian-forked-ug51u?file=/src/index.js

Try click on toggle

**Comment by CJY0208** [comment]
portal would not be hidden because component is not unmount, with react-activation you may need to use activation lifecycle to hide portal manully

**Comment by prochorz** [comment]
> portal would not be hidden because component is not unmount, with react-activation you may need to use activation lifecycle to hide portal manully

How can I do this? css? But I don't need html in DOM.

**Comment by CJY0208** [comment]
hide portal manully like this
https://codesandbox.io/s/zui-jian-react-keepalive-shi-xian-forked-15h5d?file=/src/index.js

![image](https://user-images.githubusercontent.com/18415774/149649929-e3bd9c9d-9c8b-4165-b12f-4b2847545913.png)

**Comment by prochorz** [comment]
But this does not remove the element from DOM

**Comment by CJY0208** [comment]
Just for example, `KeepAlive` cannot handle nodes that are not under its root node, you shall find the way out of you situation by active lifecycle, such as directly removing DOM nodes

**Comment by prochorz** [comment]
I do it like this [https://codesandbox.io/s/zui-jian-react-keepalive-shi-xian-forked-vg6nv?file=/src/index.js](https://codesandbox.io/s/zui-jian-react-keepalive-shi-xian-forked-vg6nv?file=/src/index.js) What you think?

**Comment by CJY0208** [comment]
sure, if it is work in your code

**Comment by CJY0208** [comment]
can't fixed, closed
