### ISSUE TITLE
umi@3.5.0 使用路由管理配置access属性 不能实现鉴权的效果

### ISSUE THREAD

**Issue by zxgreatT** [CJY0208/react-activation#146]
在config里面routes设置access属性不能达到预期效果

**Comment by AndroidMilk** [comment]
access失效了

**Comment by CJY0208** [comment]
umi 需要搭配 umi-plugin-keep-alive 使用，直接使用 react-activation 会有问题

导向此处 https://github.com/alitajs/umi-plugin-keep-alive/issues/42
