### ISSUE TITLE
结合TinyMCE 用会存在无法多个缓存的情况

### ISSUE THREAD

**Issue by zivenday** [CJY0208/react-activation#147]

**Comment by CJY0208** [comment]
有配合 id 属性使用吗，具体是如何使用的？同一个 KeepAlive 内要区分多份缓存需要使用到 id 属性

**Comment by zivenday** [comment]
> 有配合 id 属性使用吗，具体是如何使用的？同一个 KeepAlive 内要区分多份缓存需要使用到 id 属性

`
const app =function()={
return <keepalive name={id} id={id}>
<A/>
</keepalive>
}

const A= class React.component{
<Tinymce  config={...config}/>
}
`
大概这样
但是不行

**Comment by zivenday** [comment]
> 有配合 id 属性使用吗，具体是如何使用的？同一个 KeepAlive 内要区分多份缓存需要使用到 id 属性

我参照timcy-react官方提供的范例，正常，目前发现相关问题可以解决，再测试测试看看。谢谢大佬。
