### ISSUE TITLE
使用KeepAlive 包裹组件，会多增加两层div。希望添加className对其操作样式。

### ISSUE THREAD

**Issue by biology-w** [CJY0208/react-activation#15]
公司手机项目，需要保存页面。
一些页面列表使用react-virtaulized。需要一些特殊的样式包裹。
但是使用KeepAlive 包裹组件，会多增加两层div。导致样式断层，列表不显示。

希望作者能暴露出多增加Dom节点的className，添加样式。

**Comment by biology-w** [comment]
KeepAlive 导致父子之间样式断层。
我现在解决办法是： 父元素样式一层一层添加到KeepAlive Dom上：
作者有什么好的意见嘛？？？

 <div className={styles.keepAlive}>
          <KeepAlive>
            <Component history={props.history} />
          </KeepAlive>
        </div>

//  styles.scss 文件
.keepAlive {
    flex: 1;
    display: flex;
    flex-direction: column;

    >div {
        flex: 1;
        display: flex;
        flex-direction: column;

        >div {
            flex: 1;
            display: flex;
            flex-direction: column;
        }
    }
}

**Comment by CJY0208** [comment]
抱歉，这是个疏漏，我今晚发版本加上对这两层节点的选择器途径

将使用类名 `.ka-wrapper` 与 `.ka-content` 选取，结构为

```html
<div className="ka-wrapper">
  <div className="ka-content">
    ...
  </div>
</div>
```
