### ISSUE TITLE
使用 react-activation/babel,  ag-grid ，在控制台中显示警告信息

### ISSUE THREAD

**Issue by 763139102** [CJY0208/react-activation#150]
![image](https://user-images.githubusercontent.com/25519902/143522072-c1cdfba8-b5dc-40bc-9a61-15522bf46104.png)
这个问题该 如何处理 ，可以单独 屏蔽 ag-grid 吗？

**Comment by CJY0208** [comment]
看起来是三方库报的错误，activation 似乎无法处理，得看三方库本身能否关闭这个警告了
