### ISSUE TITLE
react-freeze不支持react16，会导致兼容性问题

### ISSUE THREAD

**Issue by mir0ne** [CJY0208/react-activation#153]

**Comment by CJY0208** [comment]
是什么兼容性问题？测了一下 16.8.0 是 OK 的，是不是安装时提示了 peerDeps 相关的错误？

**Comment by mir0ne** [comment]
@CJY0208 使用npm7安装时构建依赖树报错

**Comment by CJY0208** [comment]
嗯嗯，我看看有没有可能内置自己的 react-freeze

**Comment by mir0ne** [comment]
OK，那我就关闭了

**Comment by CJY0208** [comment]
0.9.6 版本内置了 react-freeze，暂时解决了问题

**Comment by CJY0208** [comment]
版本 16.6.3 以上时 react-freeze 工作良好
