### ISSUE TITLE
请问使用KeepAlive包裹的页面缓存后，页面切换动画失效？

### ISSUE THREAD

**Issue by AndroidMilk** [CJY0208/react-activation#154]
RT,如果动画要重新过渡，组件需要重新卸载再挂载，这样子缓存就会失效了，请问有什么好的解决办法吗？

**Comment by CJY0208** [comment]
react-activation 是可以配合 react-transition-group 来做动画的，可以参考这个 demo
https://codesandbox.io/s/luyouzhuanchangdonghuashili-jdhq1

**Comment by AndroidMilk** [comment]
👌

**Comment by AndroidMilk** [comment]
如果是多标签页的切换，多标签页的原理是根据cachingNodes遍历节点生成的，现在我的keepAlive包裹的是<Outlet>,缓存ok，react-router-dom:6.0.2版本，react-route也是v6版本，如果用react-transition-group 我应该把keepAlive放在哪个地方合适

**Comment by AndroidMilk** [comment]
keepAlive包裹的是<Outlet/>

**Comment by AndroidMilk** [comment]
`<Outlet/>`

**Comment by CJY0208** [comment]
我没用过 router v6，大概提供个思路

```jsx
const location = useLocation()
const outlet = useOutlet()

<KeepAlive id={location.key}>
  {outlet}
<KeepAlive>
```

**Comment by AndroidMilk** [comment]
我现在的情况就是下面这样
![image](https://user-images.githubusercontent.com/13392610/145942071-74752c8e-53bb-4c9e-ab33-f2406707de50.png)

**Comment by AndroidMilk** [comment]
如果id是用location.key，动画效果肯定会一直有，但是会造成相同路由
的标签不断的增多，而且缓存是不是也会失效

**Comment by AndroidMilk** [comment]
已解决，我写多余了

**Comment by yanjiaxuan** [comment]
@AndroidMilk 咋解决的，分享下，我也遇到坑了😂
