### ISSUE TITLE
用vite打包后，访问KeepAlive包裹的组件出错

### ISSUE THREAD

**Issue by AndroidMilk** [CJY0208/react-activation#156]
RT,开发环境没问题，但是生产环境打包访问出错

**Comment by AndroidMilk** [comment]
react_devtools_backend.js:4045 
        
       Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by AndroidMilk** [comment]
![image](https://user-images.githubusercontent.com/13392610/147342370-4164c0aa-9047-4336-90c6-82a9fb64bcea.png)

**Comment by CJY0208** [comment]
vite 下不要使用 default 导出，换用以下试试

```jsx
import { KeepAlive } from 'react-activation'
```

**Comment by AndroidMilk** [comment]
> vite 下不要使用 default 导出，换用以下试试
> 
> ```jsx
> import { KeepAlive } from 'react-activation'
> ```

真的解决了，为什么了
