### ISSUE TITLE
切换中英文国际化不生效

### ISSUE THREAD

**Issue by AndroidMilk** [CJY0208/react-activation#157]
RT，是不是缓存导致context失效了

**Comment by AndroidMilk** [comment]
刷新浏览器以后，切换又生效了，是不是挂载组件的问题

**Comment by CJY0208** [comment]
有可能，是react 17吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月24日(周五) 晚上9:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] 切换中英文国际化不生效 (Issue #157)




 
RT，是不是缓存导致context失效了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AndroidMilk** [comment]
> 

是的，有什么好的解决办法吗？

**Comment by CJY0208** [comment]
加下边这段试试

```jsx
import { autoFixContext } from 'react-activation'

autoFixContext(
  [require('react/jsx-runtime'), 'jsx', 'jsxs', 'jsxDEV'],
  [require('react/jsx-dev-runtime'), 'jsx', 'jsxs', 'jsxDEV']
)
```

**Comment by AndroidMilk** [comment]
不生效，只能切换刷新了

**Comment by CJY0208** [comment]
也可以试试手动 fix 你的国际化上下文

```jsx
import { fixContext } from 'react-activation'

fixContext(I18nContext)
```

**Comment by AndroidMilk** [comment]
我试试发自我的手机-------- 原始邮件 --------发件人： CJY ***@***.***>日期： 2021年12月28日周二 09:33收件人： CJY0208/react-activation ***@***.***>抄送： Poppy ***@***.***>, Author ***@***.***>主    题： Re: [CJY0208/react-activation] 切换中英文国际化不生效 (Issue #157)

也可以试试手动 fix 你的国际化上下文

import { fixContext } from 'react-activation'



fixContext(I18nContext)

**Comment by CJY0208** [comment]
无响应，暂时关闭
