### ISSUE TITLE
keepAlive会增加外部容器，从而阻止findDOMNode 获取元素的相关操作

### ISSUE THREAD

**Issue by inier** [CJY0208/react-activation#158]
useEffect(() => {
    // eslint-disable-next-line react/no-find-dom-node
    const dom = findDOMNode(containerRef.current) as HTMLDivElement;
    const rect = (dom && dom.getBoundingClientRect()) || {};
    setLeft(rect.left);
    setRight(document.documentElement.offsetWidth - rect.left - rect.width);
  }, []);

**Comment by CJY0208** [comment]
增加外部容器是用作定位，必要之举，如果不想过得容器，可以不要将 ref 绑定在 KeepAlive 上



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月27日(周一) 晚上11:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] keepAlive会增加外部容器，从而阻止findDOMNode 获取元素的相关操作 (Issue #158)




 
useEffect(() =&gt; {
 // eslint-disable-next-line react/no-find-dom-node
 const dom = findDOMNode(containerRef.current) as HTMLDivElement;
 const rect = (dom &amp;&amp; dom.getBoundingClientRect()) || {};
 setLeft(rect.left);
 setRight(document.documentElement.offsetWidth - rect.left - rect.width);
 }, []);
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CJY0208** [comment]
先关闭了，如果有切实问题，可以开个 demo 讨论

**Comment by cool-518** [comment]
遇到同样的问题。增加了外部容器后，导致样式不太对

**Comment by CJY0208** [comment]
可以通过 .ka-wrapper 和 .ka-content 两个 className 来调整样式
