### ISSUE TITLE
引入了KeepAlive，但是组件上的使用的hooks的useState 全部失效的原因是什么？

### ISSUE THREAD

**Issue by lxz0510** [CJY0208/react-activation#159]
![image](https://user-images.githubusercontent.com/57799539/147547901-2009314d-c33b-4468-a988-0f298868838f.png)
**我使用keepalive包裹到整个页面的jsx，然后我使得我页面上的useState全部失效了。路由切换状态保存是正常使用的。请问我描述的清晰吗，还需要提供什么其他的信息
![image](https://user-images.githubusercontent.com/57799539/147547992-c66b241a-65b4-4fbf-beeb-3b97fe5dc9ad.png)

**Comment by CJY0208** [comment]
具体是怎样的情况？有复现例子吗

**Comment by rumunanfeng** [comment]
我也遇到了此问题，就是函数式组件内使用react-activation的keep-alive包裹，使用useState初始化数据。在useEffect内改变数据，数据成功改变，但是页面不显示改变后的数据。
把keep-alive组件包裹去掉就可以正常显示。

简单示例代码如下：
import KeepAlive from 'react-activation';
import { useEffect, useState } from 'react';
import { Select } from 'antd';
const List = () => {
  const [options, setOptions] = useState([])
  useEffect(() => {
    setOptions([{label: '1', value: '1'}])
  }, [])
  return (
    <KeepAlive>
      <Select options={options}>
        </Select>
    </KeepAlive>
}

**Comment by CJY0208** [comment]
```jsx
function Comp() {
  const [value, ...] = useState(...)
  return (
    <KeepAlive>
        ... {value}
    </KeepAlive>
  )
}

export default Comp
```

换成以下试试

function Comp() {
  const [value, ...] = useState(...)
  return (
    <>
        ... {value}
    </>
  )
}

export default (props) => (
    <KeepAlive>
        <Comp {...props} />
    </KeepAlive>
)

**Comment by rumunanfeng** [comment]
> ```js
> function Comp() {
>   const [value, ...] = useState(...)
>   return (
>     <KeepAlive>
>         ... {value}
>     </KeepAlive>
>   )
> }
> 
> export default Comp
> ```
> 
> 换成以下试试
> 
> ```js
> function Comp() {
>   const [value, ...] = useState(...)
>   return (
>     <>
>         ... {value}
>     </>
>   )
> }
> 
> export default (props) => (
>     <KeepAlive>
>         <Comp {...props} />
>     </KeepAlive>
> )
> ```

这样写可以，感谢😁

**Comment by CJY0208** [comment]
嗯嗯，这条 issue 大概率也是相同的问题，KeepAlive 得包裹住整个需要缓存的组件

暂时认为是使用问题，先关了，确实有问题再打开
