### ISSUE TITLE
A页面缓存后，跳到B页面，在B页面情况缓存后，跳回A页面，A页面的按钮点击不了是怎么回事？

### ISSUE THREAD

**Issue by oubohua** [CJY0208/react-activation#166]

**Comment by CJY0208** [comment]
可以提供复现 demo 吗?

**Comment by Mr-jili** [comment]
clear()的问题 判断下啥情况执行clear()

**Comment by jerrywu001** [comment]
> 可以提供复现 demo 吗?

同样的问题，我是在react-router V6中发现的，例子如下：

https://stackblitz.com/edit/react-ts-2audg2?file=index.tsx

**Comment by CJY0208** [comment]
最新版本修复了一个历史性问题，可以看看是否可解决当前的问题，暂时关闭了
