### ISSUE TITLE
请问在vite里面能使用吗

### ISSUE THREAD

**Issue by SuperMrBean** [CJY0208/react-activation#168]
想在vite里面使用，请问需要怎么配置呢

**Comment by CJY0208** [comment]
### 1. 添加 vite babel 插件（可选项、建议）

```js
import { defineConfig } from 'vite'
import reactNodeKey from 'react-node-key/vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    reactNodeKey()
  ]
})
```

### 2. 业务代码中用 es moudle 引入相关组件

```jsx
import { AliveScope, KeepAlive } from 'react-activation'
```

**Comment by jiachenyu1** [comment]
> ### 1. 添加 vite babel 插件（可选项、建议）
> ```js
> import { defineConfig } from 'vite'
> import reactNodeKey from 'react-node-key/vite';
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [
>     reactNodeKey()
>   ]
> })
> ```
> 
> ### 2. 业务代码中用 es moudle 引入相关组件
> ```js
> import { AliveScope, KeepAlive } from 'react-activation'
> ```

这个包是不是最新的没有发布  我安装完看没有 vite 目录

**Comment by CJY0208** [comment]
试试 v0.3.2，补发了一个，之前确实漏掉了 vite 目录

**Comment by CJY0208** [comment]
除了配置 vite plugins，还可以选择手动标记 KeepAlive 的 cacheKey 属性，参考[此处](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#1-%E5%8F%AF%E9%80%89%E5%BB%BA%E8%AE%AEbabel-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-babelrc-%E4%B8%AD%E5%A2%9E%E5%8A%A0-react-activationbabel-%E6%8F%92%E4%BB%B6)
