### ISSUE TITLE
The cache works under react 18, but there is an error warning

### ISSUE THREAD

**Issue by gwsbhqt** [CJY0208/react-activation#169]
I'm following the official Offscreen API, but the official API will be available in the 18.x version a long time later, and I'm still using the react-activation library.

The cache is currently all valid, but react 18 changed the rendering API, so it caused the warning error.

![image](https://user-images.githubusercontent.com/16471930/155849030-aa537171-e1a8-415a-8a9c-d86beccfc7d2.png)

![image](https://user-images.githubusercontent.com/16471930/155849055-ec3e9e99-eada-4a05-bb4f-7ceb0bd0ea13.png)

```json
{
  "react": "^18.0.0-rc.0",
  "react-activation": "^0.9.9",
  "react-dom": "^18.0.0-rc.0"
}
```

**Comment by CJY0208** [comment]
Should be fixed with v0.9.10, thanks!
