### ISSUE TITLE
Keeping state for different routes that mount the same component

### ISSUE THREAD

**Issue by n1rna** [CJY0208/react-activation#17]
I have been trying to use `KeepAlive`'s approach to keep state of different components and prevent them from getting unmounted. The only problem is when I have something like below, I am not getting the expected behavior.

```
<KeepAlive>
  <Product {...this.props} />
</KeepAlive>
```

And inside `Product` component, I have a link to another product. When I navigate between 2 different products and I hit `back` button, the previously visited product route will lose it's state.

Is there something that I am missing here?

**Comment by CJY0208** [comment]
Is it similar to the scenario here in the documentation?

[Multiple Cache](https://github.com/CJY0208/react-activation#multiple-cache)

**Comment by n1rna** [comment]
Thanks for your response.

We are using nextjs for SSR handling and therefore we can not use `<HashRouter>` for this purpose. Is there a workaround for using HashRouter in our app? Or is Manual Caching going the only way to go?

**Comment by CJY0208** [comment]
Not only work with `Router`, I mean, seems that you want to create multiple `<Product>` cache in the same `<KeepAlive>` 

Is there any parameter difference between the different components? 

The difference in parameters can be expressed in `id` prop to make multiple caches

**Comment by n1rna** [comment]
I am doing the exact same thing you are mentioning. I am setting `id` prop for the `<KeepAlive>` component based on the unique identifier of each `<Product>`.

I am not creating several `<Product>`s inside one `<KeepAlive>`

This is the demonstration of what I am doing in my app.

```
render() {
    const { Component, pageProps } = this.props
    return (
      <AliveScope>
        <Component {...pageProps}  />
      </AliveScope>
    )
}
```
```
<KeepAlive id={random_key} name={`Item${random_key}`}>
    <Product {...this.props} />
</KeepAlive>
```

**Comment by khanbaba** [comment]
I have the same issue.

**Comment by CJY0208** [comment]
@n1rna Is there a solution to your problem? 

@khanbaba I'm not sure if I understand your scene

**Comment by n1rna** [comment]
I am trying to read through this repository's source code and if I found a solution I will let you know

**Comment by CJY0208** [comment]
It would not be an easy way... means that my understand is worng.

Can offer a simplest online demo?

**Comment by n1rna** [comment]
I see a possible big problem with caching when I print `cachingNodes` in each step of my navigation.
Different nodes are getting cached correctly but their `_ka` property seems to be the same!

I have navigated through these routes:
```
1. /browse/?q=something
2. (Click on some product) /p/rk1
3. (Click on a recommended product in rk1's page) /p/rk2
```

and this is my `cachingNodes` value at the latest stage:

```
[{…}, {…}, {…}]
0:
bridgeProps: {sus$$: {…}, ctx$$: Array(0), error$$: ƒ}
children: (2) [{…}, {…}]
createTime: 1575726324832
getInstance: ƒ getInstance()
id: "a"
name: "Comps"
saveScrollPosition: true
updateTime: 1575726324832
_ka: "m5GI21"
__proto__: Object
1:
bridgeProps: {sus$$: {…}, ctx$$: Array(0), error$$: ƒ}
children: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …}
createTime: 1575726367100
getInstance: ƒ getInstance()
id: "e4749c93-42d9-46b2-8b4a-526d5b30547el"
name: "Iteme4749c93-42d9-46b2-8b4a-526d5b30547e"
saveScrollPosition: true
updateTime: 1575726392106
_ka: "m5GI21"
__proto__: Object
2:
bridgeProps: {sus$$: {…}, ctx$$: Array(0), error$$: ƒ}
children: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …}
createTime: 1575726392068
getInstance: ƒ getInstance()
id: "f6f15abe-fac0-4630-bbe4-e43db5383aefl"
name: "Itemf6f15abe-fac0-4630-bbe4-e43db5383aef"
saveScrollPosition: true
updateTime: 1575726392068
_ka: "m5GI21"
__proto__: Object
length: 3
__proto__: Array(0)
```

**Comment by n1rna** [comment]
On the third page (`/p/rk2`) when I hit back button, some weird infinite loop runs and everything gets stuck and browser hangs!

**Comment by CJY0208** [comment]
Can offer a online demo? Seems a question

**Comment by n1rna** [comment]
Hey,

We have solved the problem which was caused by our `componentDidUpdate` lifecycle function. There was a `setState` call inside our `componentDidUpdate` and it was causing an infinite loop while rendering.

So thanks for your responses and your great job on this repository :)
