### ISSUE TITLE
drop当前组件引起React Warning

### ISSUE THREAD

**Issue by JqhSdtz** [CJY0208/react-activation#170]
直接用umi-keep-alive-tabs-demo中的代码
```javascript
function dropTab(e) {
    e.stopPropagation()
    const currentName = node.name

    if (location.pathname === node.name) {
      dropScope(currentName)
      // 前往排除当前 node 后的最后一个 tab
      history.push(
        cachingNodes.filter((node) => node.name !== currentName).pop().name
      )
    } else {
      dropScope(currentName)
    }
  }
```
在history.push之后大概1s控制台会输出错误
猜测可能是Keeper组件在unmount之后没有clearTimeout导致React提示可能造成内存泄露
react版本17.0.2，react-activation版本0.9.9
在此表示感谢！
报错截图：
![截图_20220227221222](https://user-images.githubusercontent.com/43899406/155886401-4980bd38-b23a-42e0-91e1-f0e3f940b660.png)
出错部分的代码：
![截图_20220227221542](https://user-images.githubusercontent.com/43899406/155886429-a01a1285-3cde-4d2d-9758-b08708a63633.png)

**Comment by CJY0208** [comment]
OK，v0.9.11 中修复了~
