### ISSUE TITLE
[bug] webpack 5 中 react 页面中的 context 丢失

### ISSUE THREAD

**Issue by wangzongming** [CJY0208/react-activation#173]
当我使用 webpack4 时是没问题的，AliveScope 里面的页面中的 context 可以正常设置和获取。
但是升级到 webpack5 后在下面的情况下将出现问题：

![image](https://user-images.githubusercontent.com/27466569/156511301-63358cdd-a928-4eb4-a1a8-7c33a40e39ab.png)

在 webpack5 中 TestChild 中将获取不到 context, webpack4 中测试正常

webpack4 输出如下
![image](https://user-images.githubusercontent.com/27466569/156511767-35b966b8-0944-4dc6-adaa-7da0e91fcc53.png)

webpack5 输出如下
![image](https://user-images.githubusercontent.com/27466569/156511850-20268a1a-0bf0-46d0-8c98-8ef158d00099.png)

**版本**
react-activation@0.9.11
react@17.0.2

非常感谢花费时间来帮我看这个问题🌹🌹🌹

**Comment by wangzongming** [comment]
包裹了 KeepAlive 的 TestChild  是最后输入的那个。

**Comment by CJY0208** [comment]
webpack 4 时的 react 版本是多少？应该主要和 react 版本有关，可能你升级了 webpack 时顺便把 react 也升了

尝试参考以下来做修正

```jsx
import { autoFixContext } from 'react-activation'

autoFixContext(
 [require('react/jsx-runtime'), 'jsx', 'jsxs', 'jsxDEV'],
 [require('react/jsx-dev-runtime'), 'jsx', 'jsxs', 'jsxDEV']
)
```

**Comment by wangzongming** [comment]
> webpack 4 时的 react 版本是多少？应该主要和 react 版本有关，可能你升级了 webpack 时顺便把 react 也升了
> 
> 尝试参考以下来做修正
> 
> ```js
> import { autoFixContext } from 'react-activation'
> 
> autoFixContext(
>  [require('react/jsx-runtime'), 'jsx', 'jsxs', 'jsxDEV'],
>  [require('react/jsx-dev-runtime'), 'jsx', 'jsxs', 'jsxDEV']
> )
> ```
依赖的 react 版本都是 17.0.2，只是webpack版本不同。


autoFixContext 是放到项目入口文件吗？还是放到 babel 插件里面去？

**Comment by CJY0208** [comment]
放在项目入口文件中

**Comment by wangzongming** [comment]
> 放在项目入口文件中

好用了。万分感谢好大哥。🤞🤞🤞
