### ISSUE TITLE
配合redux使用的时候组件传值会有问题，无法更新内容

### ISSUE THREAD

**Issue by zoro-r** [CJY0208/react-activation#175]
你好，方便看一下这个问题吗？下面是复线地址
https://codesandbox.io/s/xenodochial-water-1d4czv?file=/src/App.js

**Comment by lebron112** [comment]
这个不是redux 的问题；
  我也遇到了相同的问题，就是Keepalive 包裹之后的组件，无法进行状态或者props的更新；
 被包裹之后状态就没有更新
` const [a,v] = useState(1);
 return (<div onClick={()=>v(a+1)}><p> 点我{a}</p><keepalive><p>{a}</p><keepalive/><div/>)
`

**Comment by shenjunru** [comment]
欢迎试用 [react-fiber-keep-alive](https://www.npmjs.com/package/react-fiber-keep-alive)，一个基于 react fiber 的 keep-alive 实现

**Comment by CJY0208** [comment]
历史性的隐藏 bug，已经修复了，直接升最新版就 OK
