### ISSUE TITLE
ts 报错

### ISSUE THREAD

**Issue by jiachenyu1** [CJY0208/react-activation#177]
![WX20220321-131223](https://user-images.githubusercontent.com/30521653/159208507-1bd78d67-8ce3-439a-bce1-a7d5d331a3f8.png)
![WX20220321-131304](https://user-images.githubusercontent.com/30521653/159208517-4d358d68-5392-470b-ba74-cc1f796e60f3.png)

这块 ts 有点问题，configs 是个数组只有一个参数，示例代码是两个参数

**Comment by CJY0208** [comment]
mark

**Comment by CJY0208** [comment]
发了 0.9.12，应该修复了
