### ISSUE TITLE
KeepAlive 放到 layout 中不生效

### ISSUE THREAD

**Issue by jiachenyu1** [CJY0208/react-activation#178]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/30521653/159225271-56eed6e8-1f3b-4cd3-a233-c8f23a397f58.png">
<img width="559" alt="image" src="https://user-images.githubusercontent.com/30521653/159225367-e7f6f35e-1e3a-41cd-91d0-76dd6f3f1098.png">
放到layout中不生效  放到路由层生效 但是路由层每个都要套一下

**Comment by CJY0208** [comment]
id={location.key} 给的不对，需要按各个路由的区别值来给

**Comment by jiachenyu1** [comment]
> id={location.key} 给的不对，需要按各个路由的区别值来给

<img width="241" alt="image" src="https://user-images.githubusercontent.com/30521653/159397732-479aa8de-4254-4e92-9b94-0fa31d05be01.png">
我试过用 tab.key 也不行

**Comment by CJY0208** [comment]
可以搞个复现示例嘛？按理来说是可以的

**Comment by jiachenyu1** [comment]
我一会来一个

**Comment by jiachenyu1** [comment]
> 可以搞个复现示例嘛？按理来说是可以的

https://codesandbox.io/embed/elegant-dew-h0jw0q?fontsize=14&hidenavigation=1&theme=dark

帮忙看下

**Comment by CJY0208** [comment]
看了一下，例子里的不是 react-activation 的问题，是 Outlet 内部本身发生了变化，activation 是无法阻断的

**Comment by 936446507** [comment]
> 看了一下，里面的例子不是 react-activation 的问题，是 Outlet 内部内部的变化，activation 是无法触发的

你好，我想问下这个问题的话，需要怎么修改

**Comment by gamecss** [comment]
> 

[there](https://github.com/CJY0208/react-activation/issues/196#issuecomment-1140195454)
