### ISSUE TITLE
React18 complains about incorrect import for `createRoot`

### ISSUE THREAD

**Issue by isc30** [CJY0208/react-activation#179]
https://github.com/CJY0208/react-activation/blob/6efdd6155709c4d5287dd426ac83a92b362a6a1c/src/core/AliveScope.js#L203

![image](https://user-images.githubusercontent.com/10807051/159980466-914d4b94-2f59-48a1-a179-595fcab52113.png)

It should be something like this:

`if (ReactDOM.createRoot) {
  import('react-dom/client').createRoot(...)
}`

**Comment by CJY0208** [comment]
we can't import react-dom dynamically in library package, seems would cause break change, may need to release a new version which just support React 18

**Comment by CJY0208** [comment]
remove this feature in 0.10.0
