### ISSUE TITLE
keepalive 无法卸载缓存

### ISSUE THREAD

**Issue by CrownMmm** [CJY0208/react-activation#181]
您好，一开始的时候keepalive 无法添加缓存 ，之前按照其他的issue的解决方案，使用 export default () => (<keepalive><Comp></keepalive>)  后 ，可以缓存但是无法清除缓存了 手动drop后还会存在缓存，刷新页面并不会重新加载 
目前react版本 16.10 mobx 5.x 
最后能添加下您的微信请教下吗

**Comment by CrownMmm** [comment]
![WechatIMG66](https://user-images.githubusercontent.com/54773058/160583066-067d8133-164e-4d32-b649-0868c0d06400.jpeg)

目前是这么写的，这么写之后会可以缓存，但是drop（name）之后 无法清除缓存

**Comment by CrownMmm** [comment]
emmmmm 刚才我又看了一下，使用getCatchingNodes发现 里面的缓存已经删除了，可渲染后的页面还是带有缓存

**Comment by CJY0208** [comment]
是否可能需要使用的是 refresh 而不是 drop ?

**Comment by CrownMmm** [comment]
> 

尝试过 refresh 关闭页签再次打开还是带有缓存

**Comment by CJY0208** [comment]
能否搞一个可重现的 demo 呀

**Comment by CrownMmm** [comment]
已使用作者的另一个库解决页签问题

**Comment by sakitam-fdd** [comment]
@CrownMmm 是否这里出问题不是因为页面缓存，而是 mobx store的数据依然存在？
