### ISSUE TITLE
打包的时候报index.d.ts 文件中 autoFixContext 类型定义错误

### ISSUE THREAD

**Issue by luopenghu** [CJY0208/react-activation#183]
报错内容如下：
node_modules/react-activation/index.d.ts:32:32 - error TS2370: A rest parameter must be of an array type.
32 export function autoFixContext(...configs?: ContextFixEntry[]): void

node_modules/react-activation/index.d.ts:32:42 - error TS1047: A rest parameter cannot be optional.
32 export function autoFixContext(...configs?: ContextFixEntry[]): void

**Comment by luopenghu** [comment]
可以了，谢谢

**Comment by luopenghu** [comment]
没有更新到npm，麻烦更新一下

**Comment by CJY0208** [comment]
离谱，漏了

**Comment by CJY0208** [comment]
发上去了
