### ISSUE TITLE
设置id后，getCachingNodes的数据中id拼接了别的字符串

### ISSUE THREAD

**Issue by GuanJdoJ** [CJY0208/react-activation#184]
按照官网示例，打印结果如图

code:https://codesandbox.io/s/umi-keep-alive-tabs-demo-forked-l8n26e?file=/src/components/KeepAliveTabs/index.js

<img width="1449" alt="react-re" src="https://user-images.githubusercontent.com/30386473/163561152-b23257fe-4d76-4f37-a233-533fdf5c5ddb.png">

**Comment by CJY0208** [comment]
是的，这个 id 内部和 node-key 做了结合，你是需要用它来做什么吗？

**Comment by GuanJdoJ** [comment]
做/chart-detail/:id的多份缓存，根据获取的id和name关联同一个页面的不同路由，展示多份tab；比如在我的需求中，tab展示两部分，用图标区分chart-detail/node-detail/xxx-detail，后面文本显示id。如果id和内部node-key做了结合，那我就在页面设置id = props.match.params.id + $，后面获取到时再spilt，所以内部node-key会不会包含$或其他特殊字符呢

顺便问一下，有这种用法吗<KeepAlive someParams={query: ...} />, 然后再从cachingNode中获取其他参数，比如query的值

**Comment by GuanJdoJ** [comment]
需要query是因为要在一级tab的页面中做二级tab，可以在query中存放一级tab信息，能通过url直接跳到相应页面

**Comment by GuanJdoJ** [comment]
需要query是因为要在一级tab的页面中做二级tab，可以在query中存放一级tab信息，能通过url直接跳到相应页面

**Comment by GuanJdoJ** [comment]
之前的思路有问题，其实这个应该包含2部分：1路由和tab展示（业务），2缓存（非业务），它们应该是独立的两个部分；
输入路由改变tab，点击tab切换路由，在这个过程中借助Keep-alive为我们保存缓存；
tab和路由应当独立保存，而不是从cachingNode中获取；
