### ISSUE TITLE
react router v6，页面缓存没有生效

### ISSUE THREAD

**Issue by jerrywu001** [CJY0208/react-activation#186]
@CJY0208

我写了3个页面

page 1 
page 2
page 3

其中page 3没有缓存

问题描述：
页面之间互相跳转，page 1 , page 2缓存没有生效

例子如下：https://stackblitz.com/edit/react-ts-xvzg1x?file=index.tsx

**Comment by CJY0208** [comment]
<CSSTransition /> 的 key 属性不要使用 location.key，这个值完全随机，会让 KeepAlive 认为自己处于新的 vdom 树中，被看做是新的状态

另外，Routes 和 CSSTransition 之间需要裹一层 div 缓冲，不然动画直接操作到 Routes 节点会产生奇怪的问题
https://stackblitz.com/edit/react-ts-9ctqw1
