### ISSUE TITLE
react router V6版本，两个缓存页面之间无法互相跳转

### ISSUE THREAD

**Issue by jerrywu001** [CJY0208/react-activation#187]
@CJY0208 

react router V6版本，两个缓存页面之间无法互相跳转

例子如下：

https://stackblitz.com/edit/react-ts-2audg2?file=index.tsx

**Comment by CJY0208** [comment]
KeepAlive 组件上加上 key 来声明不是同一个组件，router 6 应该是在 Outlet 层面只做了简单的 vdom 替换

对于 react 来说认为是同一个 KeepAlive 组件了，也就没有触发 KeepAlive 的卸载
![image](https://user-images.githubusercontent.com/18415774/164363033-68b78b41-6f16-4447-82d6-90a891771cf4.png)

**Comment by jerrywu001** [comment]
> KeepAlive 组件上加上 key 来声明不是同一个组件，router 6 应该是在 Outlet 层面只做了简单的 vdom 替换
> 
> 对于 react 来说认为是同一个 KeepAlive 组件了，也就没有触发 KeepAlive 的卸载 ![image](https://user-images.githubusercontent.com/18415774/164363033-68b78b41-6f16-4447-82d6-90a891771cf4.png)

感谢大佬，我以为加name就可以了🤣🤣

**Comment by CJY0208** [comment]
以前 router 5 是可以不加 key 的，在 Route 这一层就会按不同的组件实例来渲染，6 的实现方式改变导致也需要加上 key = =
