### ISSUE TITLE
配合babel-plugin-import使用时, 部分功能失效

### ISSUE THREAD

**Issue by suncunhu** [CJY0208/react-activation#19]
项目中使用了 `antd-mobile` 和 `babel-plugin-import`
当从详情页面返回列表页面时，会回到列表页面的顶部，而不是停留在进入详情的那个位置
这时在列表页面中使用的 `KeepAlive`还是正常的，状态还保留着

是因为`react-activation/babel`和`babel-plugin-import` 冲突了吗？

如果去掉babel中配置的babel-plugin-import后功能效果是正常的，详情返回列表依旧停留在进入的位置

**Comment by suncunhu** [comment]
使用dva搭的项目

.babelrc的配置
```json
{
	"plugins": [
		["react-activation/babel"],
		[
			"import",
			{
				"libraryName": "antd-mobile",
				"style": "css"
			}
		]
	]
}
```

.webpackrc的配置
```
{
	"extraBabelPlugins": [
		[
			"import",
			{
				"libraryName": "antd-mobile",
				"style": "css"
			}
		]
	]
}
```

**Comment by CJY0208** [comment]
可能是 antd 样式上对滚动容器的影响，给 KeepAlive 加上 saveScrollPositipn="screen" 试试

**Comment by suncunhu** [comment]
感谢🙏 加了之后就可以了

**Comment by CJY0208** [comment]
ok，具体原因可以参考文档中关于滚动位置保存的部分
