### ISSUE TITLE
能不能选择不使用NodeKey组件

### ISSUE THREAD

**Issue by JqhSdtz** [CJY0208/react-activation#191]
首先感谢作者开源了这么优秀的工具！
我发现KeepAlive组件即使设置了id属性，也会由NodeKey组件强制加上后缀。能不能提供一个选项可以完全手动设置id。代码示例如下，我希望KeepAlive组件的id就是设置的tabKey。现在这样写，每次数组变化后都会重复渲染多个KeepAlive组件，即使设置了同样的tabKey。
```tsx
export default () => {
    const {
        sortedTabNodes
    } = useContext<TabsContextType>(TabsContext);
    return (
        <div className="keep-alive-tab-content">
            {sortedTabNodes.map(node => {
                const tabComponent = node.component;
                const Component = tabComponent.node;
                return (
                    <div key={node.name}>
                        <KeepAlive
                            name={tabKey}
                            id={tabKey}
                            saveScrollPosition="screen"
                        >
                            <Component {...tabComponent.props}/>
                        </KeepAlive>
                    </div>
                );
            })}
        </div>
    );
}
```
希望您能考虑一下这个需求，非常感谢！

**Comment by CJY0208** [comment]
OK，目前的 id 依然受 node key 标记控制，确实可能会造成意料之外的缓存问题，这个新的属性，建议叫啥？

**Comment by JqhSdtz** [comment]
> OK，目前的 id 依然受 node key 标记控制，确实可能会造成意料之外的缓存问题，这个新的属性，建议叫啥？

我觉得可以加一个fullId属性，如果有fullId属性，就直接使用fullId而不再通过NodeKey的标记生成完整ID。
只是个人见解，不知道是不是可行。

**Comment by CJY0208** [comment]
或者叫 controlledId 吧，近期事情比较多，是否考虑给个 PR 呀？可能需要改动到 react-node-key 这个库

**Comment by JqhSdtz** [comment]
> 或者叫 controlledId 吧，近期事情比较多，是否考虑给个 PR 呀？可能需要改动到 react-node-key 这个库

感谢回复！我最近也比较忙。那您有时间再考虑吧。我怕我一知半解的改不明白😂

**Comment by CJY0208** [comment]
0.11.0 加了 `cacheKey` 属性，传入时不再使用 nodeKey 生成的节点
