### ISSUE TITLE
路由相关

### ISSUE THREAD

**Issue by 3444280344** [CJY0208/react-activation#192]
一层嵌套的路由 无法缓存 
![image](https://user-images.githubusercontent.com/100815069/165662965-69862cf0-a75e-4132-8267-81775b888a6c.png)
但再嵌套一层就可以
![image](https://user-images.githubusercontent.com/100815069/165663245-8fba4bec-cc29-4c51-9b5b-a5fee801b418.png)

**Comment by CJY0208** [comment]
不太懂，activation 不关心路由，需要看看你是怎么使用 KeepAlive

**Comment by 3444280344** [comment]
![image](https://user-images.githubusercontent.com/100815069/165710567-78aaddec-7baa-4e51-bbeb-d46057e6ff3d.png)
![image](https://user-images.githubusercontent.com/100815069/165710714-97b7698a-975b-41c9-93c3-478fece490bb.png)
结构大概这个样子

**Comment by 3444280344** [comment]
![image](https://user-images.githubusercontent.com/100815069/165711359-3a0fb44d-5a80-448d-bf92-bdd219284981.png)

**Comment by CJY0208** [comment]
看起来好像是你们自己的 json 配置问题，和 activation 无关，先关了

**Comment by zfy171** [comment]
> ![image](https://user-images.githubusercontent.com/100815069/165711359-3a0fb44d-5a80-448d-bf92-bdd219284981.png)

这个问题解决了吗 我现在问题跟你一样
