### ISSUE TITLE
在layout里面包含所有的组件，组件内部的下拉框，按钮点击无反应

### ISSUE THREAD

**Issue by 1195002442** [CJY0208/react-activation#193]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/27669720/167076974-f9c1a508-83d3-43e7-bb46-6ffe1c4329de.png">
需要制作多标签，在layout里面使用keepAlive包含所有的children。组件内部操作无效，如下拉框，查询按钮等点击无反应，请问是什么原因

**Comment by CJY0208** [comment]
看起来是 react 17+ 的问题，有没有写 AliveScope 外层？

**Comment by CJY0208** [comment]
0.11.2 应该修复了这个历史问题，可以试试

**Comment by CJY0208** [comment]
有没有放置 AliveScope 外层？看起来是 react 17 事件劫持节点变化导致的问题，放 AliveScope 应该能解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月6日(周五) 下午2:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] 在layout里面包含所有的组件，组件内部的下拉框，按钮点击无反应 (Issue #193)




 

 需要制作多标签，在layout里面使用keepAlive包含所有的children。组件内部操作无效，如下拉框，查询按钮等点击无反应，请问是什么原因
