### ISSUE TITLE
升级react18后，后台给出Warning

### ISSUE THREAD

**Issue by zhouzyc** [CJY0208/react-activation#195]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/18420689/169334785-c85c827f-4ed2-47b9-a0dc-3ee5a3bd7734.png">

**Comment by zhouzyc** [comment]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/18420689/169336403-31f3fc00-4afa-493d-899e-e99a214ced51.png">
感觉上是这判断没有生效

**Comment by zhouzyc** [comment]
查看node_modules: 看到引入的是这个var ReactDOM = _interopDefault(require('react-dom'));

**Comment by CJY0208** [comment]
新版本中已经去除了对 react-dom 的引用，可以升级一下
