### ISSUE TITLE
keepAlive 包裹outlet后,登录后第一次进入首页，首页路由对应的组件渲染不出来

### ISSUE THREAD

**Issue by sunburst89757** [CJY0208/react-activation#196]
![image](https://user-images.githubusercontent.com/82217593/170402728-2f804247-0987-4b0b-a447-b39e0f7dc6ff.png)

第一次登录首页对应的组件未渲染
![image](https://user-images.githubusercontent.com/82217593/170402949-f17a3477-ff28-4a43-b1c4-d7f91af99cc5.png)
切换路由后才能渲染
![image](https://user-images.githubusercontent.com/82217593/170403025-928bd433-40b4-4cb5-b215-35d4e0041609.png)

**Comment by CJY0208** [comment]
Outlet 可能不能这样和 KeepAlive 配合，它是自己内部发生了变化，KeepAlive 阻止不了它自身的更新

**Comment by unitguyver** [comment]
我也遇到了，这个怎么解决比较好呀

**Comment by CJY0208** [comment]
可以试试下边的写法

```jsx
import { KeepAlive } from 'react-activation'
import { useOutlet, useLocation } from 'react-router-dom' // v6

function TestLayout() {
  const location = useLocation()
  const outlet = useOutlet()

  return (
    <KeepAlive key={location.key || location.pathname}>
      {outlet}
    </KeepAlive>
  )
}
```

**Comment by CJY0208** [comment]
@192114 关掉 React 严格模式就好了，这个模式会对 KeepAlive 产生一些影响，暂时还没找到解决方案
