### ISSUE TITLE
函数组件中引入 useActivate方法后始终不执行

### ISSUE THREAD

**Issue by zfy171** [CJY0208/react-activation#198]
函数组件中引入 useActivate方法后始终不执行有遇到的吗

**Comment by zfy171** [comment]
![image](https://user-images.githubusercontent.com/70139873/176651982-3fd69c09-56e1-4879-9e08-333b9bd4ab4a.png)

**Comment by CJY0208** [comment]
KeepAlive 写在啥位置？

**Comment by zfy171** [comment]
> KeepAlive 写在啥位置？

![image](https://user-images.githubusercontent.com/70139873/176802784-d517e5a9-494e-4919-8773-7e021f54f32a.png)
![image](https://user-images.githubusercontent.com/70139873/176802856-9bceaab2-c927-4605-9708-e4dd27e149d0.png)

**Comment by CJY0208** [comment]
生命周期方法需要写在 KeepAlive 内部的组件中，现在是这样写的嘛？

**Comment by zfy171** [comment]
> 生命周期方法需要写在 KeepAlive 内部的组件中，目前看起来不是这样写的，在 KeepAlive 外部，生命周期方法并不会执行

是的 但是我写到路由组件后 会出现一个新的问题 当我手动去调用clear方法去清空后 同时切换路由 当前组件将不再加载

**Comment by CJY0208** [comment]
听起来像是另一个问题，是类似下边的操作吗？

```jsx

clear()
history.push('...')

```

可试试先切换路由，在一定延时后进行 clear，
