### ISSUE TITLE
配合umi使用，添加react-activation/babel 插件后不生效，请问该如何解决？

### ISSUE THREAD

**Issue by coderyxn507** [CJY0208/react-activation#201]
1. umi中的配置  
extraBabelPlugins: [
    ["react-activation/babel", { }, 'react-activation/babel']
  ],

2.此plugin是动态给KeepAlive增加cacheKey，防止在开发环境中热更新又重复执行，getCachingNodes中会存在两个一模一样的node。

**Comment by CJY0208** [comment]
umi3 可以直接使用 [umi-plugin-keep-alive](https://github.com/alitajs/umi-plugin-keep-alive) 插件

热更新问题可以参考此处：https://github.com/alitajs/umi-plugin-keep-alive/issues/29

**Comment by coderyxn507** [comment]
其实目前针对umi就两种解决方案哇：
1.每个KeepAlive组件增加一个 cachekey
2.记录id，手动调用dropScope处理重复的缓存[alitajs/umi-plugin-keep-alive#29](https://github.com/alitajs/umi-plugin-keep-alive/issues/29)

**Comment by CJY0208** [comment]
> 其实目前针对umi就两种解决方案哇： 1.每个KeepAlive组件增加一个 cachekey 2.记录id，手动调用dropScope处理重复的缓存[alitajs/umi-plugin-keep-alive#29](https://github.com/alitajs/umi-plugin-keep-alive/issues/29)

是的，就是这两种，比较推荐手动 cacheKey，如果都写上的话其实也不需要 babel 插件了

因为 babel 插件是根据组件构造器、渲染位置之类的信息动态判断是否是新的缓存，在热更这种场景里，组件构造器会刷新，就会造成误判，目前还没想到解决办法

**Comment by coderyxn507** [comment]
好的，谢谢大佬！
