### ISSUE TITLE
umijs/max

### ISSUE THREAD

**Issue by wujun1234567** [CJY0208/react-activation#202]
你好，作者大大，请问一下目前是不是，不支持umijs/max 里面使用

**Comment by CJY0208** [comment]
理论上和任意技术都适配的



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 23, 2022 13:28 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [CJY0208/react-activation] umijs/max (Issue #202)




 
你好，作者大大，请问一下目前是不是，不支持umijs/max 里面使用

**Comment by wujun1234567** [comment]
![image](https://user-images.githubusercontent.com/48902289/180592119-5f0dfa11-4849-4dc8-88d6-f7539840ce26.png)
我看文档上有这样说

**Comment by CJY0208** [comment]
umi-plugin-keep-alive 已经有同学对 umi4 ***@***.***/max 是一个官方插件集，理论上和 activation 没冲突，实际使用中如果确实有问题，再反馈就好，不过需要提供最小复现场景哦



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 23, 2022 13:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CJY0208/react-activation] umijs/max (Issue #202)




 

 我看文档上有这样说

**Comment by wujun1234567** [comment]
好的

**Comment by pangujs** [comment]
umi4用不了，结合Wrapper无法使用，因为没有children,KeepAlive里面使用Outlet会报错
