### ISSUE TITLE
缓存页面里如果有弹出框，某些情况下会导致超过最大调用堆栈大小

### ISSUE THREAD

**Issue by Black-Jacki** [CJY0208/react-activation#208]
### 缓存页面里如果有弹出框，某些情况下会导致超过最大调用堆栈大小，但有些弹出框有问题有些没问题，大佬能估计出大概是什么原因吗？

尝试如果直接this.setState()的话弹出弹出框不会有问题，如果是使用阿里的refast库去setState好像会导致这个问题

我们现在项目里的页面多而且业务复杂，如果要每个都过一遍工作量有点大

![image](https://user-images.githubusercontent.com/63303518/186326870-0d2c6b66-57aa-4c8e-9ccd-7f3ef6743fae.png)

``` js
<Route path={`${path}/xxx/xxx`}>
   <KeepAlive name={"xxx"} cacheKey={"xxx"} saveScrollPosition={"screen"}>
      <ExampleComponent/>
   </KeepAlive>
</Route>
```

**Comment by Black-Jacki** [comment]
似乎是这种写法导致的，用的refast这个库，并且是以下写法，必定重现

```js
toggleVisible(ctx) {
  const {getState, setState} = ctx;
  const {visible} = getState();
  setState({
    visible: !visible
  })
}
```
react-activation内部是否会在某些地方有死循环了呢？

**Comment by CJY0208** [comment]
activation 可能会引起三方库本身的一些问题，可以给个复现用例吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月24日(周三) 中午12:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] 缓存页面里如果有弹出框，某些情况下会导致超过最大调用堆栈大小 (Issue #208)




 
缓存页面里如果有弹出框，某些情况下会导致超过最大调用堆栈大小，但有些弹出框有问题有些没问题，大佬能估计出大概是什么原因吗？
 
尝试如果直接this.setState()的话弹出弹出框不会有问题，如果是使用阿里的refast库去setState好像会导致这个问题
 
我们现在项目里的页面多而且业务复杂，如果要每个都过一遍工作量有点大
 

 <Route path={`${path}/xxx/xxx`}&gt;    <KeepAlive name={"xxx"} cacheKey={"xxx"} saveScrollPosition={"screen"}&gt;       <ExampleComponent/&gt;    </KeepAlive&gt; </Route&gt;

**Comment by Black-Jacki** [comment]
在codesandbox里同样写法又没有复现了，我再试试，如果复现了我发一下
另外想问下你的另一个库react-router-cache-route ，如果需求是直接以路由为缓存单位，直接用这个是不是也可以？

**Comment by CJY0208** [comment]
是的，直接用这个也可以，activation 更灵活

**Comment by CJY0208** [comment]
暂时关了
