### ISSUE TITLE
使用withAliveScope，增加的四个prop都为undefined

### ISSUE THREAD

**Issue by sunyum** [CJY0208/react-activation#21]
使用 withAliveScope，增加的四个prop都为undefined
![image](https://user-images.githubusercontent.com/20025971/71321097-dfdfef00-24ef-11ea-8835-ee2d2fbe68a7.png)

![image](https://user-images.githubusercontent.com/20025971/71321096-d3f42d00-24ef-11ea-9d14-a8fb9dcda508.png)

**Comment by CJY0208** [comment]
是否有在外层使用 AliveScope 包裹？

**Comment by sunyum** [comment]
> 是否有在外层使用 AliveScope 包裹？

明白了，多谢，我把AliveScope放在当前页面中了

**Comment by CJY0208** [comment]
OK，close~
