### ISSUE TITLE
缓存页面内有link或者style，页面会从没样式到有样式。

### ISSUE THREAD

**Issue by cuijiudai** [CJY0208/react-activation#211]
我用 <KeepAlive> 缓存了 umi 的 <MicroAppWithMemoHistory> ，这样做会导致从没有样式闪到有样式，能不能将样式提前加载？

**Comment by CJY0208** [comment]
这个不是 activation 的问题吧

**Comment by cuijiudai** [comment]
> 这个不是 activation 的问题吧

我能不能拿到缓存数据的 html ，然后把html里的 style 匹配出来，提前插入到页面上  ?

**Comment by CJY0208** [comment]
不太清楚你的意思，听起来是你们项目构建配置方面的问题，和 activation 功能无关，这个 issue 先关了，如果有需要的话可以开个在线示例说明意图
