### ISSUE TITLE
使用react-activation 缓存无效果

### ISSUE THREAD

**Issue by a717822** [CJY0208/react-activation#212]
目前采用qiankun框架，是在主应用中，针对子应用进行缓存，路由采用的是动态路由的形式；在浏览器调试中，能够看到
 Keeper部分，但是缓存的应用失效。
![image](https://user-images.githubusercontent.com/31062855/187891410-1021f1b1-bece-4bdd-9811-590f3b38109b.png)

qiankun采用的是 registerMicroApps  start 的方式进行启动的，是否与这部分相关，希望大佬能够提供下思路。谢谢

**Comment by CJY0208** [comment]
registerMicroApps 的话 qiankun 在不符合激活条件的时候会内部注销子组件，activation 无法阻止，建议换成手动模式 loadMicroApp

**Comment by CJY0208** [comment]
手动模式下，根据 keep alive 生命周期决定是否需要卸载 qiankun 子应用
