### ISSUE TITLE
Too many transient updates, may have encountered an infinite loop of updates, forced to pause the update

### ISSUE THREAD

**Issue by codeZyb** [CJY0208/react-activation#213]
Too many transient updates, may have encountered an infinite loop of updates, forced to pause the update

**Comment by CJY0208** [comment]
能碰到这个 bug，不容易啊，能提供复现用例嘛？

**Comment by codeZyb** [comment]
父组件有个context,有个touchMove的事件一直在更新context的value就导致这个事情了，keepAlive的props也没有更新

**Comment by CJY0208** [comment]
懂了，就是正常的 update 太频繁了，被 keep alive 内部当成是死循环了

**Comment by CJY0208** [comment]
更新死循环检测机制是给一开始 keep alive 还不成熟的时候准备的，后边运行了一两年已经没有人反馈过了，我想想下个版本要不要删掉这个机制

**Comment by 936446507** [comment]
@CJY0208 请问有计划删掉这个机制吗？下个版本有个大概日期吗？

**Comment by CJY0208** [comment]
这周末吧

**Comment by CJY0208** [comment]
发了 0.12.0，去除了这个机制，可以试试是否修复了问题
