### ISSUE TITLE
umi 把react-activation封装到npm包，后报错

### ISSUE THREAD

**Issue by MTTTM** [CJY0208/react-activation#216]
**背景:**

我们需要把<KeepAlive /> 和 <AliveScope> 放到我们的npm包里面，再导出来给我们的不同项目使用

**umi的layouts/index.ts**

`import React from 'react';
import type { IRouteComponentProps } from 'umi';
import { AliveScope } from 'omega-sdk';

export default ({ children }: IRouteComponentProps) => {
  return (
    <AliveScope>
      <div className='xxxx-xxx --sfsdf'>{children}</div>
    </AliveScope>
  );
};
`

**keepAlive组件封装成:**

`import React, { useEffect } from 'react';
import KeepAlive, { useAliveController } from 'react-activation';
import type { FC } from 'react';
interface Iprops {
  name: string;
}

const ChildDemo: FC<Iprops> = props => {
  console.log('props', props);
  const keepAliveKey = props.name;
  if (!keepAliveKey) {
    console.error('keepAlive 包装组件 的key不能为空');
  }
  const { dropScope } = useAliveController();
  // 关闭页签时清空缓存
  const clearCache = (e: any) => {
    console.log('关闭tab', e?.data?.deleteTab, keepAliveKey);
    if (e?.data?.deleteTab === keepAliveKey) {
      dropScope(keepAliveKey);
    }
  };
  useEffect(() => {
    window.addEventListener('message', clearCache, false);
    return () => {
      window.removeEventListener('message', clearCache, false);
    };
  }, []);
  return <div />;
};

/**
 * 维护初始解模型
 */
/**
 *
 * @param key   页面组件的文件路径 例如:'/xp-vscm-web/outWarehouseManagement/carrierAppointment'
 * @param children 要被包装的页面组件
 * @returns
 */
const KeepAliveBoundaries: FC<Iprops> = props => {
  const keepAliveKey = props.name;
  return (
    <KeepAlive name={keepAliveKey}>
      {props.children}
      <ChildDemo name={keepAliveKey} />
    </KeepAlive>
  );
};

export default KeepAliveBoundaries;
`

**现在报错:**

devScripts.js:6523 You should not use <KeepAlive /> outside a <AliveScope>

**如果没有抽离到npm包是没有问题的**

react调试截图:
![7](https://user-images.githubusercontent.com/8638001/189020917-5439d854-b1d8-4024-ba28-c3aaac718c52.png)

**Comment by CJY0208** [comment]
抽 npm 包的话需要注意 react 或者 react-dom 是否存在多个版本之类的问题，会造成 Context 由不同的 react 实例创建，可能产生上述问题

如果是这个原因的话，那就和 activation 应该无关，先关了
