### ISSUE TITLE
子组件在componentDidMount中更新父组件布局卸载掉AliveScope，导致的异常

### ISSUE THREAD

**Issue by sunyum** [CJY0208/react-activation#22]
我做了两个页面布局组件，
ALayout：使用了AliveScope
    `AliveScope->KeepAlive->children`
BLayout：未使用
    `div->children`

默认使用 Basic->ALayout，在children的componentDidMount中会调用 Basic 的方法
更新布局为 Basic->BLayout，此时将会抛出异常
![image](https://user-images.githubusercontent.com/20025971/71419180-1f057000-26a9-11ea-8cfd-1f38bfd0aadb.png)
![image](https://user-images.githubusercontent.com/20025971/71419187-2593e780-26a9-11ea-8b86-c1ac087df485.png)

这个应该对使用没有影响，不过就是看着别扭

**Comment by CJY0208** [comment]
OK，稍后尝试修复
另外，建议将 `AliveScope` 添加到应用入口处，应该可以避免此问题
