### ISSUE TITLE
作者考虑兼容react18.x吗？

### ISSUE THREAD

**Issue by ikangjie** [CJY0208/react-activation#220]

**Comment by CJY0208** [comment]
18.x 现在收集到的问题主要是 ts 类型问题，还有其他的吗？

**Comment by ikangjie** [comment]
升级到react18.x后目前发现的问题有：
1：在keepalive包裹内的组件使用react-router-dom useParams()，即使路由改变了，获取到的参数依旧是第一次的数据；
2：在keepalive包裹内的组件改变state状态，不会引起组件的更新

**Comment by CJY0208** [comment]
related #219
