### ISSUE TITLE
跳转指定页面的时候才缓存要怎么做啊

### ISSUE THREAD

**Issue by ccc-fighting** [CJY0208/react-activation#221]

**Comment by ccc-fighting** [comment]
详情页没做任何操作，跳回列表页A，列表页A不刷新，列表页A页码不变
详情页进行了编辑操作，跳回列表页A，列表页A刷新，列表页A页码不变
详情页进行了新建操作，跳回列表页A，列表页A刷新，列表页A页码变为1

**Comment by ccc-fighting** [comment]
路由：
![image](https://user-images.githubusercontent.com/69502064/190945122-d4bc68d2-5ca6-498a-bc26-07be8c37d7e1.png)

**Comment by CJY0208** [comment]
是使用了 activation 后无效果吗？这里只能解答使用过程中遇到的问题，如果你还没开始用，或者是业务上的问题，没办法解答

**Comment by ccc-fighting** [comment]
> 是使用了 activation 后无效果吗？这里只能解答使用过程中遇到的问题，如果你还没开始用，或者是业务上的问题，没办法解答

1、是没有效果 2、想问一下，指定页面的有没有好的解决办法

**Comment by CJY0208** [comment]
问题 1：需要提供你的使用方式截图，上边的截图没看到你使用了 KeepAlive 组件
问题 2：不理解你的问题

**Comment by ccc-fighting** [comment]
> 问题 1：需要提供你的使用方式截图，上边的截图没看到你使用了 KeepAlive 组件 问题 2：不理解你的问题

用了，但是滚动条失效了
![image](https://user-images.githubusercontent.com/69502064/191878651-40e81c50-4fa4-4176-92b2-4861254aacc6.png)

**Comment by ccc-fighting** [comment]
> 问题 1：需要提供你的使用方式截图，上边的截图没看到你使用了 KeepAlive 组件 问题 2：不理解你的问题

但是好像 onScrollCapture 不好使了

**Comment by CJY0208** [comment]
参见 #227
