### ISSUE TITLE
使用场景vite2,CSSTransition,react18,routerv6不生效

### ISSUE THREAD

**Issue by waterJLuck** [CJY0208/react-activation#224]
![image](https://user-images.githubusercontent.com/70199240/191412882-023a0a33-c276-4c5e-89d4-70ab1a72e109.png)
![image](https://user-images.githubusercontent.com/70199240/191412785-ddcca731-e808-4932-95c4-2692a0851688.png)
缓存不生效 请问是否还需要其他的配置

**Comment by CJY0208** [comment]
需要先解决 vite 上的插件问题，或者手动标记 cacheKey 属性，参考 #168

**Comment by waterJLuck** [comment]
首先很感谢您百忙之中的回复。
我按照您给的参考链接尝试安装了react-node-key/vite并将它加入vite的plugin中，依然无法生效。手动标记cacheKey 似乎也不起作用，我查看了浏览器被keepalive包裹下的节点，都没有出现demo中_nk属性值。
![image](https://user-images.githubusercontent.com/70199240/191428955-439be745-7aea-4e4a-87cf-b8c1dbf16b5f.png)
再次感谢您的帮助！

**Comment by CJY0208** [comment]
_nk 属性的目的就是自动生成 cacheKey，如果你传递了 cacheKey 应该是可以生效的，不行的话，可能需要提供一个简单的复现用例，我可以看看

**Comment by waterJLuck** [comment]
您好 谢谢您的回复。
在我刚刚构建一个简单的demo的过程中尝试到了 cacheKey 我传值为loaction.key时不生效，但pathname是生效的，这应该是因为location.key每次都是新生成的，所以不触发缓存。
并且若不用cacheKey，只在vite2中进行plugin的引用是不生效的。只能配合cacheKey来用。
总之，谢谢您的回复，占用您的时间为我解答。祝你生活愉快。
![image](https://user-images.githubusercontent.com/70199240/191451588-c5265a40-3827-4557-ba5c-fff6c9f8bd7b.png)
