### ISSUE TITLE
配合antd 的Button使用，Button会自动出现Loading状态

### ISSUE THREAD

**Issue by waterJLuck** [CJY0208/react-activation#225]
![1](https://user-images.githubusercontent.com/70199240/191672296-22e57f95-0b5b-45b0-b8dd-59bbac84933d.gif)
在线地址：https://codesandbox.io/p/github/waterJLuck/antd-activation/draft/lucid-tdd?import=true&file=%2Fsrc%2Fview%2Fpage1.tsx

复现方法： 点击增加按钮 一秒后再点击去page2按钮

**Comment by CJY0208** [comment]
这个问题确实挺离奇的，我看看

**Comment by Cool-Star** [comment]
不仅仅是Button Dropdown ToolTip 等

**Comment by chenhb23** [comment]
React 版本降到 17 就好了

**Comment by GitHub-WF** [comment]
同样的问题，有一部分状态没有缓存

**Comment by CJY0208** [comment]
感觉像是 rc-motion 库的问题，先同步一下
![image](https://user-images.githubusercontent.com/18415774/200799292-5eebff2a-90b0-48dd-af2b-a812268d87f9.png)

**Comment by CJY0208** [comment]
react 官方目前记录了这个问题
https://github.com/facebook/react/issues/25511

**Comment by CJY0208** [comment]
最终确认是 `react-freeze` 与 createRoot 搭配使用时会造成 useLayoutEffect 多次重复执行，而 antd 底层的  `rc-motion` 动画库依赖了 useLayoutEffect，导致了使用了该库的 Loading 图标被异常激活，理论上所有使用 rc-motion 的部分都有这个问题

已经给 react-freeze 提了 issue，但不确定这块有方式解决
https://github.com/software-mansion/react-freeze/issues/29

目前的解决方案：
1. 不使用 createRoot，可能会不兼容后续部分 React 本身的更新（用户侧的调整）
2. 不使用 react-freeze，会导致缓存的性能下降（需要 react-activation 更新支关闭 freeze 功能）

**Comment by CJY0208** [comment]
react-activation 发布了 0.12.2 支持通过 `autoFreeze={false}` 关闭 freeze 功能，关闭后不会在出现 loading，但缓存性能会有所下降

**Comment by Cool-Star** [comment]
我目前的解决方案是关闭antd组件的动画过渡效果，这个api在antd官方文档上并没有提及，但实际上是可以透传给底层rc组件生效的。

**Comment by shangwanzheng** [comment]
请问这个属性是啥。。。

**Comment by shangwanzheng** [comment]
> 我目前的解决方案是关闭antd组件的动画过渡效果，这个api在antd官方文档上并没有提及，但实际上是可以透传给底层rc组件生效的。

这个有具体文档么

**Comment by chengdick** [comment]
发现新问题，createRoot 如果用这个方法发现，pro-table组建加载会导致路由缓慢，卡顿，还是感觉用autoFreeze好点

**Comment by evelope** [comment]
使用 autoFreeze={false} ， 页面第一次切换不会缓存，第二次才会缓存。
比如刚打开的是A， 跳转到B，再返回A，发现A没有缓存。
然后再次 跳转到B，再返回A，这时候A是缓存的。
