### ISSUE TITLE
求助，有没有好的思路，列表是antd的Table ，列表页就是class：

### ISSUE THREAD

**Issue by ccc-fighting** [CJY0208/react-activation#227]
列表是antd的Table ，列表页就是class：
详情页没做任何操作，跳回列表页A，列表页A不刷新，列表页A页码不变
编辑进行了编辑操作，跳回列表页A，列表页A刷新，列表页A页码不变
新增页进行了新建操作，跳回列表页A，列表页A刷新，列表页A页码变为1

_Originally posted by @ccc-fighting in https://github.com/CJY0208/react-activation/issues/221#issuecomment-1250518071_

**Comment by CJY0208** [comment]
这是业务逻辑，需要你自己配合业务代码实现，比如回跳到列表页时通过 url 参数告诉列表页需要刷新

要刷新被 activation 的缓存页面的话，可以配合 activation 提供的 refresh 方法实现

**Comment by ccc-fighting** [comment]
> 这是业务逻辑，需要你自己配合业务代码实现，比如回跳到列表页时通过 url 参数告诉列表页需要刷新
> 
> 要刷新被 activation 的缓存页面的话，可以配合 activation 提供的 refresh 方法实现

是的，就是想想有没有大佬可以提供好的思路
现在有一个问题是，详情页B 跳转到列表页A，列表A不刷新（第一步），列表页A进入编辑页C，再由编辑页C返回列表页---刷新列表页A（第二步），此时，进入详情页B,再进入列表页A（第三步），此时保持在“第一步”列表A不刷新的状态是正常吗？可是在第二步的时候已经刷新了列表页了

**Comment by CJY0208** [comment]
应该是不正常的，不过我不清楚你是如何操作得到了这个结果，可以提供你的用例吗？

**Comment by ccc-fighting** [comment]
> 逻辑上应该是不正常的，第三步后，A 页面应该是第二步刷新后的状态
> 
> 不过我不清楚你是如何操作得到了这个结果，可以提供你的用例吗？

![image](https://user-images.githubusercontent.com/69502064/192415025-a97179d0-c1e2-4e28-9051-16c61d1f0f75.png)

**Comment by ccc-fighting** [comment]
> 逻辑上应该是不正常的，第三步后，A 页面应该是第二步刷新后的状态
> 
> 不过我不清楚你是如何操作得到了这个结果，可以提供你的用例吗？
使用这个的话，对生命周期触发顺序有什么影响？具体的触发顺序是什么？

**Comment by ccc-fighting** [comment]
> 逻辑上应该是不正常的，第三步后，A 页面应该是第二步刷新后的状态
> 
> 不过我不清楚你是如何操作得到了这个结果，可以提供你的用例吗？

这个还会影响antd-DatePicker 的初始化？？？？
