### ISSUE TITLE
react-router 中许多使用 context 的 api 失效

### ISSUE THREAD

**Issue by MinJieLiu** [CJY0208/react-activation#23]
react-router 中比如 `useParams` `useRouteMatch` 等 API，`useParams` 中使用了 `React.useContext()`。有迂回的解决办法吗

**Comment by MinJieLiu** [comment]
解决了

```ts
import { __RouterContext } from 'react-router';

fixContext(__RouterContext);
```

**Comment by CJY0208** [comment]
可以解决但性能不一定好，建议是把 AliveScope 写在 Router 内部，参考[文档此处](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#2-%E4%B8%9A%E5%8A%A1%E4%BB%A3%E7%A0%81%E4%B8%AD%E5%9C%A8%E4%B8%8D%E4%BC%9A%E8%A2%AB%E9%94%80%E6%AF%81%E7%9A%84%E4%BD%8D%E7%BD%AE%E6%94%BE%E7%BD%AE-alivescope-%E5%A4%96%E5%B1%82%E4%B8%80%E8%88%AC%E4%B8%BA%E5%BA%94%E7%94%A8%E5%85%A5%E5%8F%A3%E5%A4%84)

**Comment by MinJieLiu** [comment]
嗯，我试试

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/71862880-27908880-3136-11ea-8f1c-e16a60fb57b6.png)
这个原本就是放内部的

**Comment by MinJieLiu** [comment]
放内部仍然需要 `fixContext(__RouterContext);` 对吧

**Comment by CJY0208** [comment]
没有看过 router 的新 api，也许确实是需要的，有空后我看看能不能免除这一步吧，目前应该是需要的

**Comment by MinJieLiu** [comment]
嗯嗯，谢谢

**Comment by HelloAny** [comment]
我也遇到这个问题，请问 @MinJieLiu 是怎么解决的，这个__RouterContext我并未在react-router v5版本中找到

**Comment by CJY0208** [comment]
你好，请问可以提供用例吗？我可以用来分析原因



---原始邮件---
发件人: "AmiKara"<notifications@github.com&gt;
发送时间: 2020年9月10日(周四) 凌晨0:03
收件人: "CJY0208/react-activation"<react-activation@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"CJY"<375564567@qq.com&gt;;
主题: Re: [CJY0208/react-activation] react-router 中许多使用 context 的 api 失效 (#23)




 
我也遇到这个问题，请问 @MinJieLiu 是怎么解决的，这个__RouterContext我并未在react-router v5版本中找到

**Comment by HelloAny** [comment]
我的问题和 #43 很相似

router.js:

```
const Routes = (done) => {
  return (
    <TransitionGroup>
      {routes.map(({ path, Component }) => (
        <Route key={path} exact path={path}>
          {
            (props) => {
              return (
                <CSSTransition
                  in={props.match != null}
                  timeout={400}
                  classNames="page"
                  id="page"
                  unmountOnExit={true}
                >
                  <div className="page">
                    {
                      path === `/article/:number` ?
                        <KeepAlive >
                          <Component {...props} />
                        </KeepAlive> :
                        <Component {...props} />
                    }
                  </div>
                </CSSTransition>

              )
            }
          }
        </Route>
      ))
      }
    </TransitionGroup >
  )
}




   <Router>
      <AliveScope>
        <Header></Header>
        <Routes />
      </AliveScope>
   </Router>
```

在其页面中调用`useParams`函数无法获取路由参数,打印为`undefined`


```
const Articles = ({ show, match }) => {
  let { number } = useParams();
  console.log(number) //undefined
  return (.....)
}
```

**Comment by CJY0208** [comment]
去掉 KeepAlive 的话是可以获取的吗？

**Comment by HelloAny** [comment]
> 去掉 KeepAlive 的话是可以获取的吗？

对

**Comment by zhaoxunyong** [comment]
我也有类似的问题，获取不到参数中的id:

import React from 'react'
import { withRouter } from 'react-router-dom'

const Detail = ({ match }) => <h3>Detail with ID {match.params.id}</h3>

export default withRouter(DemoDetail)
