### ISSUE TITLE
react18下，缓存时与新组件加载时可能导致react-dom无限render

### ISSUE THREAD

**Issue by Cool-Star** [CJY0208/react-activation#231]
由于react18新特性下，state变更不一定渲染，故在组件卸载与新组件渲染的时候可能会引发状态合并更新。

具体的场景是，在我的页面级组件都使用缓存的情况下，当切换到另一个使用了缓存的组件，如果该组件在生命周期函数中调用远程数据更新状态，大概率会引发内存泄漏页面卡死。

排查各方问题后，在不使用keepAlive组件后完全正常，故修改node_modules包内react-activation源码，将延迟冻结状态的触发使用强制刷新，此问题未再复现。

```
this.freezeTimeout = setTimeout(function () {
        ReactDom.flushSync(function() {
          _this3.safeSetState({
            freeze: true
          });
        })
      }, 1000);
```

**Comment by CJY0208** [comment]
感谢，要不要来个 PR？

**Comment by Cool-Star** [comment]
已提交PR

**Comment by CJY0208** [comment]
OK，看到 #232 了，需要判断一下是否存在 flushSync 方法，兼容一下 react18 以下的版本

**Comment by Cool-Star** [comment]
react 16版本其实已经内置了这个方法，只是在未启用18新特性之前该方法没有明显作用。

**Comment by CJY0208** [comment]
16 上内置的方法是哪一个？我找了一下好像没找到，感觉还是要做兼容的，不然 16+ 可能会不支持

**Comment by Cool-Star** [comment]
@CJY0208  在react-dom 16.0.0 中已经是导出了flushSync方法，但这个方法在文档中没有提及，16没有启用并发特性故此方法只是单纯执行传入的函数。 react 18 以后才在文档上正式推出了这个方法，所以如果在react16+ 使用这个方法应该不需要考虑兼容性。

**Comment by CJY0208** [comment]
好，我下 16 17 版验证下，OK 就发新版
