### ISSUE TITLE
如果缓存页面里加入了弹窗，然后从弹窗里的内容点击跳转到另一个页面，弹窗会一直不关闭

### ISSUE THREAD

**Issue by Gonaldo7** [CJY0208/react-activation#234]

**Comment by CJY0208** [comment]
因为页面被缓存了，不会因为页面卸载而触发弹窗的卸载，你可能要在跳转的时候手动关闭一下弹窗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月28日(周五) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] 如果缓存页面里加入了弹窗，然后从弹窗里的内容点击跳转到另一个页面，弹窗会一直不关闭 (Issue #234)

**Comment by Gonaldo7** [comment]
但是我想跳转页面后返回回来让弹窗不关闭的状态&nbsp;


驱动精灵
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月28日(星期五) 晚上6:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CJY0208/react-activation] 如果缓存页面里加入了弹窗，然后从弹窗里的内容点击跳转到另一个页面，弹窗会一直不关闭 (Issue #234)





 因为页面被缓存了，不会因为页面卸载而触发弹窗的卸载，你可能要在跳转的时候手动关闭一下弹窗 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年10月28日(周五) 下午4:26 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [CJY0208/react-activation] 如果缓存页面里加入了弹窗，然后从弹窗里的内容点击跳转到另一个页面，弹窗会一直不关闭 (Issue #234)

**Comment by CJY0208** [comment]
可以用缓存生命周期在返回后恢复弹窗，总之，组件不会被卸载弹窗的隐藏显示就需要你手动控制了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月28日(周五) 晚上9:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CJY0208/react-activation] 如果缓存页面里加入了弹窗，然后从弹窗里的内容点击跳转到另一个页面，弹窗会一直不关闭 (Issue #234)




 但是我想跳转页面后返回回来让弹窗不关闭的状态&amp;nbsp; 
 
 
 驱动精灵 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年10月28日(星期五) 晚上6:08 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [CJY0208/react-activation] 如果缓存页面里加入了弹窗，然后从弹窗里的内容点击跳转到另一个页面，弹窗会一直不关闭 (Issue #234) 
 
 
 
 
 
  因为页面被缓存了，不会因为页面卸载而触发弹窗的卸载，你可能要在跳转的时候手动关闭一下弹窗  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年10月28日(周五) 下午4:26  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: [CJY0208/react-activation] 如果缓存页面里加入了弹窗，然后从弹窗里的内容点击跳转到另一个页面，弹窗会一直不关闭 (Issue #234)
