### ISSUE TITLE
Chrome 49低版本有兼容

### ISSUE THREAD

**Issue by ago008** [CJY0208/react-activation#24]
`function _toConsumableArray(arr) {
 // 这里有可能是HTMLCollection类型
  if(arr instanceof HTMLCollection){
    const arr = []
    for(var i = 0;i<arr.length;i++){
      a.push(arr[i])
    }
    return a;
  }
  return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread();
}
`
随便写了下，作者可以优化一下，否则低版本Chrome会白屏的说

**Comment by CJY0208** [comment]
看起来是 babel 转义 `...` 语法时所用到的辅助函数没有适配 chrome 低版本，也许修改 babel 适配的 broswerlist 可以解决，改天尝试下

**Comment by wangyinwei1** [comment]
这个兼容问题有解决了吗

**Comment by CJY0208** [comment]
还未解决，感觉是 babel 的问题，目前在忙业务，还没空看具体原因

**Comment by CJY0208** [comment]
@ago008 @wangyinwei1 具体的报错信息有吗？需要定位一下是否是 babel 的原因

我尝试给 @babel/env 增加了 browserslist 项 `Chrome <= 49` 但编译结果没有发生变化

**Comment by Nutlee** [comment]
遇到疑似也是兼容性问题，iOS 10 及以下时

> TypeError: Invalid attempt to spread non-iterable instance undefined

**Comment by CJY0208** [comment]
> 遇到疑似也是兼容性问题，iOS 10 及以下时
> 
> > TypeError: Invalid attempt to spread non-iterable instance undefined

尝试给项目增加垫片，看看能否修复问题？

例如在项目入口处引入

```js
import 'react-app-polyfill/stable'
```

**Comment by CJY0208** [comment]
看起来与垫片、兼容性无关，可能是隐藏的 bug

**Comment by Nutlee** [comment]
> 看起来与垫片、兼容性无关，可能是隐藏的 bug

调试了下 @ago008 的方法是可以的，只不过会丢失 keep alive 效果，比白屏可接受点。可否先采用此方案修一版？ 不然我这要先降级掉了🤦‍♀️

**Comment by CJY0208** [comment]
这段代码其实是 babel 编译生成的辅助代码...我目前正试图找出修正 babel 编译行为的方式，但暂时还没有进展，稍后尝试手动修复，看看能否保留 keep-alive 效果

**Comment by Nutlee** [comment]
> 是 babel 编译生成的辅助代码...我目前正试图找出修正 babel 编译行为的方式，但暂时还没有进展，稍后尝试手动修复，看看能否保留 keep-alive 效果


我目前这么 hack 的，先保证不白屏
```
// hack HTMLCollection 不可遍历
try {
  if (window.HTMLCollection && !window.HTMLCollection.prototype[Symbol.iterator]) {
    HTMLCollection.prototype[Symbol.iterator] = Array.prototype[Symbol.iterator];
  }
} catch (error) {
  //
}
```

**Comment by tong233** [comment]
> 这段代码其实是 babel 编译生成的辅助代码...我目前正试图找出修正 babel 编译行为的方式，但暂时还没有进展，稍后尝试手动修复，看看能否保留 keep-alive 效果

可以尝试一下这个babel plugins @babel/plugin-proposal-object-rest-spread

**Comment by CJY0208** [comment]
新版本增加了 core-js 功能垫片，或许能修复不同设备或浏览器上的兼容性问题，可以试试
