### ISSUE TITLE
页面回退以后空白

### ISSUE THREAD

**Issue by sth1193101613** [CJY0208/react-activation#243]
从a页面到b页面  然后b页面到c页面 再从c页面回退以后 页面空白  ka-wrapper里面的dom都不见了 这是什么原因？

**Comment by sth1193101613** [comment]
父路由去掉缓存就没事了。。这是为什么

**Comment by CJY0208** [comment]
检查下严格模式有没有打开，需要关闭，还不行的话需要提供一下 demo
