### ISSUE TITLE
针对列表,编辑功能如何做局部更新处理?

### ISSUE THREAD

**Issue by Jinxishihenian** [CJY0208/react-activation#250]
需求场景:
分页列表,有编辑功能；编辑完成返回列表,保持列表状态(页码,筛选条件等)但是编辑的项要更新,也就是局部更新。是否有办法处理？

**Comment by CJY0208** [comment]
需要自行调用业务接口来更新数据

**Comment by Jinxishihenian** [comment]
> 需要自行调整业务接口来更新数据
是的，通过您提供的componentDidActivate生命周期方法可以实现该场景.

**Comment by CJY0208** [comment]
这里是生命周期的文档：[生命周期](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F)
