### ISSUE TITLE
配合 React 18x 存在报错

### ISSUE THREAD

**Issue by senlinmilelu** [CJY0208/react-activation#251]
"react": "18.2.0",
"react-activation": "0.12.2",
"react-dom": "18.2.0",
"react-router-dom": "6.8.0"

![image](https://user-images.githubusercontent.com/22190133/216527293-05f3d50a-0c6b-4898-b205-92f4fe3d7a65.png)
![image](https://user-images.githubusercontent.com/22190133/216527497-60ed4a54-c12a-42c2-944c-4e48d04d809a.png)

**Comment by CJY0208** [comment]
可以做一个简单的 codesandbox 吗

**Comment by senlinmilelu** [comment]
> 可以做一个简单的 codesandbox 吗

降低了 react和react-dom版本 已经好了

**Comment by lijie602** [comment]
同样是该问题。应该跟  <React.StrictMode>有关，不开启StrictMode不会报错

**Comment by CJY0208** [comment]
如果是严格模式的话，那就不算是 bug 了，先关掉
