### ISSUE TITLE
使用antd组件，激活过后再进行切换路由，页面会闪屏

### ISSUE THREAD

**Issue by puchenhui** [CJY0208/react-activation#255]
在缓存的页面中使用了antd的 Select、Popover、Drawer、Button组件，当激活过某个组件之后，当切换页面再次回来之后，之前激活的这个组件会重新激活一次。
举例：
Select会把下拉框收缩一次，Drawer也会收缩一次，Button按钮宽度会变宽之后正常，Popover也会闪现一次

**Comment by puchenhui** [comment]
请问有什么好的办法解决这个问题吗

**Comment by puchenhui** [comment]
通过{autoFreeze = false} 这个属性已解决

**Comment by puchenhui** [comment]
通过{autoFreeze = false} 这个属性已解决

**Comment by LoveEocding** [comment]
> autoFreeze = false

点赞
