### ISSUE TITLE
antd proTable去详情页返回的时候查询条件会加载不出来

### ISSUE THREAD

**Issue by zwd609258057** [CJY0208/react-activation#258]
https://codesandbox.io/s/cha-xun-biao-ge-forked-nzkw0b?file=/App.tsx

快速点击没问题，去详情页等3-5s再返回就有问题了（使用隐藏显示模拟跳转，路由跳转是一样的问题）

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/8108601/223310601-7887c605-0369-4cfe-a88f-ea068a0aaa54.png">

**Comment by CJY0208** [comment]
是 react18 createRoot 中 useLayoutEffect 的行为和 react-freeze 冲突有关，参考这个 https://github.com/CJY0208/react-activation/issues/225#issuecomment-1311136388

两种解决方式，选其一
1. 使用 react-dom render 替换 react-dom/client createRoot
2. KeepAlive 标签加上 `autoFreeze={false}`，关闭内部的 freeze 功能
