### ISSUE TITLE
和use-context-selector同时使用时的问题

### ISSUE THREAD

**Issue by lhz87127855** [CJY0208/react-activation#259]
0.8之后已经解决了React原生的context的断层问题，所以内部采用fixed函数调用解决。
但是原生的context存在性能问题，所以会去使用use-context-selector来解决不必要的渲染。
这会导致二者同时使用时，进行路由切换会导致白屏 React 130错误
以下为猜测：
use-context-selector内部采用的是ref的方式来存储context，此模式于react-activation中的对于context的处理不兼容。
![image](https://user-images.githubusercontent.com/4485176/224017916-8d467114-f395-4587-99ce-850e627d8895.png)

**Comment by CJY0208** [comment]
可以给一个在线 demo 吗，没用过 useContextSelector

**Comment by wangjunget** [comment]
> 可以给一个在线 demo 吗，没用过 useContextSelector

我这边也遇到了这个问题
复现demo: [https://codesandbox.io/s/ke-guan-bi-de-yi-fang-wen-lu-you-tab-shi-li-ke-an-lu-you-can-shu-fen-duo-fen-huan-cun-forked-o8xggq?file=/src/views/Item.js](https://codesandbox.io/s/ke-guan-bi-de-yi-fang-wen-lu-you-tab-shi-li-ke-an-lu-you-can-shu-fen-duo-fen-huan-cun-forked-o8xggq?file=/src/views/Item.js)

**Comment by lhz87127855** [comment]
> 

谢谢提供demo，我最近在搞项目，没来得及搞demo

**Comment by CJY0208** [comment]
看了一下 use-context-selector 内部删除了 context.Consumer，这个行为导致了 react-activation 在尝试使用 context.Consumer 自动修复 context 问题时，渲染了一个 undefined 值，导致了报错

报错比较好解决，在渲染 Consumer 前做个判断就好，但因为 use-context-selector 的上下文实现并不通用，所以与 activation 配合使用时，依然可能存在上下文断层问题

我先修复报错，use-context-selector 在 activation 中断层问题后续再找方案修正

**Comment by CJY0208** [comment]
`v0.12.3` 内重新声明了 Consumer，经验证，此问题已解决
