### ISSUE TITLE
Cannot create property 'name' on string 'react-activation/babel'

### ISSUE THREAD

**Issue by lin593** [CJY0208/react-activation#261]
![image](https://user-images.githubusercontent.com/38357156/226511513-578744b4-5409-4f29-8de0-5e5db3f44e11.png)
打包时出现这个问题

**Comment by CJY0208** [comment]
看起来是 babel 插件的使用方式有问题，具体需要提供用例

**Comment by CJY0208** [comment]
参考这里：#168
