### ISSUE TITLE
ide 警告  'AliveScope' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by lingting** [CJY0208/react-activation#262]
![image](https://user-images.githubusercontent.com/59352063/227447311-34d2d883-2769-40d3-90f9-ad11f29a2ae2.png)

**Comment by CJY0208** [comment]
React 18 的类型声明和 16 17 有所不同，所以会有这个问题，目前还不确定要如何兼容修复

**Comment by lingting** [comment]
> React 18 的类型声明和 16 17 有所不同，所以会有这个问题，目前还不确定要如何兼容修复

直接针对不同版本发包呢? 或者给新版本一个新的类?
