### ISSUE TITLE
vite环境本地运行可以，打包环境报 useLocation() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by lin593** [CJY0208/react-activation#264]
场景：跳转到含缓存的页面，页面是用标签内嵌的组件,会出错
import Activation,{ useActivate , useAliveController } from 'react-activation'
return (
    <div>
      <Activation 
        name='propBoxId'
        id='propBoxId'
        key='propBoxId'
          <BoxDetailIndex/>
      </Activation>
    </div>
  )
vite.config.ts 已用  reactNodeKey()

**Comment by CJY0208** [comment]
将 AliveScope 放在路由的 Router 内部试试

**Comment by lin593** [comment]
我是这样处理的，还是说试试你的那种
<AliveScope>
    <App />
  </AliveScope>

**Comment by lin593** [comment]
我是这样处理的，还是说试试你的那种
<AliveScope>
    <App />
  </AliveScope>

**Comment by lin593** [comment]
我是用它包括 <App />的，可以的吗，还是说试试你这种

**Comment by lin593** [comment]
我是用它包括 App的，可以的吗，还是说试试你这种

**Comment by lin593** [comment]
<img width="413" alt="截屏2023-03-28 18 13 31" src="https://user-images.githubusercontent.com/38357156/228204667-f3884b51-c87e-4ded-b35c-28f7b84f357c.png">

**Comment by lin593** [comment]
已经解决
