### ISSUE TITLE
用KeepAlive包裹后，搜索别的内容，URL变化，但内容仍是上一个搜索结果的

### ISSUE THREAD

**Issue by liuyanhe96** [CJY0208/react-activation#265]
搜索出来结果列表，点进去某一个，再后退回来，之后搜索别的内容，就出现题目问题。
 目前在navigate() 跳转下一行，加入window.location.reload()来解决，但觉得是个笨方法，请问是什么原因和如何解决呢？

**Comment by liuyanhe96** [comment]
只有从结果页面，点击进入详情页后，再回退到结果页，然后搜索才会出现这种情况

**Comment by liuyanhe96** [comment]
解决 
![image](https://user-images.githubusercontent.com/44930196/231039365-ab4f85de-5a10-4c64-8769-74f657d5401e.png)

https://github.com/CJY0208/react-activation/issues/196#issuecomment-1140195454

**Comment by XUHANLIN** [comment]
这个问题我也碰到了，给KeepAlive加上key无法解决
