### ISSUE TITLE
与 umi 综合使用会出现死循环的问题

### ISSUE THREAD

**Issue by MinJieLiu** [CJY0208/react-activation#27]
这个问题在简单的场景下近乎不会出现，

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/umi-activation-demo-with-tab-zxz84)

对应的 github https://github.com/MinJieLiu/umi-activation-demo

## 复现

1. 打开 `codesandbox` ，等待启动成功，并点击 `用户列表`
2. 修改 `src/pages/user-info/index.tsx` 

### 方式1：

3. 注释 `const { tableProps } = useAntdTable<Result, Item>(getTableData);` 这一行

### 方式2：

3. 移除容器 `<NormalSearchContainer />` 直接 return `<Table />` 
4. revert 刚才的修改

## 复现所需场景：

1. 在 umi 中开启 `dynamicImport` 
1. 保持 `HMR ` 为开启状态
1. 在过程中设置过 `dispatch` 加载数据的请求

开发过程中很容易出问题，浏览器直接卡死，不好调试。看网络请求猜测可能是 `dynamicImport` 无限重复装载了。

目前暂时规避的办法可以关闭 `HMR` 或关闭 `dynamicImport`。

**Comment by MinJieLiu** [comment]
我将 `KeepAlive` 移入 `dynamicImport` 内部，暂时规避了此问题

https://github.com/MinJieLiu/umi-plugin-activation-route-modify/blob/master/src/index.ts#L60

**Comment by MinJieLiu** [comment]
我给的 KeepAlive 一个id  为 url 路径。调整到 dynamicImport 内部后，切换页面，id 一致，匹配不到之前的缓存，他会用同样的 id 生成一份新的缓存

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/72051946-28284b00-32ff-11ea-9d5b-1aab8171968e.png)

**Comment by CJY0208** [comment]
没看懂... `dynamicImport` 是干啥的？

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/72055627-244bf700-3306-11ea-8d3f-2d37766f125d.png)
j就是处理动态 import 过来的组件

**Comment by MinJieLiu** [comment]
目前情况就是每次走动态路由，import 后的组件都给他生成了不同的 key

**Comment by CJY0208** [comment]
KeepAlive 确定 id 值是根据它的渲染路径，有可能每次 dynamicImport 生成的组件没有被 _ka 标记所以查不到它的路径值，当作了每次都在变化

具体情况还要再查一下，你的 codesanbox 似乎没法实现 keep-alive 功能，我没有能细看

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/umi-activation-demo 这个是改过后的代码

我看到 _ka 值是一样的

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/72057602-9c67ec00-3309-11ea-9f38-246092add73b.png)

**Comment by MinJieLiu** [comment]
codesandbox 的页签上有个点，点一下就固定了，就能 keepAlive

**Comment by CJY0208** [comment]
_ka 会是一样的，这是在构建时确定的，但 id 会根据渲染路径来确定

a[_ka=1] -> div[_ka=3] -> DynamicComponent[_ka=?可能变动?] -> ... -> KeepAlive[_ka=m5GI21]

**Comment by CJY0208** [comment]
或者说 DynamicComponent 的 _ka 没有标记到，所以 KeepAlive 认为路径发生了变化

**Comment by MinJieLiu** [comment]
https://github.com/dvajs/dva/blob/master/packages/dva/src/dynamic.js
DynamicComponent 没有节点，感觉 import 进来的组件每次渲染都认为是新的节点那个意思

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/umi-plugin-activation-route-modify
用这个库更好调试一点

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/72127249-ff10c480-33a9-11ea-8962-af07bbe10d6d.png)
我在 KeepAlive 外层加了个 div ，没被_ka 标记，怀疑是这个原因

**Comment by MinJieLiu** [comment]
找到原因了😂

https://github.com/CJY0208/react-activation/blob/master/src/core/getKeyByFiberNode.js#L26

```js
get(node, 'type.$$typeof', node.type)
```
返回是一个 `Function`。我在某个地方使用了高阶组件，每次 import 后的返回的是一个新 `Function`。

这就导致了从 `getKey2Id` 获取不到原先存储的 Map key。

toString() 一下即可复现。

**Comment by CJY0208** [comment]
这个原因确实比较藏得有点深，一般来说 Activation 不应该支持这样的场景（因为渲染节点是精确区分对待的，包括引用），但这也是常见的使用方式，开发者也很难定位

有好的建议吗？

**Comment by MinJieLiu** [comment]
那就要避免这样的写法了

```js
export default Component => props => {
  return (
    <KeepAlive>
      <Component {...props} />
    </KeepAlive>
  );
};
```

要写成

```js
function createKeepAliveFunc() {
  let Component;

  function KeepAliveWrap(props) {
    return (
      <KeepAlive>
        <Component {...props} />
      </KeepAlive>
    );
  }

  return NextComponent => {
    Component = NextComponent;
    return KeepAliveWrap;
  };
}

export default createKeepAliveFunc();
```
