### ISSUE TITLE
url发生改变，页面还是缓存的第一次页面的数据

### ISSUE THREAD

**Issue by anbeicat** [CJY0208/react-activation#270]
从http://localhost:8000/orderManagement/sellPlanAgent/details/jh20230510509983变成http://localhost:8000/orderManagement/sellPlanAgent/details/jh20230510361061时，页面还是缓存的第一次的页面，没有重新刷新，name属性没有生效

**Comment by CJY0208** [comment]
看看这个
https://github.com/CJY0208/react-activation/blob/master/README_CN.md#%E5%A4%9A%E4%BB%BD%E7%BC%93%E5%AD%98

**Comment by anbeicat** [comment]
就是想要做成只会出现一个tabs标签，但是数据是最新url的数据，但现在这个name获取的是第一次的数据
