### ISSUE TITLE
react-router-v6中如何使用AliveScope

### ISSUE THREAD

**Issue by huangchucai** [CJY0208/react-activation#271]
如下代码片段
```javascript
const router = createBrowserRouter([
  {
    path: "/",
    errorElement: <ErrorPage/>,
    element: <KeepAlive  cacheKey="UNIQUE_ID"><App/></KeepAlive>,
    loader: appLoader,
    },
  },
  {
    path: "/detail",
    element: <Detail/>
  }
]);
ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
    <AliveScope>
      <RouterProvider router={router}/>
    </AliveScope>
)
```
我如果按照这样写，又违背了如下的建议：

>Note: When used with react-router or react-redux, you need to place <AliveScope> 
inside <Router> or <Provider>

那请问一下，如果正确的包裹呢？能不能提供一个建议例子

**Comment by CJY0208** [comment]
react-router 6  应该有 RouterProvider 和 routeConfig 分开配置的方式吧，这样可以让 AliveScope 放置到 RouterProvider 内部，具体需要看 router 6 的文档了

**Comment by huangchucai** [comment]
查看了文档，新版的配置好像并没有提供分开的方式，如果这样使用有什么影响吗？
```javascript
  <AliveScope>
    <RouterProvider router={router}/>
  </AliveScope>
```

**Comment by huangchucai** [comment]
BrowserRouter 已经不在推荐使用，目前官方推荐的使用方式是
```
[createBrowserRouter]
[createMemoryRouter]
[createHashRouter]
[createStaticRouter]
```
https://reactrouter.com/en/main/routers/picking-a-router

**Comment by CJY0208** [comment]
没问题就行，有问题的话再看怎么改吧

我没有在使用 createBrowserRouter，无法提供最佳实践

**Comment by huangchucai** [comment]
好的，感谢回复~正常感觉应该是包裹在里面的，但是神奇的是我包裹在外面也没有异常

**Comment by huangchucai** [comment]
> 那就使用 element layouts 的方式来挂载 AliveScope 吧
> 
> ```js
> const routes = [
>   {
>     path: '/',
>     element: (
>       <AliveScope><Outlets /></AliveScope>
>     ),
>     children: ...
>   }
> ]
> ```

这种方式我尝试了一下，是不可以的
