### ISSUE TITLE
第一次页面缓存失败

### ISSUE THREAD

**Issue by anbeicat** [CJY0208/react-activation#272]
我从菜单栏进去a页面，再进去b页面，然后在b页面填写了一下内容，这个时候进入a页面点击搜索，再进去b页面，发现b页面填写的内容被清空了，内容没有缓存成功。但如果之后再重复这样的操作就不会有问题，b页面内容会成功缓存下来。请问一下这个是什么问题引起的呢

**Comment by CJY0208** [comment]
如果使用了 react 严格模式，需要关掉

**Comment by anbeicat** [comment]
没有使用
