### ISSUE TITLE
route v6  lazy

### ISSUE THREAD

**Issue by ALongLi** [CJY0208/react-activation#273]
https://reactrouter.com/en/main/route/lazy

![image](https://github.com/CJY0208/react-activation/assets/20749911/b18df299-895a-4266-9a82-34542582aaa0)

这种lazy的应该怎么写

**Comment by CJY0208** [comment]
不太明白你的问题，这似乎不是 activation 出了什么错误，只是你没有找到在 router6 中使用它的方式
