### ISSUE TITLE
如何控制cachingNodes添加的顺序

### ISSUE THREAD

**Issue by anbeicat** [CJY0208/react-activation#274]
现在cachingNodes是每一个缓存节点直接push在后面，可以将新打开的节点加在上一个缓存节点的后面吗，比如我有abc三个页面，我现在在b页面，然后进入d页面，这个时候getCachingNodes应该返给我abdc

**Comment by anbeicat** [comment]
@CJY0208

**Comment by CJY0208** [comment]
这不是 activation 应该处理的功能，如果你需要依据 cachingNodes 的来得知哪个节点处于缓存中，而顺序方面的事情，你可以在自己的业务逻辑中维护
