### ISSUE TITLE
我不能在history.block（）里实时获取到getCachingNodes()的值

### ISSUE THREAD

**Issue by anbeicat** [CJY0208/react-activation#275]
我想要在history.block中实时获取getCachingNodes的值，但每次获取的都不包含当前页面的缓存节点

**Comment by CJY0208** [comment]
只有节点真正被缓存（对应不使用 KeepAlive 时卸载完成之后）的时候，才会出现在 cachingNodes 中

不确定你的做法想要达成什么效果，activation 可能无法完成你想要的功能，可能需要自行实现
