### ISSUE TITLE
在缓存（使用react-virtualized库构建的虚拟列表）列表时，若多个页面来回切换，列表会重叠。

### ISSUE THREAD

**Issue by biology-w** [CJY0208/react-activation#28]
存在pageA, pageB两个页面，每个页面初始化时从服务器拉取数据，展示列表（使用react-virtualized库构建的虚拟列表）。现在有A,B两个按钮可点击分别跳转到pageA, pageB页面。若此时，快速连续在两个页面之间来回切换，等到数据返回后，展示列表时，列表样式发生重叠。

**Comment by CJY0208** [comment]
Hello，能否提供一个可复现的 demo 呢？

**Comment by CJY0208** [comment]
虚拟列表需求，依照 react-virtualized 作者[建议](https://github.com/bvaughn/react-virtualized/blob/master/README.md#a-word-about-react-window)，尝试使用 react-window 替代，也可与 react-activation 正常协作，参考[此处 demo](https://codesandbox.io/s/keguanbideyifangwenluyou-tab-shilikeanluyoucanshufenduofenhuancun-jyrge)

或者使用 @umijs/hooks 中的 [useVirtualList](https://hooks.umijs.org/zh-CN/hooks/ui/use-virtual-list) 亦可实现

**Comment by CJY0208** [comment]
暂时缺少反馈，closed

**Comment by shuyanzi** [comment]
你解决了吗？我这边也有这个问题，但是不是必现的，很难查什么问题
