### ISSUE TITLE
在KeepAlive 中无法获取元素的宽高信息

### ISSUE THREAD

**Issue by Dreamcreative** [CJY0208/react-activation#283]
<img width="932" alt="image" src="https://github.com/CJY0208/react-activation/assets/23378455/c2ee2a78-7745-44f9-b665-51f8a7621a96">

```
const Com = () => {
  useLayoutEffect(() => {
    const rt = document.querySelector(".com")?.getBoundingClientRect();
    console.log(rt);
  }, []);
  return <div className="com">获取元素高度</div>;
};
const AliveRecord = props => (
  <KeepAlive>
    <Com {...props} />
  </KeepAlive>
);
```

**Comment by youngBrain1893** [comment]
这个是不是 `.com` 元素没获取到

**Comment by CJY0208** [comment]
参考 https://github.com/CJY0208/react-activation/blob/master/README_CN.md#breaking-change-%E7%94%B1%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86%E5%BC%95%E5%8F%91%E7%9A%84%E9%A2%9D%E5%A4%96%E9%97%AE%E9%A2%98 此处第 1 点
