### ISSUE TITLE
有getCachingNodes()方法，有没有办法setCachingNodes?

### ISSUE THREAD

**Issue by yan919** [CJY0208/react-activation#284]
有这样的需求，想把nodes缓存到storage里面，当用户刷新后从storage里面获取nodes，然后直接写入到cachingNodes里，实现刷新后页面也保留

**Comment by CJY0208** [comment]
没有这个可能性，keepalive 是无法在刷新页面后仍然保存的，需要你自己配合状态管理工具如 redux 的 persist 功能实现

**Comment by 765477020** [comment]
hi，你有找到解决方法吗，产品经理也给我提了类似功能，刷新后，也要有keepalive功能
