### ISSUE TITLE
You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by panStart** [CJY0208/react-activation#288]
组件库使用的抽屉弹窗，打开后偶现此报错，大佬救命🆘

**Comment by CJY0208** [comment]
![image](https://github.com/CJY0208/react-activation/assets/18415774/313e6478-5fd0-4607-a528-8930605ebf73)
https://github.com/CJY0208/react-activation/blob/master/README_CN.md#3-%E5%9C%A8%E4%B8%8D%E4%BC%9A%E8%A2%AB%E9%94%80%E6%AF%81%E7%9A%84%E4%BD%8D%E7%BD%AE%E6%94%BE%E7%BD%AE-alivescope-%E5%A4%96%E5%B1%82%E4%B8%80%E8%88%AC%E4%B8%BA%E5%BA%94%E7%94%A8%E5%85%A5%E5%8F%A3%E5%A4%84
