### ISSUE TITLE
手动清除浏览器缓存后的诡异现象

### ISSUE THREAD

**Issue by Symous** [CJY0208/react-activation#292]
1. 有一个页面Login，还有一个页面List，被KeepAlive包裹；
2. 使用when属性来决定List页面是否缓存，这里强制写为false；
3. 在不手动清除浏览器缓存的情况下一切正常，但是当打开浏览器设置清除缓存后，刷新页面，回退到Login页面，登录再次进入到List页面，发现List页面居然被缓存了？？？还执行了componentDidActivate方法，着实震惊了，因为我使用when=false强制关闭了该页面的缓存，按道理来说它是不应该被缓存的，即使被缓存了，清除浏览器的缓存+刷新页面后，它的缓存应当也被清空才对，更诡异的是，即使我调用了clear方法，也同样没办法清空这个不该存在的缓存；

百思不得其解，望作者 @CJY0208  能提供一下解决思路，谢谢！

**Comment by CJY0208** [comment]
听起来确实有点神奇，能给一个最简 demo 示例吗？我看看可能是啥原因
