### ISSUE TITLE
怎么区分PUSH的时候不用缓存，POP的时候使用缓存啊。我现在PUSH的时候也是用的缓存数据

### ISSUE THREAD

**Issue by txqsimon** [CJY0208/react-activation#31]

**Comment by CJY0208** [comment]
可以参考这个示例
![image](https://user-images.githubusercontent.com/18415774/75320400-8c03d480-58a9-11ea-8627-09d8c153cc7d.png)

**Comment by txqsimon** [comment]
解决啦，谢谢
