### ISSUE TITLE
umi使用KeepAlive包裹后 使用useIntl()报错

### ISSUE THREAD

**Issue by Versatileyouth** [CJY0208/react-activation#311]
![WechatIMG117](https://github.com/CJY0208/react-activation/assets/167152747/b1fc62fb-f66f-41b1-adfb-2e94e3197224)
<img width="846" alt="image" src="https://github.com/CJY0208/react-activation/assets/167152747/a0b2a586-7ea1-4d41-ae77-f63e6a1b0ed8">

**Comment by Versatileyouth** [comment]
umi版本："umi": "^4.0.88",

**Comment by Versatileyouth** [comment]
已解决！

**Comment by CJY0208** [comment]
是上述方案生效了嘛

**Comment by Versatileyouth** [comment]
生效了 是react版本导致的吗，还是umi4 在umi3中使用没出现这种问题

**Comment by CJY0208** [comment]
是的，和 react 版本有关系，是上下文断层的问题，16+ 中可以自动修复，17、18 需要手动修复
