### ISSUE TITLE
从一个缓存页面到另外一个缓存页面，再切换回来，第一个缓存页面失效

### ISSUE THREAD

**Issue by redwolf1996** [CJY0208/react-activation#314]
缓存首页，从首页进入第二个页面，如果第二个页面也是用keepalive 包裹的那么此时切换到第一个页面，第一个页面的缓存失效，如果第二个页面没有缓存，那么第一个页面是缓存的， 请问这个缓存只能同时对一个路由生效吗

**Comment by CJY0208** [comment]
你可能需要这个 [同一个位置的多份缓存](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#%E5%A4%9A%E4%BB%BD%E7%BC%93%E5%AD%98)
