### ISSUE TITLE
触发了useLayoutEect和comDidMount 导致问题

### ISSUE THREAD

**Issue by lsy934127847** [CJY0208/react-activation#320]
在使用antd 时， 
缓存激活时触发了  componentDidMount 钩子，导致数据被重置了。
![image](https://github.com/user-attachments/assets/67de55ff-cefb-440f-966a-fd15ded1823a)

问题： react-activation 为何会触发 useLayoutEffect 和  componentDidMount

**Comment by CJY0208** [comment]
related: https://github.com/CJY0208/react-activation/issues/225#issuecomment-1311136388

**Comment by lsy934127847** [comment]
在react18中， 我点的特别快，不会触发useLayoutEffect 点的慢一点就触发了， 这是什么原因？ 
![20240717160520](https://github.com/user-attachments/assets/0317846b-eab7-4433-8f4a-d04b99e86b24)
这样导致antd 的 initvalue 不能使用， 会触发

**Comment by CJY0208** [comment]
因为keep alive的freeze行为会有一定延迟
，具体解决方案看我关联的链接

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月17日(周三) 下午4:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [CJY0208/react-activation] 触发了useLayoutEect和comDidMount 导致问题 (Issue #320)




 
在react18中， 我点的特别快，不会触发useLayoutEffect 点的慢一点就触发了， 这是什么原因？
 20240717160520.gif (view on web)
 这样导致antd 的 initvalue 不能使用， 会触发

**Comment by lsy934127847** [comment]
主要是为何会触发 useLayoutEffect 和 componentDidMount 不会触发 useEffect？ 有一个很好的解释吗

**Comment by CJY0208** [comment]
related: https://github.com/CJY0208/react-activation/issues/225#issuecomment-1311136388
![image](https://github.com/user-attachments/assets/ae5e5062-4c49-42ed-9f75-43aafaaf4603)

**Comment by lsy934127847** [comment]
如果 用了 这个 autoFreeze={false}  性能影响大吗？在react18中加了这个可以解决触发layouteffect的问题， react16.14还有点问题

**Comment by lsy934127847** [comment]
那个initvalue 不要写在form.item 上 写着外层的form上， 因为外层的initvalue 不是走的生命周期 
![image](https://github.com/user-attachments/assets/1b2b79f6-d8c3-472f-9872-3c45452e4e40)
