### ISSUE TITLE
KeepAlive  会渲染成 div.ka-content  div.ka-wrapper, 添加dom层级是实现 keep-alive 必须的吗? 

### ISSUE THREAD

**Issue by vaynevayne** [CJY0208/react-activation#323]
添加dom层级会带来很多样式上的问题, 想知道这两个dom是否是必须的?

**Comment by vaynevayne** [comment]
`<KeepAlive /> ` 能否添加 className 属性,以支持修改这两个dom对整个dom树的破坏

**Comment by CJY0208** [comment]
v0.13.0 增加了 wrapperProps 和 contentProps 来控制两个层级的样式与其他行为
