### ISSUE TITLE
Invariant Violation problem

### ISSUE THREAD

**Issue by khanbaba** [CJY0208/react-activation#37]
Hi,
When i use KeepAlive and AliveScope, the following error occures in production (not development):
Invariant Violation: Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Are you sure that you have returned correctly in render function?

my app.js render:
```js
render() {
return (
      <AliveScope>
        {loading && <div id="rainbow-progress-bar"></div>}
        <Component {...modifiedPageProps} />
        <BottomNavigation />
        <InstallWebApp
          show={showInstallDialog}
          deferredPrompt={deferredPrompt}
        />
      </AliveScope>
    )
}
```
and i have KeepAlive in components like below:
```js
render() {
    const {
      query: { random_key }
    } = this.props
    return (
      <KeepAlive id={random_key} name={`p/${random_key}`}>
        <ScrollPosition>
          <Product {...this.props} />
        </ScrollPosition>
      </KeepAlive>
    )
  }
```

**Comment by CJY0208** [comment]
Can you provide complete error stack information, and the versions of react and react-activation in use?

**Comment by khanbaba** [comment]
react version: 16.4.0
nextjs version: 8.0.3
react-activation: 0.4.3

Invariant Violation: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=e for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:722290
    at i (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:722393)
    at http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:773909
    at ka (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:780757)
    at Sa (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:784964)
    at Ta (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:784662)
    at Fa (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:788496)
    at Wi (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:812540)
    at qi (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:812924)
    at Sc (http://localhost:3001/_next/static/chunks/commons.2c6ea637a085644cc7e1.js:1:819811)

**Comment by khanbaba** [comment]
I have found that react-activation version 0.4.2 is ok but after that version like 0.4.3 and 0.5.0 the problem exists.

**Comment by CJY0208** [comment]
There are known issues with version 0.4.3, and 0.5.0 should be fixed. Is it possible that it is a dependency or a built cache? Try removing node_modules and reinstalling the dependencies will solve the problem?

**Comment by khanbaba** [comment]
No I have tried this solution but not worked.

**Comment by CJY0208** [comment]
Lack of feedback, it should be fixed, closed
