### ISSUE TITLE
在switch中无法实现缓存

### ISSUE THREAD

**Issue by ainuo5213** [CJY0208/react-activation#38]
在switch中使用该组件，无法实现之前页面数据的缓存

**Comment by CJY0208** [comment]
目前是如何使用的？我自己项目中也有场景，功能是 OK 的

**Comment by ainuo5213** [comment]
我是这样用的
ReactDom.render:
<BrowserRouter&gt;
&nbsp; &nbsp; &nbsp;<AliveScope&gt;
&nbsp; &nbsp; &nbsp; <Contaienr /&gt;
&nbsp; &nbsp; &nbsp;</AliveScope&gt;
</BrowserRouter&gt;


Container含有四个组件，可以通过tab进行切换
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CJY"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 中午11:46
收件人:&nbsp;"CJY0208/react-activation"<react-activation@noreply.github.com&gt;;
抄送:&nbsp;"All We Know"<1660998482@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CJY0208/react-activation] 在switch中无法实现缓存 (#38)





 
目前是如何使用的？我自己项目中也有场景，功能是 OK 的

**Comment by CJY0208** [comment]
需要更详细一些的说明，有没有报错啥的，使用的版本号是啥？

**Comment by ainuo5213** [comment]
没报错信息。我目前的rect版本是16.8，router是最新的（有hook的）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CJY"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 中午11:56
收件人:&nbsp;"CJY0208/react-activation"<react-activation@noreply.github.com&gt;;
抄送:&nbsp;"All We Know"<1660998482@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CJY0208/react-activation] 在switch中无法实现缓存 (#38)





 
需要更详细一些的说明，有没有报错啥的，使用的版本号是啥？

**Comment by youchaojun** [comment]
我也遇到同样的问题
<Router>
      <AliveScope>
        <Listen />
        {/* <Switch> */}
          <Route exact path="/">
            <KeepAlive name="Home">
              <Home />
            </KeepAlive>
          </Route>
          <Route exact path="/list">
            <KeepAlive name="List">
              <List />
            </KeepAlive>
          </Route>
          <Route exact path="/item">
            <KeepAlive name="Item">
              <Item />
            </KeepAlive>
          </Route>
          <Route exact path="/home/detail">
            <KeepAlive name="HomeDetail">
              <HomeDetail />
            </KeepAlive>
          </Route>
        {/* </Switch> */}
      </AliveScope>
    </Router>
外边有redux包裹
有Switch就不能换成，注销就可以缓存，
"react": "^16.13.1",
"react-router-dom": "^5.2.0",

**Comment by youchaojun** [comment]
我也遇到同样的问题
`<Router>
      <AliveScope>
        <Listen />
        {/* <Switch> */}
          <Route exact path="/">
            <KeepAlive name="Home">
              <Home />
            </KeepAlive>
          </Route>
          <Route exact path="/list">
            <KeepAlive name="List">
              <List />
            </KeepAlive>
          </Route>
          <Route exact path="/item">
            <KeepAlive name="Item">
              <Item />
            </KeepAlive>
          </Route>
          <Route exact path="/home/detail">
            <KeepAlive name="HomeDetail">
              <HomeDetail />
            </KeepAlive>
          </Route>
        {/* </Switch> */}
      </AliveScope>
    </Router>`

外边有redux包裹
有Switch就不能换成，注销就可以缓存，
"react": "^16.13.1",
"react-router-dom": "^5.2.0",

**Comment by CJY0208** [comment]
看了一下示例，应该可以生效才对，能否制作线上 demo ？我自个儿项目这样用都是 OK 的，是否是对缓存的理解不一致呢

**Comment by youchaojun** [comment]
[https://github.com/youchaojun/react-router-keep-live.git](demo我上传在这里了，请你帮忙看看，谢谢)
我的缓存是用的input看能不能保存输入的内容

**Comment by youchaojun** [comment]
我把demo上传在上边这个地址了，请你帮忙看看呢，谢谢

**Comment by CJY0208** [comment]
OK，找到原因了，是 react-activation 的原因，发了 0.5.5 修复版本

另外，demo 中的 .babelrc 是无效的，create-react-app 不会使用它，需要使用 react-app-rewired 来使其生效

建议使用 [customize-cra](https://github.com/arackaf/customize-cra)

启用 babelrc 后，更新 0.5.5 版本，试试是否能解决问题~

**Comment by youchaojun** [comment]
好的，谢谢，我看所有的issues,我看到你推荐用react-router-cache-route，我想问问这两个有什么区别。两个都在维护么

**Comment by CJY0208** [comment]
都在维护，推荐使用 cache-route 是因为它的实现方式不具备破坏性，本本分分按照 react 逻辑来走，但 activation 不按常理，有破坏性

但灵活性和功能性上相较于 activation 有缺失，对复杂场景处理比较吃力，例如嵌套路由，不支持路由动画等

**Comment by youchaojun** [comment]
哦哦，明白了，十分感谢

**Comment by CJY0208** [comment]
It should be fixed now, closed
