### ISSUE TITLE
本地正常运行，build后代码报错

### ISSUE THREAD

**Issue by LinXiudong** [CJY0208/react-activation#39]
报错 react-dom.production.min.js:5058 Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=e for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by CJY0208** [comment]
新版本增加了 core-js 功能垫片，或许能修复不同设备或浏览器上的兼容性问题，可以试试

**Comment by CJY0208** [comment]
缺少反馈，closed
