### ISSUE TITLE
如何在create-react-app中配置babel

### ISSUE THREAD

**Issue by PossibleMaybe** [CJY0208/react-activation#4]

**Comment by CJY0208** [comment]
可参考 https://codesandbox.io/s/affectionate-beaver-solkt，核心是使用 [react-app-rewired](https://github.com/timarney/react-app-rewired/) 和[customize-cra](https://github.com/arackaf/customize-cra) 在没有使用 `eject` 命令时，对 `create-react-app` 做拓展

**Comment by PossibleMaybe** [comment]
> 可参考 https://codesandbox.io/s/affectionate-beaver-solkt
> 
> 核心是使用 [react-app-rewired](https://github.com/timarney/react-app-rewired/) 和 [customize-cra](https://github.com/arackaf/customize-cra) 在没有使用 `eject` 命令时，对 `create-react-app` 做拓展

是run eject之后

**Comment by CJY0208** [comment]
run eject 后和其他 webpack 工程一样的，修改 .babelrc 就好，或者其他类似的 babel 配置文件，具体需要参考 create-react-app 文档，或者 webpack、babel 文档，结合 eject 后的目录结构去做了
