### ISSUE TITLE
ios10的系统打开页面白屏

### ISSUE THREAD

**Issue by yinran100** [CJY0208/react-activation#41]
用xcode可以模拟复现，原因正在的定位

**Comment by yinran100** [comment]
初步确定是rollup打包的问题，需要更新相关版本重新打包一版哦

**Comment by CJY0208** [comment]
Hello，具体是啥原因呀

**Comment by yinran100** [comment]
没有兼容低版本浏览器需要用@babel/polyfill，经验证只需要引入加上@babel/polyfill，就可以了,我直接改的node_module里的这一句代码就可以了；依赖中添加
`"@babel/polyfill": "^7.6.0"`
代码如下，/index.js
`'use strict';
require('@babel/polyfill')
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./lib/index.min.js');
} else {
  module.exports = require('./lib/index.js');
}
`

**Comment by yinran100** [comment]
希望尽快更新哦

**Comment by yinran100** [comment]
顺便推荐作者附加一个装饰器，可以直接给组件keep-alive，而且注入生命周期函数
```javascript
export const createKeepAlive = compose(
  Com => props => <KeepAlive >
    <Com {...props}/>
  </KeepAlive>,
  withActivation
)
```
同时，想知道为什么作者不解决一下，给 `<KeepAlive>` 的组件内部其他组件全部注入生命周期函数

**Comment by CJY0208** [comment]
1. polyfill 一般不由库提供，库仅提供功能，所以兼容性问题可能需要你在项目中引入垫片啦

2. 已经提供了足够的功能，装饰器带有一定的业务封装性质，使用场景不广泛所以未提供

3. 两个原因，一是实现困难，因为需要探测到所有 KeepAlive 内部组件，二是缺乏实际场景，一般来说没有必要全部注入，选择性注入已经足够了，如果期望全部注入，可以参考 2 在项目中建立自有封装来实现

**Comment by yinran100** [comment]
我查了些资料，我看一般项目不处理node_module里的polyfill吧，我的项目对自己的代码有做polyfill处理，但是第三方的并没有，所以想知道该怎么解决好一些

**Comment by CJY0208** [comment]
polyfill 引入后应该会对整体运行环境都进行垫高处理，node_modules 在内的库也会受益，可能的原因是项目中的 polyfill 是针对性的，仅针对非 node_modules 内的代码进行功能分析并导入对应垫片，所以忽略了 node_modules 中的功能

可能的解决方案有二

1. 全量引入 polyfill
2. polyfill 功能分析需要覆盖 node_modules

**Comment by yinran100** [comment]
项目如果全量引入polyfill，打包后代码会增大一百多k，之前的建议方案也会这样，所以并不是合理的方案；后来经过验证，建议作者可以尝试更改@babel/env的配置，其他都不变，也可以达兼容效果，打包后的代码index.min.js，也只增加了3k左右的大小，可以考虑一下
```javascript
  '@babel/env',
      {
        modules: false,
        useBuiltIns: 'usage',
        corejs: 3
      }
```

**Comment by yinran100** [comment]
项目如果全量引入polyfill，打包后代码会增大一百多k，之前的建议方案也会这样，所以并不是合理的方案；后来经过验证，建议作者可以尝试更改babel.config.js里的@babel/env的配置，其他都不变，也可以达兼容效果，打包后的代码index.min.js，也只增加了3k左右的大小，可以考虑一下
```javascript
  '@babel/env',
      {
        modules: false,
        useBuiltIns: 'usage',
        corejs: 3
      }
```

**Comment by CJY0208** [comment]
> 项目如果全量引入polyfill，打包后代码会增大一百多k，之前的建议方案也会这样，所以并不是合理的方案；后来经过验证，建议作者可以尝试更改babel.config.js里的@babel/env的配置，其他都不变，也可以达兼容效果，打包后的代码index.min.js，也只增加了3k左右的大小，可以考虑一下
> 
> ```js
>   '@babel/env',
>       {
>         modules: false,
>         useBuiltIns: 'usage',
>         corejs: 3
>       }
> ```

OK，会考虑

**Comment by CJY0208** [comment]
新版本增加了 core-js 功能垫片，或许能修复不同设备或浏览器上的兼容性问题，可以试试
