### ISSUE TITLE
被包裹的容器高度 ka-wrapper  ka-content 是0 

### ISSUE THREAD

**Issue by lovesL** [CJY0208/react-activation#42]
被包裹的容器高度 ka-wrapper  ka-content 是0   我加了高度后页面似乎。。。蹦了 网页空白 关也关不掉

**Comment by CJY0208** [comment]
如何增加的高度，页面是否有报错？

**Comment by CJY0208** [comment]
私下沟通后，确认为与高德地图结合使用过程中的未知问题，与库无关
