### ISSUE TITLE
在Edge浏览器内无法运行，报错如下

### ISSUE THREAD

**Issue by jiaozhouzhou** [CJY0208/react-activation#44]
The above error occurred in the <Keeper> component:
in Keeper (created by AliveScope)
in div (created by AliveScope)
in AliveScope (at pages/index.js:54)
in PersistGate (at pages/index.js:53)
in Provider (at pages/index.js:52)
in App (created by ForwardRef(LoadableComponent))
in ForwardRef(LoadableComponent) (created by Context.Consumer)
in Route (created by RouterComponent)
in Switch (created by RouterComponent)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
index.js (1,1)

**Comment by CJY0208** [comment]
新版本增加了 core-js 功能垫片，或许能修复不同设备或浏览器上的兼容性问题，可以试试

**Comment by CJY0208** [comment]
缺少反馈，closed
