### ISSUE TITLE
用了Link就报错  this.props.match.params也报错

### ISSUE THREAD

**Issue by ladyruo** [CJY0208/react-activation#45]
Link报错是: Invariant failed: You should not use <Link> outside a <Router>
    at invariant (tiny-invariant.esm.js:13)

**Comment by ladyruo** [comment]
Link报错是: Invariant failed: You should not use outside a
at invariant (tiny-invariant.esm.js:13)

**Comment by CJY0208** [comment]
需要检查你的组件是否处于 Router 内部

**Comment by CJY0208** [comment]
暂时缺少反馈，closed
