### ISSUE TITLE
react 16.13.1 会有警告

### ISSUE THREAD

**Issue by viewweiwu** [CJY0208/react-activation#46]
可能是因为项目使用了 componentDidMount，看了下项目有几处用到了这个，是否考虑升级一下。

具体警告如下：
react-dom.development.js:88 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: LoadableComponent

**Comment by CJY0208** [comment]
和 react-activation 无关吧，是业务当中一个叫做 `LoadableComponent` 的组件，内部使用了 `componentWillMount` 所致的

**Comment by viewweiwu** [comment]
哦！不好意思，我提错地方了，我两个一起用的，弄错了，我关闭一下。
