### ISSUE TITLE
在安卓的Chrome版本低于44的浏览器里会报错白屏

### ISSUE THREAD

**Issue by yinran100** [CJY0208/react-activation#47]
我这边的用户统计到的报错都是这些安卓老机器，可以关注一下
Invariant Violation","message":"Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

即无限循环渲染的问题
`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**Comment by CJY0208** [comment]
新版本增加了 core-js 功能垫片，或许能修复老机器上的问题，可以试试
