### ISSUE TITLE
路由是怎么个配置

### ISSUE THREAD

**Issue by robotgoto** [CJY0208/react-activation#5]
看了Demo是组件缓存， 那么路由是怎么个配置。

**Comment by CJY0208** [comment]
看看一下例子是否有帮助

## 更多复杂示例

- [可关闭的路由 tabs 示例](https://codesandbox.io/s/keguanbideyifangwenluyou-tab-shilikeanluyoucanshufenduofenhuancun-ewycx)
- [使用路由转场动画](https://codesandbox.io/s/luyouzhuanchangdonghuashili-jdhq1)

**Comment by robotgoto** [comment]
@CJY0208 麻烦问下这个 name="List" 是个什么东西，是随便定义的吗？

**Comment by CJY0208** [comment]
> @CJY0208 麻烦问下这个 name="List" 是个什么东西，是随便定义的吗？

一般来说 name 不需要定义，用在手动控制缓存的时候，你想卸载一个指定的 KeepAlive，就需要给定一个名字，可参考[此处文档](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#%E6%89%8B%E5%8A%A8%E6%8E%A7%E5%88%B6%E7%BC%93%E5%AD%98)
