### ISSUE TITLE
关闭当前tab页面，无法清除当前的页的缓存

### ISSUE THREAD

**Issue by YoutheEnd** [CJY0208/react-activation#50]

**Comment by CJY0208** [comment]
请问是在 KeepAlive 激活期间使用 drop 相关动作吗？

react-activation 忽略了这个行为，因为这被认为不属于 “drop” 动作而是 "refresh"

此场景下需要使用 refresh、refreshScope 而不是 drop

如果是多 tabs 标签，需要是关闭后回到上一个路由或者标签的需求场景，那需要在进行路由切换，触发 KeepAlive 的卸载后再调用 drop 函数

原因是 react-activation 被设计为与路由系统无关，不会主动猜测路由行为且进行路由引导

**Comment by YoutheEnd** [comment]
您好， 谢谢。
触发 KeepAlive 的卸载是我在路由切换后自动检测的吗？ 我现在在路由跳转的后面执行drop方法，发现缓存还在

**Comment by c1184405532** [comment]
老哥 同问题 如果不能drop 而是refresh的话 那么我进入列表页 此时列表页请求数据然后缓存页面，进入详情页，返回列表页 此时列表页状态缓存正确，此时返回首页 我使用refresh 这个时候我已经进入首页了 但是列表页中的生命周期依然会执行 从而导致请求数据，然后触发请求loading 页面上会显示一个数据加载中 影响用户体验，请问这个问题应该怎么避免呢？如果不能卸载当前路由的话。

**Comment by CJY0208** [comment]
> 您好， 谢谢。
> 触发 KeepAlive 的卸载是我在路由切换后自动检测的吗？ 我现在在路由跳转的后面执行drop方法，发现缓存还在

需要手动检测，可以参考 umi 的这个多 tabs demo
https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy

**Comment by YoutheEnd** [comment]
> > 您好， 谢谢。
> > 触发 KeepAlive 的卸载是我在路由切换后自动检测的吗？ 我现在在路由跳转的后面执行drop方法，发现缓存还在
> 
> 需要手动检测，可以参考 umi 的这个多 tabs demo
> https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy
> 
> @c1184405532 你的场景确实应该使用 drop，只是需要在路由离开，确认 KeepAlive 已经处于 unactivated 状态后才能执行 drop，也可以参考上述 demo

好的，谢谢

**Comment by CJY0208** [comment]
还可以尝试点击关闭时并不直接执行 drop ，而是进行带参数的路由跳转，例如
```js
history.push({
  pathname: '/another-route',
  state: {
   closeTab: '/current-tab'
  }
})
```

然后使用 KeepAlive 的 when 属性，自动处理路由参数，命中 closeCurrentTab 后返回 false 来达到关闭 tab 的效果

```jsx
<Route path="/some-path" render={props => (
  <KeepAlive when={() => {
    if (props.history.state.closeTab === "/some-path") {
      return false
    }

    return true
  }}>
     <YourComponent {...props} />
  </KeepAlive>
)} />
```

**Comment by YoutheEnd** [comment]
> 还可以尝试点击关闭时并不直接执行 drop ，而是进行带参数的路由跳转，例如
> 
> ```js
> history.push({
>   pathname: '/another-route',
>   state: {
>    closeTab: '/current-tab'
>   }
> })
> ```
> 
> 然后使用 KeepAlive 的 when 属性，自动处理路由参数，命中 closeCurrentTab 后返回 false 来达到关闭 tab 的效果
> 
> ```js-jsx
> <Route path="/some-path" render={props => (
>   <KeepAlive when={() => {
>     if (props.history.state.closeTab === "/some-path") {
>       return false
>     }
> 
>     return true
>   }}>
>      <YourComponent {...props} />
>   </KeepAlive>
> )} />
> ```

多谢多谢，我尝试一下。

**Comment by c1184405532** [comment]
老哥可以加下我qq吗 1184405532 我在useUnactivate中使用dropScope 清除了缓存 但是问题在我下一次从首页进入列表页面时，列表页面已经为空 连dom元素都没有了。加我qq我好截图给你看看效果和我的代码操作逻辑。
