### ISSUE TITLE
umiJS首次进入页面缓存无效，第二次进入页面缓存成功

### ISSUE THREAD

**Issue by tijin123** [CJY0208/react-activation#52]
首次进入a页面输入查询条件并查询接口数据，得到数据后切换到b页面，然后再切换回a页面，查询条件丢失，查询接口数据也没缓存下来。再次a页面输入查询条件并查询接口数据，得到数据后切换到b页面，再一次切换回a页面，查询条件和查询结果缓存成功。请问下第一次为什么会缓存失败呢？

**Comment by CJY0208** [comment]
后续：使用 umi-plugin-keep-alive 后问题解决
