### ISSUE TITLE
快速打开多个tabs页面，前几个页面虽然进缓存了，但是切换回来的时候并没有显示，是不是dom没加载完就切换导致的

### ISSUE THREAD

**Issue by YoutheEnd** [CJY0208/react-activation#55]
![image](https://user-images.githubusercontent.com/26157631/87908209-9dd45700-ca98-11ea-9cd2-a20102614df2.png)
![image](https://user-images.githubusercontent.com/26157631/87908276-b3498100-ca98-11ea-8682-3ae9d06803e4.png)

**Comment by YoutheEnd** [comment]
![image](https://user-images.githubusercontent.com/26157631/87912807-9618b080-caa0-11ea-87cc-aef7a80c97a2.png)

**Comment by CJY0208** [comment]
是使用了 KeepAlive 内部的 dom 节点吗？比如按 id 查找 className="GWT" 的元素，然后用来做一些其他的事情

**Comment by YoutheEnd** [comment]
> 是使用了 KeepAlive 内部的 dom 节点吗？比如按 id 查找 className="GWT" 的元素，然后用来做一些其他的事情

您好，是根据当前页面的props.location.pathname去调用接口加载dom

**Comment by CJY0208** [comment]
猜测是由于 KeepAlive 实现方式所致的 [Breaking change(1)](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#breaking-change-%E7%94%B1%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86%E5%BC%95%E5%8F%91%E7%9A%84%E9%A2%9D%E5%A4%96%E9%97%AE%E9%A2%98) 引起的，KeepAlive 内部的 ref 并不会立即获得

如果是这个原因的话，可以尝试将 KeepAlive 提到更外层，看问题是否可解

可参考 [issue](https://github.com/alitajs/umi-plugin-keep-alive/issues/14#issuecomment-655308065) 

例如：
```jsx
export default function FormComponent() {
  const [form] = Form.useForm()
  const formRef = useRef(null)

  return (
    <KeepAlive>
      <Form
        form={form}
        ref={formRef}
      />
    </KeepAlive>
  )
}
```

调整为
```jsx
function FormComponent() {
  const [form] = Form.useForm()
  const formRef = useRef(null)

  return (
    <Form
      form={form}
      ref={formRef}
    />
  )
}

export default (props) => (
  <KeepAlive>
    <FormComponent {...props} />
  <KeepAlive>
)
```

**Comment by YoutheEnd** [comment]
![image](https://user-images.githubusercontent.com/26157631/87914389-23f59b00-caa3-11ea-97a5-6d330aacf04d.png)
![image](https://user-images.githubusercontent.com/26157631/87914440-340d7a80-caa3-11ea-978d-457c93436252.png)
![image](https://user-images.githubusercontent.com/26157631/87914493-4982a480-caa3-11ea-90e4-424fd2e379b6.png)
您好，现在按您说的方式改了一下，但是还会出现空白页面的情况

**Comment by CJY0208** [comment]
目前调整的方式并不是如我所说的调整呢，这个方式仍旧是可能产生问题的调整
