### ISSUE TITLE
react-router <Prompt> broken

### ISSUE THREAD

**Issue by shuozhang2016** [CJY0208/react-activation#56]
![WX20200728-120223](https://user-images.githubusercontent.com/17228552/88617875-39ce1600-d0ca-11ea-870f-4300a13819a5.png)

**Comment by CJY0208** [comment]
Make sure that your <AliveScope /> is renderred inside <Router />

**Comment by shuozhang2016** [comment]
谢谢，  解决了我的问题。 作者给力

**Comment by CJY0208** [comment]
OK :)
