### ISSUE TITLE
切换路由再回来,ref引用的元素就全部失效了,直接报错

### ISSUE THREAD

**Issue by mike8625** [CJY0208/react-activation#57]
这个问题感觉不好解决啊

**Comment by CJY0208** [comment]
描述不够清晰，需要呈现具体问题场景，是否可能与以下有关？

[Breaking Change 由实现原理引发的额外问题](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#breaking-change-%E7%94%B1%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86%E5%BC%95%E5%8F%91%E7%9A%84%E9%A2%9D%E5%A4%96%E9%97%AE%E9%A2%98)

**Comment by mike8625** [comment]
<keepalive>
  <div ref="xxx"></div>
</keepalive>
我可以访问this.refs.xxx, 但是我切换路由然后再回来,再访问this.$refs.xxx 就报错 说未定义

**Comment by mike8625** [comment]
`keepalive
  div ref="xxx" div
/keepalive
`

我可以访问this.refs.xxx, 但是我切换路由然后再回来,再访问this.$refs.xxx 就报错 说未定义

**Comment by CJY0208** [comment]
可以做一个可复现的 demo 吗？这么描述看不出来是什么原因，可能和你的使用方式有关，我自己没有遇到类似的问题

**Comment by mike8625** [comment]
好的 我下班了 明天弄一下 多谢了 大佬

**Comment by mike8625** [comment]
领导说,太麻烦就不用了,改成vue了,不用解决了,多谢了

**Comment by haiancaomin** [comment]
你是不是添加了事件监听，在监听函数里使用了$refs？如果是，在页面beforeDestroy(){}钩子里去除事件监听就解决了，这样切换路由跳到其他页面的时候就不存在这个事件，自然不会报错了。因为你在A页面添加比如resize事件来获取A页面的元素，跳到B页面后，事件监听还在，但已经获取不到A页面的元素了，故报错。
