### ISSUE TITLE
处理有开场动画的组件时初始化会有大小错位

### ISSUE THREAD

**Issue by Col0ring** [CJY0208/react-activation#58]
在进行有 requestAnimationFrame 的动画时，初始化宽高会错位

![a](https://user-images.githubusercontent.com/47329987/89204057-17675b80-d5e8-11ea-89d6-efd2c55fb2db.gif)

**Comment by CJY0208** [comment]
被 KeepAlive 包裹的组件会拥有两层 div 包裹，类名分别是  .ka-wrapper 和 .ka-content

是否有可能是样式上的问题？可以试着调整样式来解决
