### ISSUE TITLE
You should not use <KeepAlive /> outside a <AliveScope>

### ISSUE THREAD

**Issue by YoutheEnd** [CJY0208/react-activation#59]
请教以下：
1、封装了一个公共的组件放在了自己的私库里面，这个组件最外层包裹了<KeepAlive>用于把组件缓存
2、在一个主应用里面最外层包裹了<AliveScope>组件，然后npm link的形式把封装的组件引进来
会出现下面这个错误
![image](https://user-images.githubusercontent.com/26157631/89246423-ad79a100-d63d-11ea-9f82-c11be63328f5.png)

自己封装的组件
import React from "react";
// import ComponentCache from "../../components/ComponentCache";
import ReactForm from './components/ReactForm';
import KeepAlive from 'react-activation';
import "./index.less"

const ReactFnc = (props) => {

    return (
        <KeepAlive name={props.location.pathname} >
            <ReactForm />
        </KeepAlive>
    )
};

export default ReactFnc;

主应用的：
<IntlProvider locale={obj[lan]} messages={appLocale}>
            <HashRouter>
                <AliveScope>
                    <Switch>
                        <Route exact path="/login" component={Login}/>
                        <Route
                            path="/"
                            render={() => {
                                if (!token) {
                                    return <Redirect to="/login"/>;
                                } else {
                                    return <Layout/>;
                                }
                            }}
                        />
                    </Switch>
                </AliveScope>
            </HashRouter>
        </IntlProvider>

**Comment by CJY0208** [comment]
需要确保你的 KeepAlive 被渲染在 AliveScope 内部，需要检查你的 HOC 渲染位置

**Comment by YoutheEnd** [comment]
> 需要确保你的KeepAlive被渲染在AliveScope内部，需要检查你的HOC渲染位置

检查了一下，KeepAlive是放在AliveScope里面的
![image](https://user-images.githubusercontent.com/26157631/89249706-8030f100-d645-11ea-80f4-b319c8dc13ca.png)
![image](https://user-images.githubusercontent.com/26157631/89249722-89ba5900-d645-11ea-80c6-90e136598cc5.png)
![image](https://user-images.githubusercontent.com/26157631/89249789-abb3db80-d645-11ea-838e-7ed94ce65227.png)

**Comment by CJY0208** [comment]
有可能是私库中 react-activation 与项目中的 react-activation 版本不一致，检查一下 node_modules 是否存在多个 react-activation 
 包，如果是的话，需要调平版本

**Comment by YoutheEnd** [comment]
> 有可能是私库中 react-activation 与项目中的 react-activation 版本不一致，检查一下 node_modules 是否存在多个 react-activation
> 包，如果是的话，需要调平版本

就一个版本的 0.5.5
![image](https://user-images.githubusercontent.com/26157631/89757648-6b0e0380-db18-11ea-96ad-f0f3e6fd8728.png)

**Comment by CJY0208** [comment]
待提供复现 demo，长时间未跟进，暂时关闭
