### ISSUE TITLE
UMI 3.x里面想缓存所有的路由，怎么使用

### ISSUE THREAD

**Issue by xjtdevelop** [CJY0208/react-activation#60]
是不是在baseLayout.jsx里面用用AliveScope和KeepAlive把children包起来
      <AliveScope>
        <Authorized authority={authorized.authority} noMatch={noMatch}>
        <KeepAlive>
            {children}

        </KeepAlive>
        </Authorized>
        </AliveScope>

**Comment by xjtdevelop** [comment]
<AliveScope>
        <Authorized authority={authorized.authority} noMatch={noMatch}>
        <KeepAlive>
            {children}

        </KeepAlive>
        </Authorized>
        </AliveScope>

**Comment by CJY0208** [comment]
可以使用 [umi-plugin-keep-alive](https://github.com/alitajs/umi-plugin-keep-alive) 插件实现，不过需要手动做缓存，如何做到自动缓存全部路由需要摸索一下

**Comment by xiaowenming** [comment]
@xjtdevelop 你好 , 我也碰到同样的问题 , 请问你实现了么

**Comment by xjtdevelop** [comment]
我实现了



---原始邮件---
发件人: "xiaowenming"<notifications@github.com&gt;
发送时间: 2020年8月21日(周五) 下午3:48
收件人: "CJY0208/react-activation"<react-activation@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xjtdevelop"<826279192@qq.com&gt;;
主题: Re: [CJY0208/react-activation] UMI 3.x里面想缓存所有的路由，怎么使用 (#60)




 
@xjtdevelop 你好 , 我也碰到同样的问题 , 请问你实现了么

**Comment by xiaowenming** [comment]
@xjtdevelop 能不能麻烦大佬讲解下思路 , 或者贴下demo , 我研究了两天了没有成功

**Comment by xjtdevelop** [comment]
https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy ，参考大佬的



---原始邮件---
发件人: "xiaowenming"<notifications@github.com&gt;
发送时间: 2020年8月26日(周三) 上午10:20
收件人: "CJY0208/react-activation"<react-activation@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xjtdevelop"<826279192@qq.com&gt;;
主题: Re: [CJY0208/react-activation] UMI 3.x里面想缓存所有的路由，怎么使用 (#60)




 
@xjtdevelop 能不能麻烦大佬讲解下思路 , 或者贴下demo , 我研究了两天了没有成功
