### ISSUE TITLE
您好，我想问下，为何使用了KeepAlive组件后，无法在子组件中使用withRouter了啊

### ISSUE THREAD

**Issue by 1101916341** [CJY0208/react-activation#61]
一旦使用，就会报错，
 **Invariant failed: You should not use <withRouter(BizdeptemailTable) /> outside a <Router>**

**Comment by CJY0208** [comment]
好的，这个情况之前有同学反馈过，不过一直没有复现，能否提供一个 demo 呢？

**Comment by 1101916341** [comment]
demo的话无法提供，那您方便出一个正确的使用流程吗？我想对比一下看看问题在哪里

**Comment by CJY0208** [comment]
对了，AliveScope 需要放置在 Router 内部，这一步可能导致问题

如果已经做了的话，可能是 activation 高阶组件的问题，不一定是流程的问题

**Comment by 1101916341** [comment]
AliveScope 不是放在全局位置吗？就是 index.tsx 或者 app.tsx中吗？

**Comment by CJY0208** [comment]
是的，不过要注意嵌在全局 Router 或 redux 的 Provider 组件中，否则 KeepAlive 内部的组件将丢失上下文

**Comment by 1101916341** [comment]
您好，您的关闭功能有些难理解啊，我在点击关闭时，调用的时drop()，里面传递的时name属性，但是关闭之后，再次打开该页面还是没有请求接口，我标签页遍历展示的和getCachingNodes()数据不一致，我进行了getCachingNodes()遍历之后，对比数据，这样还是没有效果

**Comment by 1101916341** [comment]
您好，关于全部卸载功能，clear(), 在当前页面进行全部关闭时，会保留当前页面的缓存信息，这是什么情况啊？

**Comment by CJY0208** [comment]
> 您好，您的关闭功能有些难理解啊，我在点击关闭时，调用的时drop()，里面传递的时name属性，但是关闭之后，再次打开该页面还是没有请求接口，我标签页遍历展示的和getCachingNodes()数据不一致，我进行了getCachingNodes()遍历之后，对比数据，这样还是没有效果

drop 函数需要在 KeepAlive 确定被卸载，也就是处于 unactivated 状态下进行才有效，有可能是这个原因，导致了 drop 失败吗？

**Comment by 1101916341** [comment]
> > 您好，您的关闭功能有些难理解啊，我在点击关闭时，调用的时drop()，里面传递的时name属性，但是关闭之后，再次打开该页面还是没有请求接口，我标签页遍历展示的和getCachingNodes()数据不一致，我进行了getCachingNodes()遍历之后，对比数据，这样还是没有效果
> 
> drop 函数需要在 KeepAlive 确定被卸载，也就是处于 unactivated 状态下进行才有效，有可能是这个原因，导致了 drop 失败吗？

您好，如何确认KeepAlive是被卸载的状态啊？需要调用那个方法来查看啊？求大佬指点一下

**Comment by CJY0208** [comment]
比如以下，需要确保 show 为 false，并且 KeepAlive 已经完成了卸载

```jsx
{show && <KeepAlive />}
```
