### ISSUE TITLE
为什么在实例代码中没用看到AliveScope

### ISSUE THREAD

**Issue by k983551019** [CJY0208/react-activation#62]
我使用v5pro 下载后在welcome页面使用KeepAlive 会爆出错误， 加上AliveScope 就没有错误，
 但是并没有缓存，会触发unactivated 没触发activated。

**Comment by CJY0208** [comment]
AliveScope 是必要的，你是看哪个实例？

**Comment by k983551019** [comment]
> AliveScope 是必要的，你是看哪个实例？

https://github.com/CJY0208/react-activation/issues/62#issuecomment-676842307
可关闭的路由 tabs 示例（umijs）

**Comment by CJY0208** [comment]
这是 umijs 的示例，umi 组件内部包含了 AliveScope，如果不使用 umi 的话，需要手动放置 AliveScope

**Comment by k983551019** [comment]
> 这是 umijs 的示例，umi 组件内部包含了 AliveScope，如果不使用 umi 的话，需要手动放置 AliveScope

可是为什么我在V5.1 下使用
![image](https://user-images.githubusercontent.com/48147837/90709500-e9b03100-e2ce-11ea-8c0b-6714272624f1.png)
会出现这种错误
![image](https://user-images.githubusercontent.com/48147837/90709544-077d9600-e2cf-11ea-8c66-107207ec0215.png)

**Comment by CJY0208** [comment]
v5 pro 是基于 umi 吗？需要安装一下 umi-plugin-keep-alive

**Comment by k983551019** [comment]
> v5 pro 是基于 umi 吗？需要安装一下 umi-plugin-keep-alive

v5 pro 肯定是基于umi 安装了 umi-plugin-keep-alive。并没有变化

**Comment by k983551019** [comment]
还发现个问题 ，在运行时添加路由后新建页面可以出现效果keepalive效果，但是！ 如果吧程序听到 重新启动 之前新建的页面就会失效和之前一样！！！ 我感觉这可能是个bug

**Comment by CJY0208** [comment]
把程序停掉是啥意思？刷新页面嘛？目前的 KeepAlive 做不到刷新页面后保存哦

**Comment by k983551019** [comment]
> 把程序停掉是啥意思？刷新页面嘛？目前的 KeepAlive 做不到刷新页面后保存哦

现在奇怪的就是，新创建的页面可以keepalive，旧的就不行，一模一样 直接复制的，然后重新启动项目 有时候新的页面可以 有时候不行。离谱，  我使用的方法是， 下载一个v5.1 pro 然后安装 umi-plugin-keep-alive，在Welcome页面中使用<KeepAlive>  然后页面就会报上面的错误。

**Comment by CJY0208** [comment]
问题不是很明确，暂时关闭啦
