### ISSUE TITLE
请问下umirc 里面如何配置react-activation

### ISSUE THREAD

**Issue by ccc-chen** [CJY0208/react-activation#63]
[没有配置的时候试了下，如果被KeepAlive包裹则Tabs页签消失，点击时候路由也不对。
<img width="521" alt="WeChat4a6f0da76d6286b79df36856089a3a7d" src="https://user-images.githubusercontent.com/32119580/90850477-52b5a880-e3a4-11ea-9ab4-f9d6adedef42.png">
<img width="554" alt="WeChat5652fcbd21e4bc815bd7d8eae1bc8e7a" src="https://user-images.githubusercontent.com/32119580/90850492-5fd29780-e3a4-11ea-9ed9-53aa47277cb0.png">
<img width="773" alt="WeChat16fa6090e40565030bc8f9063c109de3" src="https://user-images.githubusercontent.com/32119580/90850532-7b3da280-e3a4-11ea-96f0-e247fed51ab9.png">

**Comment by CJY0208** [comment]
用这个插件就好了 [umi-plugin-keep-alive](https://github.com/alitajs/umi-plugin-keep-alive)

不需要放置 AliveScope，直接使用 KeepAlive 即可
