### ISSUE TITLE
路由嵌套使用 KeepAlive，内层组件会多次触发 active 对应的生命周期

### ISSUE THREAD

**Issue by win7killer** [CJY0208/react-activation#67]
业务里边用到了子路由。
一级路由 `/a`； 子路由 `/a/sub`；两个 route 的地方都用了 KeepAlive 处理.

结构大致如下：
```js
<Route>
    <KeepAlive>
        <Route>
            <KeepAlive></KeepAlive>
       </Route>
    </KeepAlive>
</Route>
```

但是二级路由对应的组件，会触发两次 `componentDidActivate ` 和 `componentWillUnactivate `;
一级路由的地方，会触发一次【正常】。

**Comment by CJY0208** [comment]
Mark，稍后我检查一下

**Comment by Freeyayo** [comment]
> Mark，稍后我检查一下

检查了吗

**Comment by CJY0208** [comment]
> > Mark，稍后我检查一下
> 
> 检查了吗

看过了，没啥异常，设计上外层 KeepAlive 激活状态变化的时候也会触发子层的相关生命周期，这个特性和 vue keep alive 设计一致的，父层的卸载也会通知到子层，方便做一些副作用消除的行为，比如暂停计时器之类的

**Comment by CJY0208** [comment]
触发了两次 componentDidActivate 的问题，当时可能是没做生命周期的触发优化，后来加上了，我自测 demo 中已经没有这个问题了，可以看看还是否会触发两次，如果还有的话，希望能提供用例进行检查，这个 issue 先关闭了
