### ISSUE TITLE
相同路由但是参数不同的情况下互相切换缓存不起作用

### ISSUE THREAD

**Issue by muermaru** [CJY0208/react-activation#68]
![image](https://user-images.githubusercontent.com/12495960/93963170-0e486e80-fd8f-11ea-858c-70c2b624e47e.png)

这是我的cachingNodes截图，场景是tab页中有两个路由相同只是参数不同的组件(下标1和2)，使用umi的history.push方法切换路由，但是如果是这两个路由之间切换的话(1->2)，缓存不会生效，只会展示当前的组件内容。

但是如果不是相互切换的情况下，比如1->0->2这个顺序，缓存就可以正常生效，请问这个问题如何处理

**Comment by CJY0208** [comment]
给 KeepAlive 加上 key 属性试试

**Comment by muermaru** [comment]
@CJY0208 还是不行……

**Comment by muermaru** [comment]
项目的业务场景是每个keepalive包裹的都是页面组件，我发现如果是keepalive里包裹的不是一个自定义的组件，而是多个组件或者只是单个组件的话，就会出现这个问题。如果我把这些组件抽出来写成一个组件，然后让keepalive包裹这个单独的自定义组件的话，就可以正常。@CJY0208

如原来：
```
export default (props: any) => {
  ...业务逻辑代码
  return (
    <KeepAlive>
      // 一个业务组件，比如ProTable
      <ProTable />
    </KeepAlive>
  )
}
```

改成：
```
function List (props:any) {
   ...业务逻辑代码
  return <ProTable />
}

export default (props: any) => {
  return (
    <KeepAlive>
      <List />
    </KeepAlive>
  )
}
```

**Comment by CJY0208** [comment]
上述用例确实不是 KeepAlive 的目标场景，KeepAlive 能保持的是它内部的组件状态，如果业务逻辑也想被保持，确实需要封装成组件，保证完全被 KeepAlive 包裹，

不过当前的问题也有其他小伙伴正在反馈，例如以下场景当中依然存在问题，目前还没有定位，场景下可能仍然存在问题
![image](https://user-images.githubusercontent.com/18415774/98622205-ebc0e380-2343-11eb-8520-24048d952c92.png)

**Comment by CJY0208** [comment]
暂无响应，关闭
