### ISSUE TITLE
使用 drop  删除 缓存节点  不生效 

### ISSUE THREAD

**Issue by yangtanyu** [CJY0208/react-activation#73]
![image](https://user-images.githubusercontent.com/50374470/96852095-4ffe2f00-148b-11eb-994c-438518f832d5.png)

console.log(343333,'获取所有的缓存节点',getCachingNodes())

    let delObj =  getCachingNodes().find((a)=>a.name ===targetKey )

    console.log(3822,'需要删除的对象的name',delObj.name)

    dropScope(delObj.name)
    drop(delObj.name)

    // clear()

    console.log(358888888,'删除后的获取所有的  缓存节点',getCachingNodes())

执行后 需要卸载的缓存对象 还在（就是3588888与34333333还是一样的数组），  没有删除，我看大佬您 在之前的  解答中  有说  需要在 休眠状态下才能 drop（name）卸载 ，需要怎样  才能让其休眠。     在issuse  50   中  您有提到 ‘refresh’    请问一下 refresh   该如何使用？？  希望大佬 解答一下

**Comment by Mr-Lucky** [comment]
我也刚遇到这个问题，你可以先setTimeout 延迟一下执行drop试试。
期待大佬有其他解决方法

**Comment by yangtanyu** [comment]
@Mr-Lucky   谢谢   按照您的 指引   我加了个 promise  函数 处理，也明白了  作者所说的  激活的 含义，   激活 就是指当前的keeplive 是否正在显示，比如说  现在的keeplive正在显示，而我们又要去卸载它 ，这是冲突的，所以会忽略卸载当前 keeplive     @CJY0208  不知道 我理解得是否正确

**Comment by CJY0208** [comment]
@yangtanyu 是的，当 KeepAlive 需要被显示时，却要卸载它，就算卸载成功了，也会因为符合显示条件而重新被挂载

从表现上来说，这次卸载的效果等同于刷新，但因为不合逻辑，所以干脆拆分了 drop 和 refresh 函数，如果激活状态下要做卸载的话，会被 activation 忽略掉 drop 行为

**Comment by CJY0208** [comment]
无响应，关闭
