### ISSUE TITLE
使用KeepAlive包裹组件以后，为什么我路由切换回来的时候，useEffect里面还会执行呢

### ISSUE THREAD

**Issue by bihongbin3027** [CJY0208/react-activation#74]
使用KeepAlive包裹组件以后，为什么我路由切换回来的时候，useEffect里面还会执行呢

**Comment by CJY0208** [comment]
需要看 effect 的 deps 是如何写的，因为组件未被卸载，如果触发了 deps 的变动，effect 依然会执行
