### ISSUE TITLE
umi中引用之后报错,V5版本

### ISSUE THREAD

**Issue by shaohuatsou** [CJY0208/react-activation#78]
app.ts:
![image](https://user-images.githubusercontent.com/50793943/98063143-4f519980-1e8a-11eb-90e9-836f63da595f.png)

自定义layout:
![image](https://user-images.githubusercontent.com/50793943/98063178-642e2d00-1e8a-11eb-8716-61ac245e648f.png)

page1:
![image](https://user-images.githubusercontent.com/50793943/98063191-6bedd180-1e8a-11eb-841c-f6e70b8665d7.png)

page2:
![image](https://user-images.githubusercontent.com/50793943/98063205-7314df80-1e8a-11eb-8c9f-5b11a8d9c561.png)

报错：
![image](https://user-images.githubusercontent.com/50793943/98063233-83c55580-1e8a-11eb-9894-7b14b1ce9cc5.png)

用npm或yarn都全新安装过也不行。

**Comment by CJY0208** [comment]
微信沟通后，非 activation 原因，umi 部分依赖所致，关闭此 issue
