### ISSUE TITLE
与react-loadable一起使用，好像keeplive失效了

### ISSUE THREAD

**Issue by tongsanghua** [CJY0208/react-activation#79]

**Comment by tongsanghua** [comment]
<KeepLive>包裹的组件可以是按需加载的吗

**Comment by CJY0208** [comment]
尝试增加以下代码进行 loadable 兼容

```jsx
import { NodeKey } from 'react-activation';

NodeKey.defaultProps.onHandleNode = (node, mark) => {
  // 因异步组件 loaded 后会去掉 LoadableComponent 层，导致 nodeKey 变化，缓存定位错误
  // 故排除对 LoadableComponent 组件的标记，兼容异步加载组件
  if (node.type && node.type.displayName === 'LoadableComponent') {
    return undefined;
  }

  return mark;
};
```

**Comment by yshysh123** [comment]
问下楼主这个问题解决了吗？我也遇到相同的问题

**Comment by tongsanghua** [comment]
> 问下楼主这个问题解决了吗？我也遇到相同的问题

用作者提供的办法试了，还是不行
https://codesandbox.io/s/luyouzhuanchangdonghuashili-forked-pwk9n

**Comment by tongsanghua** [comment]
> 尝试增加以下代码进行 loadable 兼容
> 
> ```js-jsx
> import { NodeKey } from 'react-activation';
> 
> NodeKey.defaultProps.onHandleNode = (node, mark) => {
>   // 因异步组件 loaded 后会去掉 LoadableComponent 层，导致 nodeKey 变化，缓存定位错误
>   // 故排除对 LoadableComponent 组件的标记，兼容异步加载组件
>   if (node.type && node.type.displayName === 'LoadableComponent') {
>     return undefined;
>   }
> 
>   return mark;
> };
> ```

试了一下，感觉不咋行
https://codesandbox.io/s/luyouzhuanchangdonghuashili-forked-pwk9n

**Comment by CJY0208** [comment]
在线示例中做如上调整后，缓存是正常的，不加 3 楼的修复措施也可用

**Comment by yshysh123** [comment]
我将react-loadable替换成react.lazy  缓存是OK的。

**Comment by conkyliu** [comment]
> 我将react-loadable替换成react.lazy 缓存是OK的。

你用react.lazy 会不会把没有引用的静态资源也打包进去呢
