### ISSUE TITLE
在非doument.body和document.documentElement的屏幕滚动问题

### ISSUE THREAD

**Issue by HelloAny** [CJY0208/react-activation#81]
当我的共享滚动容器不在`Body`和`Html`上使用插件的时候，会出现滚动高度无法保存的问题，虽然这个应该是`react-router-dom`的问题，但是希望能有解决方案

问题样例：
https://codesandbox.io/s/nifty-jepsen-4hs1k

一些思路：
在`keepAlive`上可以添加新的`props`，比如提供一个监听`class`或`id`的接口来监听当前容器的滚动高度，然后保存不同界面的高度`<KeepAlive onListen="#App">`。

**Comment by CJY0208** [comment]
直接借用 saveScrollPosition prop 的位置如何？

三种取值

1. `screen` 监听屏幕共用容器
2. true/false 监听 KeepAlive 内部
3. selector name 监听指定 dom 节点如 `#App` 或  `.my-view .my-scroll-view`

相较于目前，新增了第 3 项

**Comment by HelloAny** [comment]
> 直接借用 saveScrollPosition prop 的位置如何？
> 
> 三种取值
> 
> 1. `"screen"`:  监听屏幕共用容器
> 2. `true | false`:  监听 KeepAlive 内部
> 3. `selector name`:  监听指定 dom 节点
> 
> ```js-jsx
> <KeepAlive saveScrollPosition="screen">
> <KeepAlive saveScrollPosition>
> <KeepAlive saveScrollPosition=".my-view .my-scroll-view">
> ```
> 
> 相较于目前，新增了第 3 项

嗯，可以

**Comment by CJY0208** [comment]
OK 了，v0.6.1，试试~

**Comment by HelloAny** [comment]
@CJY0208 谢谢大佬，OK了

**Comment by CJY0208** [comment]
OK，那这个关了哦
