### ISSUE TITLE
当keepAlive和TransitionGroup一起使用，2个页面全部缓存滚动条位置时，切换页面动画异常

### ISSUE THREAD

**Issue by calmchang** [CJY0208/react-activation#82]
[重现地址  codesandbox](https://codesandbox.io/s/luyouzhuanchangdonghuashili-forked-q1o9c?file=/src/index.js)
重现方式
1、切到页面 two 然后将滚动条拖到最下方，因为two有40条记录，而页面one只有20条记录，所以他们滚动条长度不一样
2、切换到 one 可以发现切换的时候页面并没正确展示动画，并且滚动条异常

**Comment by CJY0208** [comment]
示例中滚动容器共享，两个内容长度不一的页面在做切换时必然会存在动画异常（整体高度以最高内容为准）

需要考虑各页面自建滚动容器以解决

**Comment by calmchang** [comment]
> 示例中不使用 KeepAlive，问题也是存在的
> 
> 原因为滚动容器共享，两个内容长度不一的页面在做切换时必然会存在动画异常（整体高度以最高内容为准）
> 
> 需要考虑各页面自建滚动容器以解决

感谢大佬回答，的确，应该给每个页面自己设定滚动容器就好了

**Comment by CJY0208** [comment]
OK，那这条我关掉啦
