### ISSUE TITLE
大佬，我想问下，该插件兼容redux吗？因为详情页面的数据，都是用的同一个字段，每次请求新的详情页面，都会替换之前的redux数据，关于该问题，您这边有解决方法吗？

### ISSUE THREAD

**Issue by 1101916341** [CJY0208/react-activation#84]
大佬，我想问下，该插件兼容redux吗？因为详情页面的数据，都是用的同一个字段，每次请求新的详情页面，都会替换之前的redux数据，关于该问题，您这边有解决方法吗？

**Comment by CJY0208** [comment]
兼容 redux 的，我项目中和 redux 一同使用，没遇到过类似问题，可以做一个最小复现场景吗？

**Comment by 1101916341** [comment]
大佬，就是那种开多个详情页，页签的那种，不关闭，但是这些详情页都是用的同一个公共的字段，他们的值不会被相互替换吗？您能否简单说一下实现的具体步骤啊？拜托了😳

**Comment by CJY0208** [comment]
如果都直接连接了 redux 的数据，当然是会被替换的，如果要处理的话，方式也比较简单，详情页加载完成后，从 redux 拿初始数据就好了，拿到数据后就切断和 redux 的联系

例如 
```jsx
function Details() {
  const reduxDetails = useSelector(state => state.currentDetails)
  const [details, setDetails] = useState(reduxDetails)

  return ...
}
```

**Comment by 1101916341** [comment]
好的，谢谢大佬的指点，我这就去试一下，要是可行的话，我会自己关闭当前任务的☺

**Comment by 1101916341** [comment]
> 如果都直接连接了redux的数据，当然是会被替换的，如果要处理的话，方式也比较简单，详情页加载完成后，从redux拿到初始数据就好了，拿到数据后就切断和redux的联系
> 
> 例如
> 
> ```js-jsx
> 功能 细节（）{
>   常量 reduxDetails  =  useSelector（状态 => 状态。currentDetails）
>    const的[细节，setDetails ] =  useState（reduxDetails）
> 
>   返回 ... 
> }
> ```
大佬，我刚刚使用了一下，第一次加载数据的时候，数据加载不上去，但是打开其他页面的话，会把第一次加载的数据赋值上去，就是，每打开一个详情页，都是渲染的上一个详情的数据，您看这样该如何解决啊？😭

**Comment by CJY0208** [comment]
这种方式思路上应该没啥问题，具体数据的时机我就不太了解你们项目的情况了，需要你自己想办法了

**Comment by 1101916341** [comment]
问题已解决
