### ISSUE TITLE
react-activation/babel似乎也给Fragment加了_nk属性

### ISSUE THREAD

**Issue by chenvd** [CJY0208/react-activation#86]
项目里面用了一些Fragment，react-activation/babel给Fragment也添加了_ng属性，于是控制台输出了很多警告
<img width="805" alt="iShot2020-12-29 23 49 10" src="https://user-images.githubusercontent.com/9840477/103296180-85496f00-4a30-11eb-8854-16097659429a.png">

**Comment by CJY0208** [comment]
Fragment 的代码截图有嘛，插件里已经做了大部分 Fragment 场景的排除处理，可能还漏了一些场景



---原始邮件---
发件人: "chenvd"<notifications@github.com&gt;
发送时间: 2020年12月29日(周二) 晚上11:49
收件人: "CJY0208/react-activation"<react-activation@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [CJY0208/react-activation] react-activation/babel似乎也给Fragment加了_nk属性 (#86)




 
项目里面用了一些Fragment，react-activation/babel给Fragment也添加了_ng属性，于是控制台输出了很多警告

**Comment by chenvd** [comment]
> Fragment 的代码截图有嘛，插件里已经做了大部分 Fragment 场景的排除处理，可能还漏了一些场景
> […](#)
> ---原始邮件--- 发件人: "chenvd"<notifications@github.com&gt; 发送时间: 2020年12月29日(周二) 晚上11:49 收件人: "CJY0208/react-activation"<react-activation@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [CJY0208/react-activation] react-activation/babel似乎也给Fragment加了_nk属性 (#86) 项目里面用了一些Fragment，react-activation/babel给Fragment也添加了_ng属性，于是控制台输出了很多警告 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是使用高级组件包裹了Fragment，用来处理权限的问题，是不是这样导致无法判断是否是Fragment

**Comment by CJY0208** [comment]
嗯嗯，原因是 babel 插件无法区分自定义 Fragment ，所以打上了标记，这个我想想怎么搞合适

目前最快的修正方法是调整一下上图的写法，如下

```jsx

const EditFragment = withAuth('edit', ({ children }) => (
  <Fragment>{children}</Fragment>
))
```

**Comment by chenvd** [comment]
> 嗯嗯，原因是 babel 插件无法区分自定义 Fragment ，所以打上了标记，这个我想想怎么搞合适
> 
> 目前最快的修正方法是调整一下上图的写法，如下
> 
> ```js-jsx
> const EditFragment = withAuth('edit', ({ children }) => (
>   <Fragment>{children}</Fragment>
> ))
> ```

好的 ，非常感谢

**Comment by CJY0208** [comment]
思来想去，babel 插件想要区分自定义 Fragment 还是比较困难，自定义的方式颇多，程序无法判定

此问题决定暂不解决，需要使用者注意不要直接对 Fragment 进行 props 传递，避免 _nk 属性流到 Fragment 上
