### ISSUE TITLE
第一次进入页面和下一次进入当前缓存页面useActivate执行多次，有哪些可能的情况呢

### ISSUE THREAD

**Issue by pk110** [CJY0208/react-activation#87]
第一次进入页面和下一次进入当前缓存页面useActivate执行多次，有哪些可能的情况呢

**Comment by CJY0208** [comment]
应用中短时内触发了多次对该组件的卸载和挂载，去掉 KeepAlive 外层后，观测组件的 didMount 和 unmount 是否也触发了多次

**Comment by CJY0208** [comment]
长期无响应，暂时关闭，期望能提供复现 demo
