### ISSUE TITLE
建议给KeepAlive添加自定义属性，可以在getCachingNodes中获取

### ISSUE THREAD

**Issue by KellenHe** [CJY0208/react-activation#88]
结合umi使用的多tab场景下。无法给tab自定义名字。
目前KeepAlive只有一个name属性可以使用，id属性会自动在后面追加一个名字。

**Comment by CJY0208** [comment]
刚才试了一下，你说的这个功能应该是现有的，getCachingNodes 将返回 KeepAlive 实例，包括其获得的 props

![image](https://user-images.githubusercontent.com/18415774/105572442-17c00280-5d92-11eb-8f08-183f3af1021e.png)
