### ISSUE TITLE
如何微信里面缓存 

### ISSUE THREAD

**Issue by yangjunjie520** [CJY0208/react-activation#9]
试验了下 在微信浏览器里 列表数据跳转列表详情 在回退后 会重新在执行request请求 渲染   我是在componentDidMount里执行的request  请问下是我request 写的位置不对还是不支持微信缓存

**Comment by CJY0208** [comment]
微信页面的跳转是用前端路由管理的吗？还是普通的网页跳转呢

**Comment by yangjunjie520** [comment]
前端路由跳转

**Comment by yangjunjie520** [comment]
> 微信页面的跳转是用前端路由管理的吗？还是普通的网页跳转呢

前端路由跳转

**Comment by yangjunjie520** [comment]
> 微信页面的跳转是用前端路由管理的吗？还是普通的网页跳转呢

![image](https://user-images.githubusercontent.com/21153269/67936050-011a1280-fc06-11e9-865f-a1d442777360.png)
![image](https://user-images.githubusercontent.com/21153269/67936087-12fbb580-fc06-11e9-90c6-f88a358518e8.png)
这是加载数据渲染数据代码

**Comment by CJY0208** [comment]
TestIndex 是如何使用的？

**Comment by yangjunjie520** [comment]
> TestIndex 是如何使用的？
TestIndex 直接配置对行路由
![image](https://user-images.githubusercontent.com/21153269/67938722-029a0980-fc0b-11e9-80b4-0a591331511c.png)

**Comment by yangjunjie520** [comment]
> TestIndex 是如何使用的？

直接对应的路由
![image](https://user-images.githubusercontent.com/21153269/67938864-4bea5900-fc0b-11e9-8f25-a76a958f6301.png)

**Comment by CJY0208** [comment]
AliveScope 需要放置在不会被卸载的地方，按上图，应该作为 Router 的第一个子元素

**Comment by yangjunjie520** [comment]
> AliveScope 需要放置在不会被卸载的地方，按上图，应该作为 Router 的第一个子元素

好的 我试下  感谢大佬

**Comment by yangjunjie520** [comment]
> AliveScope 需要放置在不会被卸载的地方，按上图，应该作为 Router 的第一个子元素

![image](https://user-images.githubusercontent.com/21153269/67998865-eb076300-fc94-11e9-8ca6-4568aa01ab9b.png)
 Router 的第一个子元素  回退request还是会刷新

**Comment by CJY0208** [comment]
KeepAlive 标签不需要换位置，只是 AliveScope 需要变更而已，KeepAlive 之前的使用方式是正确的

**Comment by yangjunjie520** [comment]
> KeepAlive 标签不需要换位置，只是 AliveScope 需要变更而已，KeepAlive 之前的使用方式是正确的
好的

**Comment by CJY0208** [comment]
@yangjunjie520 

如何呀？
