### ISSUE TITLE
useActivate和useUnactivate不会触发，useEffect每次都会触发，请问是什么原因

### ISSUE THREAD

**Issue by KellenHe** [CJY0208/react-activation#91]
`
  useEffect(() => {
    notification.info({
      message: '[Chart] mounted'
    })

    return () => {
      notification.error({
        message: '[Chart] unmounted'
      })
    }
  }, [])

  useActivate(() => {
    notification.success({
      message: '[Chart] activated'
    })
  })
  useUnactivate(() => {
    notification.warning({
      message: '[Chart] unactivated'
    })
  })
`
模仿umi多tab的例子在项目里写的，发现useActivate和useUnactivate怎么都不会触发。
反而useEffect会在第一次加载和关闭tab时触发，切换离开也会触发。
界面的数据也确实被缓存了，不知道是什么原因导致的。

**Comment by CJY0208** [comment]
可以提供你的例子嘛？

**Comment by flarelove** [comment]
这个有解决方案了吗？

**Comment by CJY0208** [comment]
还没有，能提供简单的 demo 吗？@flarelove

**Comment by flarelove** [comment]
> 还没有，能提供简单的 demo 吗？@flarelove

我包裹写的有问题。
应该用keepAlive标签这样包裹导出。
![1](https://user-images.githubusercontent.com/49007955/110901328-2614ae80-833f-11eb-9dea-d3d2944544a2.png)

而不是这样。
![2](https://user-images.githubusercontent.com/49007955/110901383-388ee800-833f-11eb-9c19-672fb4545132.png)

用第二种方法的话，只会缓存dom树，会导致组件重新加载（state重新初始化）。

**Comment by CJY0208** [comment]
无反馈，暂时关闭
