### ISSUE TITLE
IOS10.3.3上页面一片空白

### ISSUE THREAD

**Issue by luxurydragon** [CJY0208/react-activation#92]
作者大大，页面缓存功能确实强大，但今天测试发现在ios10.3.3上页面展示一片空白，我排查了之后发现去掉KeepAlive后页面就恢复正常，而我使用的功能相对简单，只是使用了AliveScope和KeepAlive。目前手头机子有限，ios最老的版本就是10.3.3，安卓和手上其他ios版本上没有问题，就ios10.3.3页面空白，麻烦作者大大可以看下这个问题

**Comment by CJY0208** [comment]
我没有可用的设备，你那边能用 vConsole 或者 eruda 之类的工具看到错误栈嘛？

**Comment by luxurydragon** [comment]
> 我没有可用的设备，你那边能用 vConsole 或者 eruda 之类的工具看到错误栈嘛？

**Comment by luxurydragon** [comment]
> > 我没有可用的设备，你那边能用 vConsole 或者 eruda 之类的工具看到错误栈嘛？

**Comment by luxurydragon** [comment]
> 我没有可用的设备，你那边能用 vConsole 或者 eruda 之类的工具看到错误栈嘛？

![1](https://user-images.githubusercontent.com/21510896/106080446-ff653480-6151-11eb-8ef7-25e24fda7304.png)

**Comment by luxurydragon** [comment]
> 我没有可用的设备，你那边能用 vConsole 或者 eruda 之类的工具看到错误栈嘛？

不好意思，我不确定图片是否能看到，因为这边我这里github的图是显示不出来的，所以我补充下错误的代码：Invalid attempt to spread non-iterable instance。麻烦作者大大看下

**Comment by CJY0208** [comment]
看起来是某个不可解构的值被解构了，点击错误后能看到错误堆栈吗？eruda 好像有这个功能，如果能看到堆栈的话对错误定位会很有帮助

**Comment by luxurydragon** [comment]
> 看起来是某个不可解构的值被解构了，点击错误后能看到错误堆栈吗？eruda 好像有这个功能，如果能看到堆栈的话对错误定位会很有帮助

你好，错误堆栈是这样的：
![3](https://user-images.githubusercontent.com/21510896/106091223-e915a380-6166-11eb-962d-883fd7d9d581.png)
![4](https://user-images.githubusercontent.com/21510896/106091226-eadf6700-6166-11eb-91f3-b557d7a46ad3.png)
![5](https://user-images.githubusercontent.com/21510896/106091227-eb77fd80-6166-11eb-8aeb-f0cf9a62b071.png)
![2](https://user-images.githubusercontent.com/21510896/106091229-eb77fd80-6166-11eb-8600-f558881d509c.png)
我根据错误信息查找后觉得问题应该出在datum8413:34这个位置，麻烦作者大大看下：
![datum8413-34](https://user-images.githubusercontent.com/21510896/106091357-385bd400-6167-11eb-80fa-224a6cdbdba0.png)

**Comment by CJY0208** [comment]
发了 0.7.3 尝试修复此问题，可以试试

**Comment by luxurydragon** [comment]
> 发了 0.7.3 尝试修复此问题，可以试试

好的，谢谢大大

**Comment by luxurydragon** [comment]
> 发了 0.7.3 尝试修复此问题，可以试试

作者大大，刚更新0.7.3，发现同样代码下，在KeepAlive里的内容不会添加到html节点里了，内容不展示，但是componentDidMount里发出的请求照常，麻烦大大看下

**Comment by CJY0208** [comment]
我先撤销这个改动

**Comment by CJY0208** [comment]
@luxurydragon 
新版本中已经尝试修复了，可以帮忙看看是否还有问题

**Comment by luxurydragon** [comment]
> @luxurydragon
> 新版本中已经尝试修复了，可以帮忙看看是否还有问题

好的，辛苦大大了

**Comment by luxurydragon** [comment]
> @luxurydragon
> 新版本中已经尝试修复了，可以帮忙看看是否还有问题

大大，不好意思，这两天手头没有那部机子，今天测了下ios10.3.3后，没有错误问题，但是KeepAlive里面的内容无法展示

**Comment by CJY0208** [comment]
OK，那可能是 iOS 10.3.3 的 DOM 操作存在一定毛病了

**Comment by CJY0208** [comment]
无可重现场景，暂时关闭
