### ISSUE TITLE
dropScope通过name卸载 能否增加个Id参数

### ISSUE THREAD

**Issue by k983551019** [CJY0208/react-activation#93]
路由是 path: '/welcome/welcome1/:id',  这种多详情
通过dropScope 卸载 会吧所有的welcome/welcome1/:id页面都卸载
而不能只卸载welcome/welcome1/text  这种
加个id    可能可以解决这个问题

**Comment by CJY0208** [comment]
name 属性可以作为所期望的卸载 id 来使用
id 属性目前仅仅是用来提醒 KeepAlive 在同一个标签位置上创建多份缓存

```jsx
<Route path="/item/:id" render={props => (
  <KeepAlive name={props.location.pathname} id={props.match.params.id}>
    <Item />
  </KeepAlive>
)} />

// 定点爆破
dropScope('/item/1')
dropScope('/item/2')

// 全量爆破，使用正则
dropScope(/^\/item/)
```

可参考此示例：[可关闭的路由 tabs 示例](https://codesandbox.io/s/keguanbideyifangwenluyou-tab-shilikeanluyoucanshufenduofenhuancun-ewycx)

**Comment by CJY0208** [comment]
判定为无问题，暂时关闭
