### ISSUE TITLE
v0.7.3 中引入的问题： inject() 不能正常执行  

### ISSUE THREAD

**Issue by cyndra0** [CJY0208/react-activation#94]
https://github.com/CJY0208/react-activation/commit/7abff784de017f9156620f8416209405d1383ee5 为了修复这个 issue：https://github.com/CJY0208/react-activation/issues/92 时：
判断是否 iterable 的方式是 `node.children instance of Array` ，然而它的类型可能是 HTMLCollection ，所以就无法插入 DOM了 （appendChild argument 1 is not type of node）。

try-catch 把错误都吞掉啦~~~ 是不是至少来个 devWarning 比较好呢~

**Comment by CJY0208** [comment]
OK，mark

**Comment by CJY0208** [comment]
我先撤销改动，重发一版

**Comment by CJY0208** [comment]
发了 0.7.4

node.children 转 array 过程加了个 try catch，试了一下应该 OK 的
