### ISSUE TITLE
react-activation@0.8.0和antd的tree组件兼容问题

### ISSUE THREAD

**Issue by anrgct** [CJY0208/react-activation#99]
在react-activation@0.8.0版本中， antd的tree组件会导致使用tree组件组件第一次不能缓存，会触发constructor，但在react-activation@0.7.4不会触发
例子：https://codesandbox.io/s/luyouzhuanchangdonghuashili-forked-i7g5c

**Comment by anrgct** [comment]
react-activation/core/Bridge/Context/ConsumerBridge.js
`@@ -12,11 +12,13 @@ import { fixedContext, eventBus, updateListenerCache } from './fixContext'
 
 // 对 ConsumerWrapper 的递归结构，会在 devtool 中生成较深的嵌套结构，可用 hooks 消除嵌套结构
 class RecursiveConsumerBridge extends PureComponent {
   componentDidMount() {
     // 渲染时若 fixedContext 列表更新，则需强制刷新
-    eventBus.on('update', this.forceUpdate)
+    eventBus.on('update', () => {
+      this.forceUpdate()
+    })
   }
 
   componentWillUnmount() {
     eventBus.off('update', this.forceUpdate)
   }
@@ -109,6 +111,6 @@ function HooksConsumerBridge({ children: renderChildren, id }) {
 
 const ConsumerBridge = [useContext, useRef, useEffect].every(isFunction)
   ? HooksConsumerBridge
   : RecursiveConsumerBridge
 
-export default ConsumerBridge
+export default RecursiveConsumerBridge
`
我发现这样修改了以后，被KeepAlive包裹的Tree组件的第一次生成时会触发两次生命周期，但是第一次生成就可以缓存了
`
🚀 ~ file: index.jsx ~ line 25 ~ Index ~ constructor ~ constructor
index.jsx:62 🚀 ~ file: index.jsx ~ line 61 ~ Index ~ componentDidMount
index.jsx:25 🚀 ~ file: index.jsx ~ line 25 ~ Index ~ constructor ~ constructor
index.jsx:77 🚀 ~ file: index.jsx ~ line 61 ~ Index ~ componentWillUnactivate ~ componentWillUnactivate
index.jsx:67 🚀 ~ file: index.jsx ~ line 56 ~ Index ~ componentWillUnmount
index.jsx:62 🚀 ~ file: index.jsx ~ line 61 ~ Index ~ componentDidMount
index.jsx:57 🚀 ~ file: index.jsx ~ line 56 ~ Index ~ componentDidUpdate
index.jsx:72 🚀 ~ file: index.jsx ~ line 56 ~ Index ~ componentDidActivate ~ componentDidActivate
index.jsx:57 🚀 ~ file: index.jsx ~ line 56 ~ Index ~ componentDidUpdate
`

**Comment by CJY0208** [comment]
这块的设计还存在一些问题，我尝试重构

**Comment by CJY0208** [comment]
根据上述中的方案，在 0.8.1 中对 #101 做了临时修复
